/*
 * CalendarForSingleClient.java
 *
 * Created on December 19, 2005, 9:15 AM
 */

package rmischedule.schedule.print.ExtendedEmployeeReport;
import rmischeduleserver.util.StaticDateTimeFunctions;
import rmischedule.xprint.xdata.*;
import rmischedule.components.*;
import java.util.*;
import java.awt.*;
/**
 *
 * @author  Ira Juneau
 */
public class CalendarForSingleClient extends javax.swing.JPanel {
    
    private ArrayList<VisualDay> myDays;
    
    /** Creates new form CalendarForSingleClient */
    public CalendarForSingleClient(SortedSet<xNewPrintDay> myShifts, xNewPrintData.client client, String sdate, String edate) {
        initComponents();
        myDays = new ArrayList();
        ClientNameLabel.setText(client.clientName);
        AddressLineOneLabel.setText(client.clientAddress1);
        AddressLineTwoLabel.setText(client.clientCity + ", " + client.clientState + " " + client.clientZip);
        Calendar sCal = StaticDateTimeFunctions.setCalendarToString(sdate);
        Calendar eCal = StaticDateTimeFunctions.setCalendarToString(edate);
        int diffDays = StaticDateTimeFunctions.getDifferenceInDays(sCal, eCal);
        for (int i = 0; i < diffDays; i++) {
            VisualDay myDay = new VisualDay(sCal);
            myDays.add(myDay);
            sCal.add(Calendar.DAY_OF_MONTH, 1);
            DataPanel.add(myDay);
        }
        Iterator<xNewPrintDay> myIterator = myShifts.iterator();
        while (myIterator.hasNext()) {
            xNewPrintDay tempDay = myIterator.next();
            for (int d = 0; d < diffDays; d++) {
                myDays.get(d).insertDataIfCorrectDate(tempDay);
            }
        }
    }
    
    public int getNumDays() {
        return myDays.size();
    }
    
    public int getHeight() {
        return (new Double(Math.ceil(myDays.size() / 7.0)).intValue() * 60) + 35; 
    }
    
    public Dimension getPreferredSize() {
        return new Dimension(10000, getHeight());
    }
    
    public Dimension getMinimumSize() {
        return new Dimension(100, getHeight());
    }
    
    public Dimension getMaximumSize() {
        return new Dimension(10000, getHeight());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        HeaderPanel = new javax.swing.JPanel();
        ClientNamePanel = new javax.swing.JPanel();
        ClientNameLabel = new javax.swing.JLabel();
        ClientAddressPanel = new javax.swing.JPanel();
        ClientAddressLineOne = new javax.swing.JPanel();
        AddressLineOneLabel = new javax.swing.JLabel();
        ClientAddressLineTwo = new javax.swing.JPanel();
        AddressLineTwoLabel = new javax.swing.JLabel();
        DataPanel = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setDoubleBuffered(false);
        HeaderPanel.setLayout(new javax.swing.BoxLayout(HeaderPanel, javax.swing.BoxLayout.X_AXIS));

        HeaderPanel.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.MatteBorder(new java.awt.Insets(0, 0, 1, 0), new java.awt.Color(0, 0, 0)), new javax.swing.border.MatteBorder(new java.awt.Insets(0, 0, 1, 0), new java.awt.Color(0, 0, 0))));
        HeaderPanel.setDoubleBuffered(false);
        HeaderPanel.setMaximumSize(new java.awt.Dimension(32767, 35));
        HeaderPanel.setMinimumSize(new java.awt.Dimension(10, 35));
        HeaderPanel.setOpaque(false);
        HeaderPanel.setPreferredSize(new java.awt.Dimension(10, 35));
        ClientNamePanel.setLayout(new java.awt.GridLayout(1, 0));

        ClientNamePanel.setDoubleBuffered(false);
        ClientNamePanel.setOpaque(false);
        ClientNameLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20));
        ClientNameLabel.setText("Client Name Goes Here");
        ClientNamePanel.add(ClientNameLabel);

        HeaderPanel.add(ClientNamePanel);

        ClientAddressPanel.setLayout(new java.awt.GridLayout(2, 1));

        ClientAddressPanel.setDoubleBuffered(false);
        ClientAddressPanel.setMaximumSize(new java.awt.Dimension(140, 32767));
        ClientAddressPanel.setMinimumSize(new java.awt.Dimension(140, 22));
        ClientAddressPanel.setOpaque(false);
        ClientAddressPanel.setPreferredSize(new java.awt.Dimension(140, 22));
        ClientAddressLineOne.setLayout(new java.awt.GridLayout(1, 0));

        ClientAddressLineOne.setDoubleBuffered(false);
        ClientAddressLineOne.setOpaque(false);
        AddressLineOneLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 9));
        AddressLineOneLabel.setText("Client Address Line 1");
        ClientAddressLineOne.add(AddressLineOneLabel);

        ClientAddressPanel.add(ClientAddressLineOne);

        ClientAddressLineTwo.setLayout(new java.awt.GridLayout(1, 0));

        ClientAddressLineTwo.setDoubleBuffered(false);
        ClientAddressLineTwo.setOpaque(false);
        AddressLineTwoLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 9));
        AddressLineTwoLabel.setText("Client Address Line 2");
        ClientAddressLineTwo.add(AddressLineTwoLabel);

        ClientAddressPanel.add(ClientAddressLineTwo);

        HeaderPanel.add(ClientAddressPanel);

        add(HeaderPanel);

        DataPanel.setLayout(new java.awt.GridLayout(0, 7));

        DataPanel.setDoubleBuffered(false);
        DataPanel.setOpaque(false);
        add(DataPanel);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLineOneLabel;
    private javax.swing.JLabel AddressLineTwoLabel;
    private javax.swing.JPanel ClientAddressLineOne;
    private javax.swing.JPanel ClientAddressLineTwo;
    private javax.swing.JPanel ClientAddressPanel;
    private javax.swing.JLabel ClientNameLabel;
    private javax.swing.JPanel ClientNamePanel;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JPanel HeaderPanel;
    // End of variables declaration//GEN-END:variables
    
}
