/*
 * Employee_Termination_Confirmation.java
 *
 * Created on August 30, 2005, 9:31 AM
 */

package rmischedule.client.components;


import java.awt.*;
import java.util.ArrayList;
import java.util.Calendar;

import rmischeduleserver.control.ClientController;
import schedfoxlib.model.ClientTerminationReason;
import schedfoxlib.model.TerminationReason;

/**
 *
 * @author  jason.allen
 */
public class ClientTerminationConfirmation extends javax.swing.JDialog {
    private rmischedule.components.jcalendar.JCalendarPanel calTermDate;

    private Calendar terminationDate;
    private String companyId;
    private Integer clientId;
    
    /** Creates new form Employee_Termination_Confirmation */
    public ClientTerminationConfirmation(java.awt.Frame parent, boolean modal, String companyId, Integer clientId) {
        super(parent, modal);
        initComponents();
        this.companyId = companyId;
        this.clientId = clientId;
        ClientController clientController = ClientController.getInstance(companyId);
        try {
            ArrayList<TerminationReason> reasons = clientController.getTerminationReasons();
            for (int r = 0; r < reasons.size(); r++) {
                terminationReasonCmbo.addItem(reasons.get(r));
            }
        } catch (Exception exe) {}
        calTermDate = new rmischedule.components.jcalendar.JCalendarPanel();
        pnCal.add(calTermDate, BorderLayout.CENTER);
        calTermDate.setEnabled(true);
        setLocation((parent.getWidth()/2) - 100, (parent.getHeight()/2) - 100);
    }
    
    /**
     * Returns the selected Date.
     * @return
     */
    public Calendar getTerminationDate() {
        return this.terminationDate;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        terminationReasonCmbo = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        termNotesTxt = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnCal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pbOk = new javax.swing.JButton();
        pbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 1));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 24));
        jPanel5.setMinimumSize(new java.awt.Dimension(181, 24));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 24));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("Reason for Service Cancellation");
        jPanel5.add(jLabel2);

        jPanel3.add(jPanel5);

        terminationReasonCmbo.setMaximumSize(new java.awt.Dimension(32767, 28));
        terminationReasonCmbo.setMinimumSize(new java.awt.Dimension(64, 28));
        terminationReasonCmbo.setPreferredSize(new java.awt.Dimension(64, 28));
        jPanel3.add(terminationReasonCmbo);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 24));
        jPanel6.setMinimumSize(new java.awt.Dimension(235, 24));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 24));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Additional Information about Cancellation");
        jPanel6.add(jLabel3);

        jPanel3.add(jPanel6);
        jPanel3.add(termNotesTxt);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 1));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Service End Date");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4);

        pnCal.setMinimumSize(new java.awt.Dimension(200, 200));
        pnCal.setPreferredSize(new java.awt.Dimension(200, 200));
        pnCal.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnCal);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pbOk.setText("Ok");
        pbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbOkActionPerformed(evt);
            }
        });
        jPanel2.add(pbOk);

        pbCancel.setText("Cancel");
        pbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbCancelActionPerformed(evt);
            }
        });
        jPanel2.add(pbCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 498, 324);
    }// </editor-fold>//GEN-END:initComponents

    private void pbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbCancelActionPerformed
        dispose();
    }//GEN-LAST:event_pbCancelActionPerformed

    private void pbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbOkActionPerformed
        terminationDate = calTermDate.getCalendar();
        
        try {
            ClientController clientController = ClientController.getInstance(companyId);
            
            ClientTerminationReason clientTermReason = new ClientTerminationReason();
            clientTermReason.setClientId(this.clientId);
            clientTermReason.setNotes(termNotesTxt.getText().trim());
            clientTermReason.setTerminationReasonId(((TerminationReason)terminationReasonCmbo.getSelectedItem()).getTerminationReason());
            
            clientController.saveClientTerminationReason(clientTermReason);
        } catch (Exception exe) {}
        
        dispose();
    }//GEN-LAST:event_pbOkActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton pbCancel;
    private javax.swing.JButton pbOk;
    private javax.swing.JPanel pnCal;
    private java.awt.TextArea termNotesTxt;
    private javax.swing.JComboBox terminationReasonCmbo;
    // End of variables declaration//GEN-END:variables
    
}
