/*
 * Client_Worksite_Item.java
 *
 * Created on August 22, 2005, 8:01 AM
 */

package rmischedule.client.components;

import java.awt.event.*;
import java.awt.BorderLayout;

import javax.swing.*;
import javax.swing.event.*;

import rmischedule.components.Rate_Code_LB;
import rmischedule.components.graphicalcomponents.*;
import rmischeduleserver.mysqlconnectivity.queries.client.client_worksite_list_query;
import rmischeduleserver.mysqlconnectivity.queries.client.client_save_query;

/**
 *
 * @author  jason.allen
 */
public class Client_Worksite_Item extends JPanel {
    
    private int myOrder;
    private String myId;
    private String myName;
    private String myRateCode;
    
    
    protected boolean isBlank;
    
    private Client_Ids myParent;
    
    /** Creates new form Client_Worksite_Item */
    public Client_Worksite_Item(int order, Client_Ids parent) {
        super();        
        initComponents();
        
        myParent = parent;
        myId     = "0";
        myOrder = order;

        isBlank = true;
        pnName.add(efName,BorderLayout.CENTER);
        pbDelete.setText("Add");
        pnEdit.setVisible(false);
        efName.setText("");

        lblOrderNo.setText(String.valueOf(order) + ". ");
        setBackground(java.awt.Color.lightGray);         
    }
    
    /**
     *  Update information
     */
    public void update(int order, String id, String name, String rate_code){
        isBlank = false;
        myId        = id;
        myName      = name;
        myOrder     = order;
        myRateCode  = rate_code;
        //myRCLB.setRateCode(rate_code);
        pnName.remove(efName);
        pnName.add(lblName, BorderLayout.CENTER);
        lblName.setText(name);
        efName.setText(name);
        lblOrderNo.setText(String.valueOf(order) + ". ");
        pbDelete.setText("Delete");
   }
    
    /**
     * Save Work Site
     */
    public void wsAdd(){
        if(efName.getText().length() > 0){
            //myRateCode = myRCLB.getSelectedRateCodeId();
            myName     = efName.getText();
            myParent.addWorksite(myId, myName, myOrder, myRateCode, "0"); 
        }
    }
    
    /**
     * Delete Work Site
     */
    public void wsDelete(){
        //myRateCode = myRCLB.getSelectedRateCodeId();
        myName     = efName.getText();
        myParent.addWorksite(myId, myName, myOrder, myRateCode, "1");   
    }
    
    public void highlightMe(boolean highlightMe, Object myObj){
        if(highlightMe){
            setBackground(java.awt.Color.green);
        }else{
            setBackground(java.awt.Color.lightGray);            
        }
    }
     
    /**
     * Sets the order
     */
    public void setOrder(int o){
        myOrder = o;
        lblOrderNo.setText(String.valueOf(o) + ". ");
    }    
    
    /**
     * Adds a keylistener to our text box...
     */
    public void addKeyListener(KeyListener kl) {
        efName.addKeyListener(kl);
    }
    
    /**
     * Keys to text in our text box...
     */
    public String toString() {
        return efName.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblName = new javax.swing.JLabel();
        efName = new javax.swing.JTextField();
        pnVis = new javax.swing.JPanel();
        lblOrderNo = new javax.swing.JLabel();
        pnName = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnRateCode = new javax.swing.JPanel();
        pbDelete = new javax.swing.JButton();
        pnEdit = new javax.swing.JPanel();
        pbUpdate = new javax.swing.JButton();
        pbCancel = new javax.swing.JButton();

        lblName.setText("jLabel1");
        lblName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblNameMouseDragged(evt);
            }
        });
        lblName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblNameMouseReleased(evt);
            }
        });

        efName.setText("jTextField1");

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(12000, 30));
        pnVis.setLayout(new javax.swing.BoxLayout(pnVis, javax.swing.BoxLayout.X_AXIS));

        pnVis.setMaximumSize(new java.awt.Dimension(12000, 23));
        pnVis.setOpaque(false);
        lblOrderNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOrderNo.setText("1.");
        lblOrderNo.setMaximumSize(new java.awt.Dimension(20, 14));
        lblOrderNo.setMinimumSize(new java.awt.Dimension(20, 14));
        lblOrderNo.setPreferredSize(new java.awt.Dimension(20, 14));
        pnVis.add(lblOrderNo);

        pnName.setLayout(new java.awt.BorderLayout());

        pnName.setOpaque(false);
        pnName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnNameMousePressed(evt);
            }
        });

        pnVis.add(pnName);

        jPanel1.setOpaque(false);
        pnVis.add(jPanel1);

        pnRateCode.setLayout(new java.awt.BorderLayout());

        pnRateCode.setMaximumSize(new java.awt.Dimension(210, 2147483647));
        pnRateCode.setMinimumSize(new java.awt.Dimension(210, 0));
        pnRateCode.setOpaque(false);
        pnRateCode.setPreferredSize(new java.awt.Dimension(210, 0));
        pnVis.add(pnRateCode);

        pbDelete.setText("Delete");
        pbDelete.setMaximumSize(new java.awt.Dimension(80, 23));
        pbDelete.setMinimumSize(new java.awt.Dimension(80, 23));
        pbDelete.setPreferredSize(new java.awt.Dimension(80, 23));
        pbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbDeleteActionPerformed(evt);
            }
        });

        pnVis.add(pbDelete);

        add(pnVis);

        pnEdit.setOpaque(false);
        pbUpdate.setText("Update");
        pbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbUpdateActionPerformed(evt);
            }
        });

        pnEdit.add(pbUpdate);

        pbCancel.setText("Cancel");
        pbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbCancelActionPerformed(evt);
            }
        });

        pnEdit.add(pbCancel);

        add(pnEdit);

    }
    // </editor-fold>//GEN-END:initComponents

    private void lblNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseExited
       
    }//GEN-LAST:event_lblNameMouseExited

    private void lblNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseEntered
        
    }//GEN-LAST:event_lblNameMouseEntered

    private void lblNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseReleased
        
    }//GEN-LAST:event_lblNameMouseReleased

    private void lblNameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseDragged
        
    }//GEN-LAST:event_lblNameMouseDragged

    private void lblNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMousePressed
        
    }//GEN-LAST:event_lblNameMousePressed

    private void pnNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNameMousePressed
        
    }//GEN-LAST:event_pnNameMousePressed

    private void lblNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseClicked

    }//GEN-LAST:event_lblNameMouseClicked

    private void pbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbCancelActionPerformed
        pnName.remove(efName);
        efName.setText(myName);
        pnName.add(lblName, BorderLayout.CENTER);        
        pnEdit.setVisible(false);        
    }//GEN-LAST:event_pbCancelActionPerformed

    private void pbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbUpdateActionPerformed
        wsAdd();
    }//GEN-LAST:event_pbUpdateActionPerformed

    private void pbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbDeleteActionPerformed
        if(isBlank){
            wsAdd();
        }else{
            wsDelete();
        }
    }//GEN-LAST:event_pbDeleteActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField efName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderNo;
    private javax.swing.JButton pbCancel;
    private javax.swing.JButton pbDelete;
    private javax.swing.JButton pbUpdate;
    private javax.swing.JPanel pnEdit;
    private javax.swing.JPanel pnName;
    private javax.swing.JPanel pnRateCode;
    private javax.swing.JPanel pnVis;
    // End of variables declaration//GEN-END:variables
    public JTextField getEfName() {
    	return efName;
    }
}
