/*
 * Employee_Import.java
 *
 * Created on February 14, 2005, 7:54 AM
 */

package rmischedule.client.components;
import rmischedule.components.graphicalcomponents.*;
import rmischedule.data_connection.Connection;
import rmischedule.security.*;
import rmischedule.main.*;
import rmischeduleserver.control.ClientController;
import schedfoxlib.model.util.Record_Set;
import schedfoxlib.model.Client;
import schedfoxlib.model.ClientExport;
import rmischeduleserver.mysqlconnectivity.queries.client.*;
import rmischeduleserver.mysqlconnectivity.queries.util.GenericQuery;
/**
 *
 * @author  ira
 */
public class Client_Export extends GenericEditSubForm {

    private client_export_usked_update myUpdateQuery;
    
    
    /** Creates new form Employee_Import */
    public Client_Export() {
        initComponents();
        myUpdateQuery = new client_export_usked_update();
        
    }

    public void doOnClear() {
    }

    public javax.swing.JPanel getMyForm() {
        return this;
    }

    public java.lang.String getMyTabTitle() {
        return "Export";
    }

    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getSaveQuery(boolean isNewData) {
        Client myClient = (Client)myparent.getSelectedObject();
        
        try {
            if (myClient.getClientWorksite() > 0) {
                myUpdateQuery.update(UltraIDTextField.getText().trim(), myparent.getMyIdForSave(), UltraParentID.getText().trim());
            } else {
                String ultraId = UltraIDTextField.getText().trim();
                if (ultraId.length() == 0) {
                    ClientController myController = ClientController.getInstance(myparent.getConnection().myCompany);
                    ultraId = myController.generateNewUskedId(myClient);
                }
                myUpdateQuery.update(ultraId, myparent.getMyIdForSave());
            }
        } catch (Exception e) {
            return null;
        }
        return myUpdateQuery;
    }
    
    public void loadData(Record_Set rs) {
        try {
            Client myClient = (Client)myparent.getSelectedObject();
            ClientController clientController = ClientController.getInstance(myparent.getConnection().myCompany);
            ClientExport export = clientController.getClientExport(myClient.getClientId());
            
            UltraIDTextField.setText(export.getUskedWsId());
            UltraParentID.setText(export.getUskedCliId());
            if (UltraIDTextField.getText().trim().length() == 0) {
                UltraIDTextField.setText(UltraParentID.getText());
                UltraParentID.setText("");
            }
        } catch (Exception e) {
            System.out.println("Problem loading Usked Information in ID tab.");
            e.printStackTrace();
            UltraIDTextField.setText("");
            UltraParentID.setText("");
        }
    }
    
    public boolean needsMoreRecordSets() {
        return false;
    }
    
    public boolean userHasAccess() {
        return Main_Window.parentOfApplication.mySecurity.checkSecurity(security_detail.MODULES.CLIENT_EXPORT);
    }
    
    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getQuery(boolean isSelected) {
        return new GenericQuery("Select NOW();");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CCSImport = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UltraIDTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UltraParentID = new javax.swing.JTextField();
        SpacerPanel = new javax.swing.JPanel();
        ControlPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(186, 186, 222));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3), javax.swing.BorderFactory.createEtchedBorder()));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        CCSImport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ultra Sked", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        CCSImport.setMaximumSize(new java.awt.Dimension(1600, 120));
        CCSImport.setMinimumSize(new java.awt.Dimension(1600, 120));
        CCSImport.setPreferredSize(new java.awt.Dimension(16, 120));
        CCSImport.setLayout(new javax.swing.BoxLayout(CCSImport, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 70));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setMinimumSize(new java.awt.Dimension(126, 28));
        jPanel4.setPreferredSize(new java.awt.Dimension(220, 28));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Individual Account USKED");
        jLabel1.setMaximumSize(new java.awt.Dimension(220, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(220, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(220, 22));
        jPanel4.add(jLabel1);

        UltraIDTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        UltraIDTextField.setMinimumSize(new java.awt.Dimension(12, 26));
        UltraIDTextField.setPreferredSize(new java.awt.Dimension(12, 26));
        jPanel4.add(UltraIDTextField);

        jPanel1.add(jPanel4);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel2.setText("Joint Corporate Account");
        jLabel2.setMaximumSize(new java.awt.Dimension(220, 22));
        jLabel2.setMinimumSize(new java.awt.Dimension(220, 22));
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 22));
        jPanel3.add(jLabel2);

        UltraParentID.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        UltraParentID.setMinimumSize(new java.awt.Dimension(12, 26));
        UltraParentID.setPreferredSize(new java.awt.Dimension(12, 26));
        jPanel3.add(UltraParentID);

        jPanel1.add(jPanel3);

        CCSImport.add(jPanel1);

        add(CCSImport);
        add(SpacerPanel);

        ControlPanel.setMaximumSize(new java.awt.Dimension(32767, 40));
        ControlPanel.setMinimumSize(new java.awt.Dimension(10, 40));
        ControlPanel.setPreferredSize(new java.awt.Dimension(10, 40));
        ControlPanel.setLayout(new javax.swing.BoxLayout(ControlPanel, javax.swing.BoxLayout.LINE_AXIS));
        ControlPanel.add(jPanel2);

        add(ControlPanel);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CCSImport;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel SpacerPanel;
    private javax.swing.JTextField UltraIDTextField;
    private javax.swing.JTextField UltraParentID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    
}
