/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmischedule.client.components;

import java.awt.Color;
import rmischedule.utility.ParentTrickleListener;
import schedfoxlib.model.Client;

/**
 *
 * @author ira
 */
public class DisplayClientSearchInfoPanel extends javax.swing.JPanel {

    private Color highlightColor = new Color(18, 107, 13);

    /**
     * Creates new form DisplayClientSearchInfoPanel
     */
    public DisplayClientSearchInfoPanel(Client client, String searchText) {
        initComponents();

        this.addMouseListener(new ParentTrickleListener());
        for (int c = 0; c < this.getComponentCount(); c++) {
            this.getComponent(c).addMouseListener(new ParentTrickleListener());
        }
        
        clientNameLabel.setText(client.getClientName());
        if (client.getClientName().toUpperCase().contains(searchText.toUpperCase())) {
            clientNameLabel.setForeground(highlightColor);
        }

        addressLabel.setText(client.getAddress1() + " " + client.getAddress2());
        if ((client.getAddress1() + " " + client.getAddress2()).toUpperCase().contains(searchText.toUpperCase())) {
            addressLabel.setForeground(highlightColor);
        }

        addressLabel2.setText(client.getCity() + ", " + client.getState() + " " + client.getZip());
        if ((client.getCity() + ", " + client.getState() + " " + client.getZip()).toUpperCase().contains(searchText.toUpperCase())) {
            addressLabel2.setForeground(highlightColor);
        }

        phoneTxt.setText(client.getClientPhone());
        if (client.getClientPhone().toUpperCase().contains(searchText.toUpperCase())) {
            phoneTxt.setForeground(highlightColor);
        }

        phone2Txt.setText(client.getClientPhone2());
        if (client.getClientPhone2().toUpperCase().contains(searchText.toUpperCase())) {
            phone2Txt.setForeground(highlightColor);
        }

        faxTxt.setText(client.getClientFax());
        if (client.getClientFax().toUpperCase().contains(searchText.toUpperCase())) {
            faxTxt.setForeground(highlightColor);
        }

        for (int c = 0; c < client.getContactsWOFetch().size(); c++) {
            this.add(new DisplayClientContactInfoPanel(client.getContactsWOFetch().get(c), searchText));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        clientNameLabel = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JLabel();
        phone2Txt = new javax.swing.JLabel();
        faxTxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setPreferredSize(new java.awt.Dimension(400, 32));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 16));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        clientNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientNameLabel.setText("jLabel1");
        clientNameLabel.setMaximumSize(new java.awt.Dimension(410, 16));
        clientNameLabel.setMinimumSize(new java.awt.Dimension(410, 16));
        clientNameLabel.setPreferredSize(new java.awt.Dimension(410, 16));
        jPanel2.add(clientNameLabel);

        phoneTxt.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        phoneTxt.setText("jLabel1");
        phoneTxt.setMaximumSize(new java.awt.Dimension(200, 16));
        phoneTxt.setMinimumSize(new java.awt.Dimension(100, 16));
        phoneTxt.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel2.add(phoneTxt);

        phone2Txt.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        phone2Txt.setText("jLabel2");
        phone2Txt.setMaximumSize(new java.awt.Dimension(200, 16));
        phone2Txt.setMinimumSize(new java.awt.Dimension(100, 16));
        phone2Txt.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel2.add(phone2Txt);

        faxTxt.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        faxTxt.setText("jLabel2");
        faxTxt.setMaximumSize(new java.awt.Dimension(200, 16));
        faxTxt.setMinimumSize(new java.awt.Dimension(100, 16));
        faxTxt.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel2.add(faxTxt);

        add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        addressLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        addressLabel.setText("jLabel2");
        addressLabel.setMaximumSize(new java.awt.Dimension(410, 16));
        addressLabel.setMinimumSize(new java.awt.Dimension(410, 16));
        addressLabel.setPreferredSize(new java.awt.Dimension(410, 16));
        jPanel1.add(addressLabel);

        addressLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        addressLabel2.setText("jLabel2");
        addressLabel2.setMaximumSize(new java.awt.Dimension(2400, 16));
        addressLabel2.setMinimumSize(new java.awt.Dimension(210, 16));
        addressLabel2.setPreferredSize(new java.awt.Dimension(210, 16));
        jPanel1.add(addressLabel2);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JLabel faxTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel phone2Txt;
    private javax.swing.JLabel phoneTxt;
    // End of variables declaration//GEN-END:variables
}
