/*
 * EditContactDialog.java
 *
 * Created on August 4, 2006, 10:30 AM
 */

package rmischedule.client.components;

import javax.swing.*;
import java.text.*;
import java.util.ArrayList;
import javax.swing.event.ListDataListener;
import rmischedule.components.graphicalcomponents.GenericEditForm;
import rmischedule.data_connection.Connection;
import rmischedule.utility.TextField;
import schedfoxlib.model.util.Record_Set;
import schedfoxlib.model.ClientContact;
import schedfoxlib.model.ClientContactType;
import rmischeduleserver.mysqlconnectivity.queries.util.get_all_client_contact_types_query;

/**
 *
 * @author  shawn
 */
public class EditContactDialog extends javax.swing.JDialog {
    
    private ClientContact savedContact;
    private Integer idForSave;
    private int clientId;
    private GenericEditForm myparent;
    private ArrayList<ClientContactType> contactTypes = new ArrayList<ClientContactType>();
    
    /** Creates new form EditContactDialog */
    public EditContactDialog(java.awt.Frame parent, boolean modal, GenericEditForm myparent) {
        super(parent, modal);
        initComponents();

        this.myparent = myparent;
        try {
            this.clientId = Integer.parseInt(myparent.getMyIdForSave());
        } catch (Exception e) {
            this.clientId = 0;
        }
        this.savedContact = null;
        this.idForSave = 0;
        this.setTitle("Add a new Client Contact");
        
        this.loadClientContactTypes();

    }
    
    public EditContactDialog(java.awt.Frame parent, boolean modal, ClientContact contact, GenericEditForm myparent) {
        this(parent, modal, myparent);

        this.fnameTextField.setText(contact.getClientContactFirstName().trim());
        this.mnameTextField.setText(contact.getClientContactMiddleName().trim());
        this.lnameTextField.setText(contact.getClientContactLastName().trim());
        this.titleTextField.setText(contact.getClientContactTitle().trim());
        this.primaryCheckBox.setSelected(contact.getClientContactIsPrimary() == 1);
        this.addressTextField.setText(contact.getClientContactAddress().trim());
        this.address2TextField.setText(contact.getClientContactAddress2().trim());
        this.cityTextField.setText(contact.getClientContactCity().trim());
        this.stateTextField.setText(contact.getClientContactState().trim());
        this.zipFormattedTextField.setValue(contact.getClientContactZip().trim());
        this.phoneTextField.setText(contact.getClientContactPhone().trim());
        this.cellTextField.setText(contact.getClientContactCell().trim());
        this.faxTextField.setText(contact.getClientContactFax().trim());
        this.emailTextField.setText(contact.getClientContactEmail().trim());
        this.pagerTextField.setText(contact.getClientContactPager());
        this.massEmailChk.setSelected(contact.getClientContactIncludeMassEmail());
        
        this.idForSave = contact.getClientContactId();

        try {
            contactTypeCombo.getModel().setSelectedItem(contact.getClientContactType());
        } catch (Exception e) {}
        this.savedContact = contact;
        this.setTitle("Edit a Client Contact");
    }

    private void loadClientContactTypes() {
        get_all_client_contact_types_query contactTypeQuery = new get_all_client_contact_types_query();
        Connection myConn = myparent.getConnection();
        myConn.prepQuery(contactTypeQuery);
        contactTypeQuery.setPreparedStatement(new Object[]{});
        Record_Set rst = myConn.executeQuery(contactTypeQuery);

        contactTypes.clear();
        for (int r = 0; r < rst.length(); r++) {
            contactTypes.add(new ClientContactType(rst));
            rst.moveNext();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        generalPanel = new javax.swing.JPanel();
        namePanel = new javax.swing.JPanel();
        fnameLabel = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        mnameLabel = new javax.swing.JLabel();
        mnameTextField = new javax.swing.JTextField();
        lnameLabel = new javax.swing.JLabel();
        lnameTextField = new javax.swing.JTextField();
        miscPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        contactTypeCombo = new javax.swing.JComboBox();
        primaryCheckBox = new javax.swing.JCheckBox();
        contactPanel = new javax.swing.JPanel();
        addressLabelPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        address2Label = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressTextFieldPanel = new javax.swing.JPanel();
        addressTextField = new javax.swing.JTextField();
        address2TextField = new javax.swing.JTextField();
        cityStateZipPanel = new javax.swing.JPanel();
        cityTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateTextField = TextField.getStateTextField();
        zipLabel = new javax.swing.JLabel();
        zipFormattedTextField = TextField.getZipTextField();
        jPanel1 = new javax.swing.JPanel();
        emailTextField = new javax.swing.JTextField();
        massEmailChk = new javax.swing.JCheckBox();
        spacerPanel = new javax.swing.JPanel();
        contactLabelPanel = new javax.swing.JPanel();
        phoneLabel = new javax.swing.JLabel();
        cellLabel = new javax.swing.JLabel();
        faxLabel = new javax.swing.JLabel();
        pagerLabel = new javax.swing.JLabel();
        contactTextFieldPanel = new javax.swing.JPanel();
        phoneTextField = TextField.getPhoneTextField();
        cellTextField = TextField.getPhoneTextField();
        faxTextField = TextField.getPhoneTextField();
        pagerTextField = TextField.getPhoneTextField();
        controlPanel = new javax.swing.JPanel();
        spacerPanel2 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        infoPanel.setLayout(new javax.swing.BoxLayout(infoPanel, javax.swing.BoxLayout.Y_AXIS));

        generalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General Information"));
        generalPanel.setMaximumSize(new java.awt.Dimension(1000, 125));
        generalPanel.setMinimumSize(new java.awt.Dimension(100, 95));
        generalPanel.setPreferredSize(new java.awt.Dimension(100, 95));
        generalPanel.setLayout(new javax.swing.BoxLayout(generalPanel, javax.swing.BoxLayout.Y_AXIS));

        namePanel.setMaximumSize(new java.awt.Dimension(2216, 100));
        namePanel.setMinimumSize(new java.awt.Dimension(380, 30));
        namePanel.setPreferredSize(new java.awt.Dimension(238, 100));
        namePanel.setLayout(new javax.swing.BoxLayout(namePanel, javax.swing.BoxLayout.LINE_AXIS));

        fnameLabel.setText("First Name:");
        fnameLabel.setMaximumSize(new java.awt.Dimension(64, 14));
        fnameLabel.setMinimumSize(new java.awt.Dimension(64, 14));
        fnameLabel.setPreferredSize(new java.awt.Dimension(64, 14));
        namePanel.add(fnameLabel);

        fnameTextField.setMaximumSize(new java.awt.Dimension(125, 28));
        fnameTextField.setMinimumSize(new java.awt.Dimension(125, 24));
        fnameTextField.setPreferredSize(new java.awt.Dimension(125, 24));
        namePanel.add(fnameTextField);

        mnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnameLabel.setText("Middle Initial:");
        mnameLabel.setMaximumSize(new java.awt.Dimension(73, 14));
        mnameLabel.setMinimumSize(new java.awt.Dimension(73, 14));
        mnameLabel.setPreferredSize(new java.awt.Dimension(73, 14));
        namePanel.add(mnameLabel);

        mnameTextField.setMaximumSize(new java.awt.Dimension(24, 28));
        mnameTextField.setMinimumSize(new java.awt.Dimension(24, 24));
        mnameTextField.setPreferredSize(new java.awt.Dimension(24, 24));
        mnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnameTextFieldKeyTyped(evt);
            }
        });
        namePanel.add(mnameTextField);

        lnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnameLabel.setText("Last Name:");
        lnameLabel.setMaximumSize(new java.awt.Dimension(64, 14));
        lnameLabel.setMinimumSize(new java.awt.Dimension(64, 14));
        lnameLabel.setPreferredSize(new java.awt.Dimension(64, 14));
        namePanel.add(lnameLabel);

        lnameTextField.setMaximumSize(new java.awt.Dimension(1000, 28));
        lnameTextField.setMinimumSize(new java.awt.Dimension(64, 24));
        lnameTextField.setPreferredSize(new java.awt.Dimension(12, 24));
        namePanel.add(lnameTextField);

        generalPanel.add(namePanel);

        miscPanel.setMaximumSize(new java.awt.Dimension(2215, 100));
        miscPanel.setMinimumSize(new java.awt.Dimension(270, 30));
        miscPanel.setPreferredSize(new java.awt.Dimension(270, 100));
        miscPanel.setLayout(new javax.swing.BoxLayout(miscPanel, javax.swing.BoxLayout.LINE_AXIS));

        titleLabel.setText("Title:");
        titleLabel.setMaximumSize(new java.awt.Dimension(64, 14));
        titleLabel.setMinimumSize(new java.awt.Dimension(64, 14));
        titleLabel.setPreferredSize(new java.awt.Dimension(64, 14));
        miscPanel.add(titleLabel);

        titleTextField.setMaximumSize(new java.awt.Dimension(125, 28));
        titleTextField.setMinimumSize(new java.awt.Dimension(125, 24));
        titleTextField.setPreferredSize(new java.awt.Dimension(125, 24));
        miscPanel.add(titleTextField);

        jLabel1.setText("Contact Type");
        miscPanel.add(jLabel1);

        contactTypeCombo.setModel(new ClientContactModel());
        contactTypeCombo.setMaximumSize(new java.awt.Dimension(120, 28));
        contactTypeCombo.setMinimumSize(new java.awt.Dimension(120, 26));
        contactTypeCombo.setPreferredSize(new java.awt.Dimension(120, 26));
        miscPanel.add(contactTypeCombo);

        primaryCheckBox.setText("Primary Contact");
        primaryCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        primaryCheckBox.setFocusable(false);
        primaryCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        primaryCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        primaryCheckBox.setMaximumSize(new java.awt.Dimension(300, 15));
        primaryCheckBox.setMinimumSize(new java.awt.Dimension(10, 15));
        primaryCheckBox.setPreferredSize(new java.awt.Dimension(10, 15));
        miscPanel.add(primaryCheckBox);

        generalPanel.add(miscPanel);

        infoPanel.add(generalPanel);

        contactPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Information"));
        contactPanel.setMaximumSize(new java.awt.Dimension(1000, 200));
        contactPanel.setMinimumSize(new java.awt.Dimension(100, 95));
        contactPanel.setLayout(new javax.swing.BoxLayout(contactPanel, javax.swing.BoxLayout.LINE_AXIS));

        addressLabelPanel.setMaximumSize(new java.awt.Dimension(60, 150));
        addressLabelPanel.setMinimumSize(new java.awt.Dimension(60, 95));
        addressLabelPanel.setPreferredSize(new java.awt.Dimension(60, 95));
        addressLabelPanel.setLayout(new javax.swing.BoxLayout(addressLabelPanel, javax.swing.BoxLayout.Y_AXIS));

        addressLabel.setText("Address:");
        addressLabel.setMaximumSize(new java.awt.Dimension(60, 28));
        addressLabel.setMinimumSize(new java.awt.Dimension(60, 24));
        addressLabel.setPreferredSize(new java.awt.Dimension(60, 24));
        addressLabelPanel.add(addressLabel);

        address2Label.setText("Address2:");
        address2Label.setMaximumSize(new java.awt.Dimension(60, 28));
        address2Label.setMinimumSize(new java.awt.Dimension(60, 24));
        address2Label.setPreferredSize(new java.awt.Dimension(60, 24));
        addressLabelPanel.add(address2Label);

        cityLabel.setText("City:");
        cityLabel.setMaximumSize(new java.awt.Dimension(60, 28));
        cityLabel.setMinimumSize(new java.awt.Dimension(60, 24));
        cityLabel.setPreferredSize(new java.awt.Dimension(60, 24));
        addressLabelPanel.add(cityLabel);

        emailLabel.setText("E-Mail:");
        emailLabel.setMaximumSize(new java.awt.Dimension(60, 28));
        emailLabel.setMinimumSize(new java.awt.Dimension(60, 24));
        emailLabel.setPreferredSize(new java.awt.Dimension(60, 24));
        addressLabelPanel.add(emailLabel);

        contactPanel.add(addressLabelPanel);

        addressTextFieldPanel.setMaximumSize(new java.awt.Dimension(32767, 150));
        addressTextFieldPanel.setPreferredSize(new java.awt.Dimension(175, 95));
        addressTextFieldPanel.setLayout(new javax.swing.BoxLayout(addressTextFieldPanel, javax.swing.BoxLayout.Y_AXIS));

        addressTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        addressTextField.setMinimumSize(new java.awt.Dimension(12, 24));
        addressTextField.setPreferredSize(new java.awt.Dimension(12, 24));
        addressTextFieldPanel.add(addressTextField);

        address2TextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        address2TextField.setMinimumSize(new java.awt.Dimension(12, 24));
        address2TextField.setPreferredSize(new java.awt.Dimension(12, 24));
        addressTextFieldPanel.add(address2TextField);

        cityStateZipPanel.setLayout(new javax.swing.BoxLayout(cityStateZipPanel, javax.swing.BoxLayout.LINE_AXIS));

        cityTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        cityTextField.setMinimumSize(new java.awt.Dimension(12, 24));
        cityTextField.setPreferredSize(new java.awt.Dimension(12, 24));
        cityStateZipPanel.add(cityTextField);

        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stateLabel.setText("State:");
        stateLabel.setMaximumSize(new java.awt.Dimension(35, 19));
        stateLabel.setMinimumSize(new java.awt.Dimension(35, 19));
        stateLabel.setPreferredSize(new java.awt.Dimension(35, 19));
        cityStateZipPanel.add(stateLabel);

        stateTextField.setMaximumSize(new java.awt.Dimension(36, 28));
        stateTextField.setMinimumSize(new java.awt.Dimension(36, 24));
        stateTextField.setPreferredSize(new java.awt.Dimension(36, 24));
        stateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stateTextFieldKeyTyped(evt);
            }
        });
        cityStateZipPanel.add(stateTextField);

        zipLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zipLabel.setText("Zip:");
        zipLabel.setMaximumSize(new java.awt.Dimension(23, 19));
        zipLabel.setMinimumSize(new java.awt.Dimension(23, 19));
        zipLabel.setPreferredSize(new java.awt.Dimension(23, 19));
        cityStateZipPanel.add(zipLabel);

        zipFormattedTextField.setMaximumSize(new java.awt.Dimension(50, 28));
        zipFormattedTextField.setMinimumSize(new java.awt.Dimension(50, 24));
        zipFormattedTextField.setPreferredSize(new java.awt.Dimension(50, 24));
        cityStateZipPanel.add(zipFormattedTextField);

        addressTextFieldPanel.add(cityStateZipPanel);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        emailTextField.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        emailTextField.setMinimumSize(new java.awt.Dimension(12, 24));
        emailTextField.setPreferredSize(new java.awt.Dimension(12, 24));
        jPanel1.add(emailTextField);

        massEmailChk.setText("Mass Email?");
        jPanel1.add(massEmailChk);

        addressTextFieldPanel.add(jPanel1);

        contactPanel.add(addressTextFieldPanel);

        spacerPanel.setMaximumSize(new java.awt.Dimension(10, 32767));
        contactPanel.add(spacerPanel);

        contactLabelPanel.setMaximumSize(new java.awt.Dimension(45, 150));
        contactLabelPanel.setMinimumSize(new java.awt.Dimension(45, 95));
        contactLabelPanel.setPreferredSize(new java.awt.Dimension(45, 95));
        contactLabelPanel.setLayout(new javax.swing.BoxLayout(contactLabelPanel, javax.swing.BoxLayout.Y_AXIS));

        phoneLabel.setText("Phone:");
        phoneLabel.setMaximumSize(new java.awt.Dimension(50, 28));
        phoneLabel.setMinimumSize(new java.awt.Dimension(45, 24));
        phoneLabel.setPreferredSize(new java.awt.Dimension(45, 24));
        contactLabelPanel.add(phoneLabel);

        cellLabel.setText("Cell:");
        cellLabel.setMaximumSize(new java.awt.Dimension(50, 28));
        cellLabel.setMinimumSize(new java.awt.Dimension(45, 24));
        cellLabel.setPreferredSize(new java.awt.Dimension(45, 24));
        contactLabelPanel.add(cellLabel);

        faxLabel.setText("Fax:");
        faxLabel.setMaximumSize(new java.awt.Dimension(50, 28));
        faxLabel.setMinimumSize(new java.awt.Dimension(45, 24));
        faxLabel.setPreferredSize(new java.awt.Dimension(45, 24));
        contactLabelPanel.add(faxLabel);

        pagerLabel.setText("Phone2");
        pagerLabel.setMaximumSize(new java.awt.Dimension(50, 28));
        pagerLabel.setMinimumSize(new java.awt.Dimension(45, 24));
        pagerLabel.setPreferredSize(new java.awt.Dimension(45, 24));
        contactLabelPanel.add(pagerLabel);

        contactPanel.add(contactLabelPanel);

        contactTextFieldPanel.setMaximumSize(new java.awt.Dimension(100, 150));
        contactTextFieldPanel.setPreferredSize(new java.awt.Dimension(100, 95));
        contactTextFieldPanel.setLayout(new javax.swing.BoxLayout(contactTextFieldPanel, javax.swing.BoxLayout.Y_AXIS));

        phoneTextField.setMaximumSize(new java.awt.Dimension(100, 28));
        phoneTextField.setMinimumSize(new java.awt.Dimension(100, 24));
        phoneTextField.setPreferredSize(new java.awt.Dimension(100, 24));
        contactTextFieldPanel.add(phoneTextField);

        cellTextField.setMaximumSize(new java.awt.Dimension(100, 28));
        cellTextField.setMinimumSize(new java.awt.Dimension(100, 24));
        cellTextField.setPreferredSize(new java.awt.Dimension(100, 24));
        contactTextFieldPanel.add(cellTextField);

        faxTextField.setMaximumSize(new java.awt.Dimension(100, 28));
        faxTextField.setMinimumSize(new java.awt.Dimension(100, 24));
        faxTextField.setPreferredSize(new java.awt.Dimension(100, 24));
        faxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxTextFieldActionPerformed(evt);
            }
        });
        contactTextFieldPanel.add(faxTextField);

        pagerTextField.setMaximumSize(new java.awt.Dimension(100, 28));
        pagerTextField.setMinimumSize(new java.awt.Dimension(100, 24));
        pagerTextField.setPreferredSize(new java.awt.Dimension(100, 24));
        pagerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagerTextFieldActionPerformed(evt);
            }
        });
        contactTextFieldPanel.add(pagerTextField);

        contactPanel.add(contactTextFieldPanel);

        infoPanel.add(contactPanel);

        getContentPane().add(infoPanel, java.awt.BorderLayout.CENTER);

        controlPanel.setMaximumSize(new java.awt.Dimension(0, 23));
        controlPanel.setMinimumSize(new java.awt.Dimension(0, 23));
        controlPanel.setPreferredSize(new java.awt.Dimension(100, 23));
        controlPanel.setLayout(new javax.swing.BoxLayout(controlPanel, javax.swing.BoxLayout.LINE_AXIS));
        controlPanel.add(spacerPanel2);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        controlPanel.add(cancelButton);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        controlPanel.add(saveButton);

        getContentPane().add(controlPanel, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-558)/2, (screenSize.height-329)/2, 558, 329);
    }// </editor-fold>//GEN-END:initComponents


    private void mnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameTextFieldKeyTyped
        if(this.mnameTextField.getText().length() == 1) {
            evt.consume();
        }
    }//GEN-LAST:event_mnameTextFieldKeyTyped

    private void stateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateTextFieldKeyTyped
//        if(this.stateTextField.getText().length() == 2) {
//            evt.consume();
//        }
    }//GEN-LAST:event_stateTextFieldKeyTyped
    

    public ClientContact getSavedContact() {
        return this.savedContact;
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.savedContact = null;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(this.fnameTextField.getText().trim().length() == 0 ||
           this.lnameTextField.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "You must enter a first and last name", "Unable to save contact!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (this.savedContact == null) {
            this.savedContact = new ClientContact();
        }

        savedContact.setClientId(this.clientId);
        savedContact.setClientContactFirstName(fnameTextField.getText());
        savedContact.setClientContactMiddleName(mnameTextField.getText());
        savedContact.setClientContactLastName(lnameTextField.getText());
        savedContact.setClientContactTitle(titleTextField.getText());
        savedContact.setClientContactIsPrimary(primaryCheckBox.isSelected() ? 1 : 0);
        savedContact.setClientContactAddress(addressTextField.getText());
        savedContact.setClientContactAddress2(address2TextField.getText());
        savedContact.setClientContactCity(cityTextField.getText());
        savedContact.setClientContactState(stateTextField.getText());
        savedContact.setClientContactPager(pagerTextField.getText());
        savedContact.setClientContactIncludeMassEmail(massEmailChk.isSelected());
        try {
            this.zipFormattedTextField.commitEdit();
            savedContact.setClientContactZip(zipFormattedTextField.getValue().toString());
        }
        catch(ParseException ex) { 
            this.savedContact.setClientContactZip("");
        }

        try {
            this.savedContact.setClientContactType(((ClientContactType)contactTypeCombo.getSelectedItem()).getClientContactType());
        } catch (Exception e) {

        }
        savedContact.setClientContactPhone(phoneTextField.getText());
        savedContact.setClientContactCell(cellTextField.getText());
        savedContact.setClientContactFax(faxTextField.getText());
        savedContact.setClientContactEmail(emailTextField.getText());
        savedContact.setClientContactId(idForSave);
        
        this.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void faxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxTextFieldActionPerformed

    private void pagerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagerTextFieldActionPerformed

    private class ClientContactModel implements ComboBoxModel {
        private int selectedIndex = -1;

        public ClientContactModel() {

        }

        public void setSelectedItem(Object anItem) {
            for (int c = 0; c < contactTypes.size(); c++) {
                if (contactTypes.get(c).getClientContactType().equals(anItem) ||
                        contactTypes.get(c).getContactType().equals(anItem)) {
                    this.selectedIndex = c;
                }
            }
        }

        public Object getSelectedItem() {
            if (selectedIndex >= 0) {
                return contactTypes.get(selectedIndex);
            } else {
                return "Please Select";
            }
        }

        public int getSize() {
            return contactTypes.size();
        }

        public Object getElementAt(int index) {
            if (index >= 0) {
                return contactTypes.get(index).getContactType();
            } else {
                return "None Selected";
            }
        }

        public void addListDataListener(ListDataListener l) {
            
        }

        public void removeListDataListener(ListDataListener l) {
            
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address2Label;
    private javax.swing.JTextField address2TextField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel addressLabelPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JPanel addressTextFieldPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel cellLabel;
    private javax.swing.JTextField cellTextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JPanel cityStateZipPanel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JPanel contactLabelPanel;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JPanel contactTextFieldPanel;
    private javax.swing.JComboBox contactTypeCombo;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JTextField faxTextField;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JCheckBox massEmailChk;
    private javax.swing.JPanel miscPanel;
    private javax.swing.JLabel mnameLabel;
    private javax.swing.JTextField mnameTextField;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel pagerLabel;
    private javax.swing.JTextField pagerTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JCheckBox primaryCheckBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel spacerPanel;
    private javax.swing.JPanel spacerPanel2;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JFormattedTextField zipFormattedTextField;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
    
}
