/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rmischedule.problemsolver;

import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import rmischedule.client.components.ProblemSolverEditPanel;
import rmischeduleserver.control.ClientController;
import rmischeduleserver.control.UserController;
import schedfoxlib.model.Client;
import schedfoxlib.model.Problemsolver;
import schedfoxlib.model.ProblemsolverTemplate;
import schedfoxlib.model.User;

/**
 *
 * @author ira
 */
public class ProblemSolverDisplay extends javax.swing.JPanel {

    private Problemsolver ps;
    private Integer companyId;
    
    /**
     * Creates new form ProblemSolverDisplay
     */
    public ProblemSolverDisplay(Problemsolver ps, Integer companyId) {
        initComponents();
        this.ps = ps;
        this.companyId = companyId;
        
        this.reload();
    }
    
    public void addBtnActionListener(ActionListener listener) {
        closeBtn.addActionListener(listener);
    }

    protected void reload() {
        try {
            UserController userController = new UserController(companyId + "");
            User myUser = userController.getUserById(ps.getUserId());
            
            ClientController clientController = ClientController.getInstance(companyId + "");
            Client myClient = clientController.getClientById(ps.getClientId());

            clientDataLabel.setText(myClient.getClientName());
            dateDataLabel.setText(new SimpleDateFormat("MM/dd/yyyy").format(ps.getPsDate()));
            userDataLabel.setText(myUser.getUserFullName());
            phoneDataLabel.setText(myClient.getClientPhone());
            cellDataLabel.setText(myClient.getClientPhone2());
            faxDataLabel.setText(myClient.getClientFax());
        } catch (Exception exe) {}
        ArrayList<ProblemsolverTemplate> temp = new ArrayList<ProblemsolverTemplate>();
        
        this.problemSolverPanel.removeAll();
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Communication:", ps.getProblem(), 1, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Solution:", ps.getSolution(), 2, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Scheduler Instructions:", ps.getSchedulerInst(), 3, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Supervisor Instructions:", ps.getSupervisorInst(), 4, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("District Manager Instructions:", ps.getDmInst(), 5, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Personnel Instructions:", ps.getHrInst(), 6, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Post Commander Instructions:", ps.getPostcomInst(), 7, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Security Officers Instructions:", ps.getOfficerInst(), 8, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Payroll Instructions:", ps.getPayrollInst(), 9, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Night Managers and Dispatch Instructions:", ps.getDispatchInst(), 10, temp, companyId, null, null));
        this.problemSolverPanel.add(new ProblemSolverEditPanel("Secretary and Check-In Instructions:", ps.getCheckinInst(), 11, temp, companyId, null, null));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        infoPanel1 = new javax.swing.JPanel();
        labelPanel1 = new javax.swing.JPanel();
        clientLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        dataPanel1 = new javax.swing.JPanel();
        clientDataLabel = new javax.swing.JLabel();
        dateDataLabel = new javax.swing.JLabel();
        userDataLabel = new javax.swing.JLabel();
        infoPanel2 = new javax.swing.JPanel();
        labelPanel2 = new javax.swing.JPanel();
        phoneLabel = new javax.swing.JLabel();
        cellLabel = new javax.swing.JLabel();
        faxLabel = new javax.swing.JLabel();
        dataPanel2 = new javax.swing.JPanel();
        phoneDataLabel = new javax.swing.JLabel();
        cellDataLabel = new javax.swing.JLabel();
        faxDataLabel = new javax.swing.JLabel();
        corpTypesPanel = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        problemSolverPanel = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        headerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Corporate Communicator Information"));
        headerPanel.setMaximumSize(new java.awt.Dimension(32767, 150));
        headerPanel.setLayout(new java.awt.GridLayout(1, 0));

        infoPanel1.setLayout(new javax.swing.BoxLayout(infoPanel1, javax.swing.BoxLayout.LINE_AXIS));

        labelPanel1.setMinimumSize(new java.awt.Dimension(80, 10));
        labelPanel1.setPreferredSize(new java.awt.Dimension(80, 48));
        labelPanel1.setLayout(new javax.swing.BoxLayout(labelPanel1, javax.swing.BoxLayout.Y_AXIS));

        clientLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clientLabel.setText("Client Name:");
        clientLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        clientLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        labelPanel1.add(clientLabel);

        dateLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dateLabel.setText("Date:");
        dateLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        dateLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        labelPanel1.add(dateLabel);

        userLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        userLabel.setText("Originator:");
        userLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        userLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        labelPanel1.add(userLabel);

        infoPanel1.add(labelPanel1);

        dataPanel1.setLayout(new javax.swing.BoxLayout(dataPanel1, javax.swing.BoxLayout.Y_AXIS));

        clientDataLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        clientDataLabel.setText("CLIENT NAME HERE");
        clientDataLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        clientDataLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        dataPanel1.add(clientDataLabel);

        dateDataLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dateDataLabel.setText("DATE HERE");
        dateDataLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        dateDataLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        dataPanel1.add(dateDataLabel);

        userDataLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userDataLabel.setText("ORIGINATOR HERE");
        userDataLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        userDataLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        dataPanel1.add(userDataLabel);

        infoPanel1.add(dataPanel1);

        headerPanel.add(infoPanel1);

        infoPanel2.setLayout(new javax.swing.BoxLayout(infoPanel2, javax.swing.BoxLayout.LINE_AXIS));

        labelPanel2.setMinimumSize(new java.awt.Dimension(80, 48));
        labelPanel2.setPreferredSize(new java.awt.Dimension(80, 48));
        labelPanel2.setLayout(new javax.swing.BoxLayout(labelPanel2, javax.swing.BoxLayout.Y_AXIS));

        phoneLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        phoneLabel.setText("Client Phone:");
        phoneLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        phoneLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        labelPanel2.add(phoneLabel);

        cellLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cellLabel.setText("Client Cell:");
        cellLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        cellLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        labelPanel2.add(cellLabel);

        faxLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        faxLabel.setText("Client Fax:");
        faxLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        faxLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        labelPanel2.add(faxLabel);

        infoPanel2.add(labelPanel2);

        dataPanel2.setLayout(new javax.swing.BoxLayout(dataPanel2, javax.swing.BoxLayout.Y_AXIS));

        phoneDataLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        phoneDataLabel.setText("CLIENT PHONE HERE");
        phoneDataLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        phoneDataLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        dataPanel2.add(phoneDataLabel);

        cellDataLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cellDataLabel.setText("CLIENT CELL HERE");
        cellDataLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        cellDataLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        dataPanel2.add(cellDataLabel);

        faxDataLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        faxDataLabel.setText("CLIENT FAX HERE");
        faxDataLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        faxDataLabel.setPreferredSize(new java.awt.Dimension(32767, 16));
        dataPanel2.add(faxDataLabel);

        infoPanel2.add(dataPanel2);

        headerPanel.add(infoPanel2);

        corpTypesPanel.setLayout(new java.awt.GridLayout(2, 2));

        closeBtn.setText("Close");
        corpTypesPanel.add(closeBtn);

        headerPanel.add(corpTypesPanel);

        add(headerPanel);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        problemSolverPanel.setLayout(new javax.swing.BoxLayout(problemSolverPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(problemSolverPanel);

        jPanel1.add(jScrollPane1);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cellDataLabel;
    private javax.swing.JLabel cellLabel;
    private javax.swing.JLabel clientDataLabel;
    private javax.swing.JLabel clientLabel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JPanel corpTypesPanel;
    private javax.swing.JPanel dataPanel1;
    private javax.swing.JPanel dataPanel2;
    private javax.swing.JLabel dateDataLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel faxDataLabel;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel infoPanel1;
    private javax.swing.JPanel infoPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel labelPanel1;
    private javax.swing.JPanel labelPanel2;
    private javax.swing.JLabel phoneDataLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel problemSolverPanel;
    private javax.swing.JLabel userDataLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
