/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowEmployeeTypes.java
 *
 * Created on Jan 19, 2011, 2:48:32 PM
 */

package rmischedule.print;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import rmischedule.data_connection.Connection;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.schedule_data.get_all_employee_types_query;

/**
 *
 * @author user
 */
public class ShowEmployeeTypes extends javax.swing.JDialog {

    private Connection myConn;
    private ArrayList<Integer> selectedTypes = new ArrayList<Integer>();
    private HashMap<JRadioButton, Integer> employeeTypes = new HashMap<JRadioButton, Integer>();
    
    private static final String selectAll = "Select All Types";


    /** Creates new form ShowEmployeeTypes */
    public ShowEmployeeTypes(java.awt.Frame parent, boolean modal, Connection myConn) {
        super(parent, modal);
        initComponents();

        this.myConn = myConn;
        this.showEmployeeTypes();
    }

    public ArrayList<Integer> getSelectedEmployeeTypes() {
        return this.selectedTypes;
    }

    private void showEmployeeTypes() {
        ButtonGroup typeGroup = new ButtonGroup();
        get_all_employee_types_query typeQuery = new get_all_employee_types_query();
        Record_Set rst2 = myConn.executeQuery(typeQuery);
        JRadioButton all = new JRadioButton(selectAll);
        all.setSelected(true);
        employeeTypePanel.add(all);
        typeGroup.add(all);
        for (int r = 0; r < rst2.length(); r++) {
            JRadioButton myRadio = new JRadioButton();
            employeeTypes.put(myRadio, rst2.getInt("employee_type_id"));
            myRadio.setText(rst2.getString("employee_type"));
            employeeTypePanel.add(myRadio);
            typeGroup.add(myRadio);
            rst2.moveNext();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeTypePanel = new javax.swing.JPanel();
        controlsPanel = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        employeeTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Types - Choose one or leave select all"));
        employeeTypePanel.setMaximumSize(new java.awt.Dimension(500000, 800));
        employeeTypePanel.setMinimumSize(new java.awt.Dimension(0, 80));
        employeeTypePanel.setPreferredSize(new java.awt.Dimension(0, 80));
        employeeTypePanel.setLayout(new java.awt.GridLayout(0, 3));
        getContentPane().add(employeeTypePanel);

        controlsPanel.setMaximumSize(new java.awt.Dimension(32767, 35));
        controlsPanel.setMinimumSize(new java.awt.Dimension(20, 35));
        controlsPanel.setPreferredSize(new java.awt.Dimension(20, 25));
        controlsPanel.setLayout(new javax.swing.BoxLayout(controlsPanel, javax.swing.BoxLayout.LINE_AXIS));

        cancelBtn.setText("Cancel");
        cancelBtn.setMaximumSize(new java.awt.Dimension(70, 28));
        cancelBtn.setMinimumSize(new java.awt.Dimension(70, 28));
        cancelBtn.setPreferredSize(new java.awt.Dimension(70, 28));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        controlsPanel.add(cancelBtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        controlsPanel.add(jPanel1);

        okBtn.setText("OK");
        okBtn.setMaximumSize(new java.awt.Dimension(70, 28));
        okBtn.setMinimumSize(new java.awt.Dimension(70, 28));
        okBtn.setPreferredSize(new java.awt.Dimension(70, 28));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        controlsPanel.add(okBtn);

        getContentPane().add(controlsPanel);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-394)/2, (screenSize.height-216)/2, 394, 216);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        Iterator<JRadioButton> buttonsIterator = employeeTypes.keySet().iterator();
        while (buttonsIterator.hasNext()) {
            JRadioButton currButton = buttonsIterator.next();
            if (!currButton.getText().equals(selectAll) && currButton.isSelected()) {
                selectedTypes.add(employeeTypes.get(currButton));
            }
        }
        this.setVisible(false);
}//GEN-LAST:event_okBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JPanel employeeTypePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables

}
