/*
 * CertificationPanel.java
 *
 * Created on October 13, 2005, 11:45 AM
 */

package rmischedule.employee.components;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.*;
import rmischedule.components.graphicalcomponents.DragAndDropContainer;
/**
 *
 * @author  Ira Juneau
 */
public class CertificationPanel extends javax.swing.JPanel implements DragAndDropContainer {
    
    private static final Color myColor1 = new Color(30,64,142);
    private static final Color myColor2 = new Color(156,36,31);
    private boolean isCertOnly;
    
    /** Creates new form CertificationPanel */
    public CertificationPanel(String header, Employee_Certifications myPar, boolean isCert) {
        initComponents();
        isCertOnly = isCert;
        HeaderPanel.setText(header);
        if (!isCert) {
            setBackground(myColor1);
        } else {
            setBackground(myColor2);
        }
        
    }
    
    public void highlightMe(boolean isHover, Object obj, MouseEvent evt) {
        
    }
    
    public void removeAllComps() {
        ContainerPanel.removeAll();
    }
    
    public void runOnDrop(Object obj, MouseEvent evt, BufferedImage bi) {
        ((EmployeeCertPanel)obj).setCertified(!isCertOnly);
    }
    
    public void removeComp(JComponent newComp) {
        ContainerPanel.remove(newComp);
    }
    
    public void addComp(JComponent newComp) {
        ContainerPanel.add(newComp);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ContainerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout());

        setBackground(new java.awt.Color(156, 36, 31));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)), new javax.swing.border.LineBorder(new java.awt.Color(30, 64, 142), 2, true)));
        jPanel3.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(30, 64, 142));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 18));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 18));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 18));
        HeaderPanel.setFont(new java.awt.Font("Courier New", 1, 14));
        HeaderPanel.setForeground(new java.awt.Color(255, 255, 255));
        HeaderPanel.setText("jLabel1");
        jPanel1.add(HeaderPanel);

        jPanel3.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout());

        ContainerPanel.setLayout(new javax.swing.BoxLayout(ContainerPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.add(ContainerPanel);

        jPanel3.add(jPanel2);

        add(jPanel3);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JLabel HeaderPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
}
