/*
 * Employee_Import.java
 *
 * Created on February 14, 2005, 7:54 AM
 */
package rmischedule.employee.components;

import rmischedule.employee.*;
import rmischedule.components.graphicalcomponents.*;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.employee.*;
import rmischedule.security.*;
import rmischedule.main.*;
import rmischeduleserver.control.EmployeeController;
import schedfoxlib.model.Employee;

/**
 *
 * @author  ira
 */
public class Employee_Export extends GenericEditSubForm {

    private employee_export_usked_query mySelectQuery;
    private employee_export_usked_update myUpdateQuery;
    private xEmployeeEdit myParent;

    private int employee_id;

    /** Creates new form Employee_Import */
    public Employee_Export(xEmployeeEdit main) {
        initComponents();
        myParent = main;
        mySelectQuery = new employee_export_usked_query();
        myUpdateQuery = new employee_export_usked_update();
    }

    public String checkData() {
        if (UltraIDTextField.getText().trim().length() > 10) {
            return "Usked ID can only 10 characters long. Please change ID.";
        }
        if (UltraIDTextField.getText().trim().length() > 0) {
            CheckEmployeeExportForDuplicateUskedId myCheckQuery = new CheckEmployeeExportForDuplicateUskedId();
            myCheckQuery.update(myparent.getMyIdForSave(), UltraIDTextField.getText().trim());
            Record_Set checkrs = new Record_Set();
            try {
                myParent.getConnection().prepQuery(myCheckQuery);
                checkrs = myParent.getConnection().executeQuery(myCheckQuery);
            } catch (Exception e) {
            }
            if (checkrs.length() > 0) {
                return "Usked ID is already in use for " + checkrs.getString("lname") + ", " + checkrs.getString("fname");
            }
        }
        return null;
    }

    public void loadData(Record_Set rs) {
        UltraIDTextField.setText(rs.getString("usked_id").trim());
        employee_id = rs.getInt("eid");
    }

    public boolean needsMoreRecordSets() {
        return false;
    }

    public String getMyTabTitle() {
        return "Export";
    }

    public javax.swing.JPanel getMyForm() {
        return this;
    }

    public boolean userHasAccess() {
        return Main_Window.parentOfApplication.checkSecurity(security_detail.MODULES.EMPLOYEE_EXPORT);
    }

    public void doOnClear() {
        employee_id = -1;
    }

    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getQuery(boolean isSelected) {
        mySelectQuery.update(myparent.getMyIdForSave());
        return mySelectQuery;
    }

    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getSaveQuery(boolean isNewData) {
        try {
            Employee myEmployee = (Employee)myparent.getSelectedObject();
            String ultraId = UltraIDTextField.getText().trim();
            if (ultraId.length() == 0 && employee_id <= 0) {
                EmployeeController myController = EmployeeController.getInstance(myparent.getConnection().myCompany);
                ultraId = myController.generateNewUskedId(myEmployee);
            }
            myUpdateQuery.update(ultraId, myparent.getMyIdForSave());
            return myUpdateQuery;
        } catch (Exception e) {
            System.out.println("Exception in saving export: " + e.getMessage());
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CCSImport = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UltraIDTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        SpacerPanel = new javax.swing.JPanel();
        ControlPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(186, 186, 222));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3), javax.swing.BorderFactory.createEtchedBorder()));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        CCSImport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ultra Sked", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        CCSImport.setMaximumSize(new java.awt.Dimension(1600, 120));
        CCSImport.setMinimumSize(new java.awt.Dimension(1600, 120));
        CCSImport.setPreferredSize(new java.awt.Dimension(16, 120));
        CCSImport.setLayout(new javax.swing.BoxLayout(CCSImport, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Ultra Sked ID:");
        jPanel1.add(jLabel1);

        UltraIDTextField.setMinimumSize(new java.awt.Dimension(6, 22));
        UltraIDTextField.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel1.add(UltraIDTextField);

        CCSImport.add(jPanel1);
        CCSImport.add(jPanel3);

        add(CCSImport);
        add(SpacerPanel);

        ControlPanel.setMaximumSize(new java.awt.Dimension(32767, 40));
        ControlPanel.setMinimumSize(new java.awt.Dimension(10, 40));
        ControlPanel.setPreferredSize(new java.awt.Dimension(10, 40));
        ControlPanel.setLayout(new javax.swing.BoxLayout(ControlPanel, javax.swing.BoxLayout.LINE_AXIS));
        ControlPanel.add(jPanel2);

        add(ControlPanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CCSImport;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel SpacerPanel;
    private javax.swing.JTextField UltraIDTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
