/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmischedule.employee.components;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JToggleButton;
import rmischeduleserver.control.GenericController;
import rmischeduleserver.control.HealthCareController;
import schedfoxlib.model.EmployeeHealthcare;
import schedfoxlib.model.HealthCareOption;

/**
 *
 * @author ira
 */
public class EmployeeHealthcarePanel extends javax.swing.JPanel {

    private String companyId;
    private Integer employeeId;
    private ArrayList<JToggleButton> buttons;
    private ArrayList<Integer> buttonVal;
    private EmployeeHealthcare healthcare;
    private ButtonGroup group;

    /**
     * Creates new form EmployeeHealthcarePanel
     */
    public EmployeeHealthcarePanel(String companyId) {
        initComponents();

        this.companyId = companyId;

        try {
            HealthCareController healthController = HealthCareController.getInstance(companyId);
            ArrayList<HealthCareOption> healthOptions = healthController.getHealthCareOptions();
            group = new ButtonGroup();
            buttons = new ArrayList<JToggleButton>();
            buttonVal = new ArrayList<Integer>();
            for (int o = 0; o < healthOptions.size(); o++) {
                JToggleButton button = new JToggleButton(healthOptions.get(o).getName());
                this.add(button);
                group.add(button);
                buttons.add(button);
                buttonVal.add(healthOptions.get(o).getHealthcareOptionsId());
            }
        } catch (Exception exe) {
            exe.printStackTrace();
        }
    }

    public void setData(int employeeId) {
        try {
            HealthCareController healthController = HealthCareController.getInstance(companyId);
            healthcare = healthController.getEmployeeHealthcare(employeeId);

            group.clearSelection();
            this.employeeId = employeeId;
            for (int b = 0; b < buttons.size(); b++) {
                if (healthcare != null && healthcare.getHealthcareOptionId() != null) {
                    if (healthcare.getHealthcareOptionId().equals(buttonVal.get(b))) {
                        buttons.get(b).setSelected(true);
                    }
                }
            }
        } catch (Exception exe) {
            exe.printStackTrace();
        }
    }

    public void saveData() {
        int selectedHealthcare = -1;
        HealthCareController healthController = HealthCareController.getInstance(companyId);
        for (int b = 0; b < buttons.size(); b++) {
            if (buttons.get(b).isSelected()) {
                selectedHealthcare = buttonVal.get(b);
            }
        }
        if (healthcare != null) {
            if (healthcare.getHealthcareOptionId() == null || selectedHealthcare != healthcare.getHealthcareOptionId()) {
                try {
                    healthController.removeHealthcareFromEmployee(this.employeeId);
                } catch (Exception exe) {
                    exe.printStackTrace();
                }

                healthcare = new EmployeeHealthcare();
                healthcare.setActive(true);
                healthcare.setSetOn(new Date(GenericController.getInstance(companyId).getCurrentTimeMillis()));
                healthcare.setEmployeeId(employeeId);
                healthcare.setHealthcareOptionId(selectedHealthcare);
                try {
                    healthController.saveEmployeeHealthcare(healthcare);
                } catch (Exception exe) {
                    exe.printStackTrace();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(2, 3));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
