/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmployeeDynamicForm.java
 *
 * Created on Aug 15, 2010, 10:48:31 PM
 */
package rmischedule.employee.components;

import rmischedule.components.DynamicFieldPanel;
import java.util.Vector;
import javax.swing.JPanel;
import rmischedule.components.graphicalcomponents.GenericEditSubForm;
import rmischedule.components.graphicalcomponents.GenericTabbedEditForm;
import rmischedule.main.Main_Window;
import rmischedule.xadmin.model.DynamicFieldValue;
import rmischedule.security.security_detail;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat;
import rmischeduleserver.mysqlconnectivity.queries.employee.save_employee_dynamic_data_query;
import rmischeduleserver.mysqlconnectivity.queries.util.GenericQuery;

/**
 *
 * @author user
 */
public class EmployeeDynamicForm extends GenericEditSubForm implements DynamicPanelParent {

    private GenericTabbedEditForm myParent;
    private Vector<DynamicFieldPanel> myFieldPanels;
    private DynamicFormPanel dynamicFormPanel;

    /** Creates new form EmployeeDynamicForm */
    public EmployeeDynamicForm(GenericTabbedEditForm myParent) {
        initComponents();
        this.myParent = myParent;
        this.myFieldPanels = new Vector<DynamicFieldPanel>();
        this.dynamicFormPanel = new DynamicFormPanel(myParent, this,
                getDynamicType(), isClient(), isEmployee());
        jAdditionalFieldsScrollPane.setViewportView(dynamicFormPanel);
    }

    protected int getDynamicType() {
        return 1;
    }

    protected boolean isClient() {
        return false;
    }

    protected boolean isEmployee() {
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBasePanel = new javax.swing.JPanel();
        jFileFieldsScrollPane = new javax.swing.JScrollPane();
        jAdditionalFieldsFilePane = new javax.swing.JPanel();
        jAdditionalFieldsScrollPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jBasePanel.setLayout(new java.awt.GridLayout(2, 1));

        jAdditionalFieldsFilePane.setLayout(new javax.swing.BoxLayout(jAdditionalFieldsFilePane, javax.swing.BoxLayout.Y_AXIS));
        jFileFieldsScrollPane.setViewportView(jAdditionalFieldsFilePane);

        jBasePanel.add(jFileFieldsScrollPane);
        jBasePanel.add(jAdditionalFieldsScrollPane);

        add(jBasePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public GeneralQueryFormat getQuery(boolean isSelected) {
        return new GenericQuery("Select NOW()");
    }

    @Override
    public GeneralQueryFormat getSaveQuery(boolean isNewData) {
        dynamicFormPanel.save();

        return new GenericQuery("Select NOW()");
    }

    @Override
    public void loadData(Record_Set rs) {
        dynamicFormPanel.loadData();
    }

    

    @Override
    public boolean needsMoreRecordSets() {
        return false;
    }

    @Override
    public String getMyTabTitle() {
        return "Additional Fields";
    }

    @Override
    public JPanel getMyForm() {
        return this;
    }

    @Override
    public void doOnClear() {
        this.jAdditionalFieldsFilePane.removeAll();
        this.dynamicFormPanel.clear();
        this.myFieldPanels.clear();
    }

    public JPanel getPanelForFileDynamicForms() {
        return this.jAdditionalFieldsFilePane;
    }
    
    @Override
    public boolean userHasAccess() {
        return Main_Window.mySecurity.checkSecurity(security_detail.MODULES.EMPLOYEE_EDIT);
//        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAdditionalFieldsFilePane;
    private javax.swing.JScrollPane jAdditionalFieldsScrollPane;
    private javax.swing.JPanel jBasePanel;
    private javax.swing.JScrollPane jFileFieldsScrollPane;
    // End of variables declaration//GEN-END:variables

}
