/*
 * Employee_Certifications.java
 *
 * Created on May 26, 2005, 11:13 AM
 */

/**
 *  Modifications:  Jeffrey Davis renamed tab from "Certifications" to "Certs"
 *      on 06/16/2010 per Jim's request
 */

package rmischedule.employee.components;
import com.creamtec.ajaxswing.AjaxSwingManager;
import com.creamtec.ajaxswing.core.ClientAgent;
import rmischedule.employee.*;
import rmischedule.components.graphicalcomponents.*;
import rmischedule.security.*;
import rmischedule.main.*;
import rmischedule.components.*;
import rmischeduleserver.mysqlconnectivity.queries.employee.employee_certifications_list_query;
import schedfoxlib.model.util.Record_Set;
import java.util.*;
import schedfoxlib.model.EmployeeCertification;
/**
 *
 * @author  ira
 */
public class Employee_Certifications extends GenericEditSubForm {
    
    private String eid;
    public xEmployeeEdit myParent;
    private CertificationPanel myCertificationPanel;
    private CertificationPanel employeeCerts;
    
    /** Creates new form Employee_Certifications */
    public Employee_Certifications(xEmployeeEdit parent) {
        initComponents();
        myCertificationPanel = new CertificationPanel("Available Certifications", this, true);
        employeeCerts = new CertificationPanel("Employee Has Following Certifications", this, false);
        
        myParent = parent;
        eid = "";
        ControlPanel.setBounds(myLayeredPane.getBounds());
        jPanel1.add(myCertificationPanel);
        jPanel2.add(employeeCerts);
    }

    public void doOnClear() {
        myCertificationPanel.removeAllComps();
        employeeCerts.removeAllComps();
    }

    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getQuery(boolean isNew) {
        employee_certifications_list_query myQuery = new employee_certifications_list_query();
        myQuery.update(myparent.getMyIdForSave(), true);
        return myQuery;
    }

    public void loadData(Record_Set rs) {
        myCertificationPanel.removeAllComps();
        employeeCerts.removeAllComps();
        try {
            for (int i = 0; i < rs.length(); i++) {
                EmployeeCertification myCert = new EmployeeCertification(rs);
                EmployeeCertPanel temp = new EmployeeCertPanel(this, myCert);
                temp.setInterval(rs.getString("interval"));
                rs.moveNext();
            }
        } catch (Exception e) {
            System.out.println("Could not load the certifications tab. Error: " + e.toString());
        }
    }

    /**
     *
     */
    public void moveCertToCertification(EmployeeCertPanel obj) {
        employeeCerts.removeComp(obj);
        myCertificationPanel.addComp(obj);
        revalidate();
        repaint();
        if (AjaxSwingManager.isAjaxSwingRunning()) {
            ClientAgent.getCurrentInstance().getHTMLPage().setComponentDirty(this, true);
        }
    }
    
    /**
     *
     */
    public void moveCertToEmployeeHas(EmployeeCertPanel obj) {
        myCertificationPanel.removeComp(obj);
        employeeCerts.addComp(obj);
        revalidate();
        repaint();
        if (AjaxSwingManager.isAjaxSwingRunning()) {
            ClientAgent.getCurrentInstance().getHTMLPage().setComponentDirty(this, true);
        }
    }
    
    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getSaveQuery(boolean isNew) {
        return null;
    }
    
    public boolean needsMoreRecordSets() {
        return false;
    }

    public String getMyTabTitle() {
        //  tab title changed by Jeffrey Davis on 06/16/2010 per Jim's request
        return "Certs";
    }

    public javax.swing.JPanel getMyForm() {
        return this;
    }

    public boolean userHasAccess() {
        return Main_Window.parentOfApplication.checkSecurity(security_detail.MODULES.EMPLOYEE_EDIT);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myLayeredPane = new javax.swing.JLayeredPane();
        ControlPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        listCertifications = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        employeeCertifications = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(186, 186, 222));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3), javax.swing.BorderFactory.createEtchedBorder()));
        setLayout(new java.awt.GridLayout(1, 0));

        myLayeredPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                resizeControl(evt);
            }
        });

        ControlPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        ControlPanel.setLayout(new javax.swing.BoxLayout(ControlPanel, javax.swing.BoxLayout.Y_AXIS));

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        listCertifications.setViewportView(jPanel1);

        jSplitPane1.setLeftComponent(listCertifications);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        employeeCertifications.setViewportView(jPanel2);

        jSplitPane1.setRightComponent(employeeCertifications);

        ControlPanel.add(jSplitPane1);

        ControlPanel.setBounds(0, 0, 390, 420);
        myLayeredPane.add(ControlPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(myLayeredPane);
    }// </editor-fold>//GEN-END:initComponents

    private void resizeControl(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_resizeControl
        ControlPanel.setBounds(myLayeredPane.getBounds());
    }//GEN-LAST:event_resizeControl
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ControlPanel;
    private javax.swing.JScrollPane employeeCertifications;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane listCertifications;
    public javax.swing.JLayeredPane myLayeredPane;
    // End of variables declaration//GEN-END:variables
    
}
