//  package declaration
package rmischedule.templates.view;

//  import declarations
import com.inet.jortho.SpellChecker;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import rmischedule.main.Main_Window;
import rmischedule.templates.controllers.TemplateSystemController;
import rmischedule.templates.models.InitializeTemplateSystem;

/**
 *
 * @author jdavis
 */
public class TemplateDiagForm extends javax.swing.JDialog
{
    //  private variable declaration
    TemplateSystemController controller;

    protected void setPlaceholderButtonVisible(boolean isVisible)
    {
        this.jPlaceholdersButton.setVisible(isVisible);
    }

    /**
     *  Default initialization of this object is not supported.
     *  @since 02/28/2011
     *  @throws UnsupportedOperationException
     */
    public TemplateDiagForm()
    {
        super(Main_Window.parentOfApplication, true);
        initComponents();

        //  set icons
        this.jSaveButton.setIcon(Main_Window.Edit_Template_Diag_Save_16x16_px);
        this.jDeleteButton.setIcon(Main_Window.Edit_Template_Diag_Exit_16x16_px);
        this.jExitButton.setIcon(Main_Window.Edit_Template_Diag_Delete_16x16_px);

        //  set text area
        this.jTemplateTextArea.setWrapStyleWord(true);
        this.jTemplateTextArea.setLineWrap(true);
        this.jTemplateTextArea.setColumns(25);

        //  set spellchecker
        try
        {
            SpellChecker.register( this.jTemplateNameTextField );
            SpellChecker.register( this.jTemplateTextArea );
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }
    /**
     *  Initializes this objects controller
     */
    public void init( InitializeTemplateSystem incomingInit )
    {
        this.controller = TemplateSystemController.getInstance();
        this.controller.init(incomingInit, this);
    }

    /*  mutators for controller */
    public JComboBox getJTemplateListingComboBox()  { return this.jTemplateListingComboBox; }
    public JButton getJPlaceholdersButton() { return this.jPlaceholdersButton; }
    public JTextField getJTemplateNameTextField()   { return this.jTemplateNameTextField; }
    public JTextArea getJTemplateTextArea() { return this.jTemplateTextArea; }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jBasePanel = new javax.swing.JPanel();
        jControlPanel = new javax.swing.JPanel();
        jTemplateComboBoxLabel = new javax.swing.JLabel();
        jTemplateListingComboBox = new javax.swing.JComboBox();
        jNewTemplateButton = new javax.swing.JButton();
        jTemplateNameLabel = new javax.swing.JLabel();
        jTemplateNameTextField = new javax.swing.JTextField();
        jPlaceholdersButton = new javax.swing.JButton();
        jTextAreaPanel = new javax.swing.JPanel();
        jTemplateTextAreaScrollPane = new javax.swing.JScrollPane();
        jTemplateTextArea = new javax.swing.JTextArea();
        jSaveDeleteExitPanel = new javax.swing.JPanel();
        jSaveButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(380, 205));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jBasePanel.setLayout(new javax.swing.BoxLayout(jBasePanel, javax.swing.BoxLayout.PAGE_AXIS));

        jControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Template Controls"));

        jTemplateComboBoxLabel.setText("Templates:  ");

        jTemplateListingComboBox.setMinimumSize(new java.awt.Dimension(26, 24));
        jTemplateListingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTemplateListingComboBoxActionPerformed(evt);
            }
        });

        jNewTemplateButton.setText("Clear");
        jNewTemplateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewTemplateButtonActionPerformed(evt);
            }
        });

        jTemplateNameLabel.setText("Template Name:  ");

        jPlaceholdersButton.setText("Placeholders");
        jPlaceholdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlaceholdersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jControlPanelLayout = new javax.swing.GroupLayout(jControlPanel);
        jControlPanel.setLayout(jControlPanelLayout);
        jControlPanelLayout.setHorizontalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTemplateNameLabel)
                    .addComponent(jTemplateComboBoxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTemplateListingComboBox, 0, 165, Short.MAX_VALUE)
                    .addComponent(jTemplateNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPlaceholdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNewTemplateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jControlPanelLayout.setVerticalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemplateComboBoxLabel)
                    .addComponent(jNewTemplateButton)
                    .addComponent(jTemplateListingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemplateNameLabel)
                    .addComponent(jTemplateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPlaceholdersButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jBasePanel.add(jControlPanel);

        jTextAreaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Template"));
        jTextAreaPanel.setLayout(new java.awt.GridBagLayout());

        jTemplateTextAreaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTemplateTextArea.setColumns(20);
        jTemplateTextArea.setRows(5);
        jTemplateTextAreaScrollPane.setViewportView(jTemplateTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jTextAreaPanel.add(jTemplateTextAreaScrollPane, gridBagConstraints);

        jBasePanel.add(jTextAreaPanel);

        jSaveDeleteExitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Actions"));

        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        jDeleteButton.setText("Delete");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSaveDeleteExitPanelLayout = new javax.swing.GroupLayout(jSaveDeleteExitPanel);
        jSaveDeleteExitPanel.setLayout(jSaveDeleteExitPanelLayout);
        jSaveDeleteExitPanelLayout.setHorizontalGroup(
            jSaveDeleteExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSaveDeleteExitPanelLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jSaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jExitButton)
                .addGap(31, 31, 31))
        );
        jSaveDeleteExitPanelLayout.setVerticalGroup(
            jSaveDeleteExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSaveDeleteExitPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jSaveDeleteExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaveButton)
                    .addComponent(jDeleteButton)
                    .addComponent(jExitButton))
                .addContainerGap())
        );

        jBasePanel.add(jSaveDeleteExitPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jBasePanel, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-451)/2, (screenSize.height-374)/2, 451, 374);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        this.controller.saveTemplateAction();
    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        this.controller.deleteTemplateAction();
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jNewTemplateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewTemplateButtonActionPerformed
        this.controller.newTemplateAction();
    }//GEN-LAST:event_jNewTemplateButtonActionPerformed

    private void jPlaceholdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlaceholdersButtonActionPerformed
        this.controller.placeholderAction();
    }//GEN-LAST:event_jPlaceholdersButtonActionPerformed

    private void jTemplateListingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTemplateListingComboBoxActionPerformed
        this.controller.comboBoxAction();
    }//GEN-LAST:event_jTemplateListingComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBasePanel;
    private javax.swing.JPanel jControlPanel;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JButton jNewTemplateButton;
    private javax.swing.JButton jPlaceholdersButton;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JPanel jSaveDeleteExitPanel;
    private javax.swing.JLabel jTemplateComboBoxLabel;
    private javax.swing.JComboBox jTemplateListingComboBox;
    private javax.swing.JLabel jTemplateNameLabel;
    private javax.swing.JTextField jTemplateNameTextField;
    private javax.swing.JTextArea jTemplateTextArea;
    private javax.swing.JScrollPane jTemplateTextAreaScrollPane;
    private javax.swing.JPanel jTextAreaPanel;
    // End of variables declaration//GEN-END:variables
};
