/*
 * NewBranch_LB.java
 *
 * Created on February 23, 2005, 1:31 PM
 */

package rmischedule.components;
import rmischedule.main.Main_Window;
import rmischedule.components.*;
import java.awt.*;
import java.awt.event.*;
import java.io.DataInputStream;
import java.util.Vector;

import javax.swing.*;
import rmischeduleserver.mysqlconnectivity.queries.util.*;
import rmischeduleserver.data_connection_types.*;
import rmischedule.data_connection.Connection;
/**
 *
 * @author  ira
 */
public class Branch_LB extends javax.swing.JPanel {
    
    private Vector branchId;
    private Vector branchName;
    
    private Main_Window parent;
    
    private ActionListener myActionListener = null;
    /** Creates new form NewBranch_LB */
    public Branch_LB(Main_Window Parent) {
        parent = Parent;
        branchId = parent.getBranchId();
        branchName = parent.getBranchNames();
        initComponents();
        lbBranch.addActionListener(new Branch_LB.BranchActionListener(this));
    }
    
    /**
     * Self explainatory...should really be moved to Main_Window eventually...
     */
    public String getBranchNameById(String id) {
        return parent.getBranchNameById(id);
    }
    
    public void setBranchLocation(String bId){
        int c, i;
        c = branchId.size();
        for(i=0;i<c;i++){
            try {
            if(((String)branchId.get(i)).equals(bId)){
                lbBranch.setSelectedItem((String)branchName.get(i));
                break;
            }
            } catch (Exception e) {}
        }
    }
    
    public int getLength(){
        return branchId.size();
    }
    
    public String getBranchName(int i) {
        return (String)branchName.get(i);
    }
    
    public String getBranchId(int i) {
        return (String)branchId.get(i);
    }
    
    public void addActionListener(ActionListener al){
        myActionListener = al;
    }
    
    public int getSelectedIndex(){
        return lbBranch.getSelectedIndex();
    }
    
    public String getSelectedItem(){
        return (String) lbBranch.getSelectedItem();
    }
    
    public String getSelectedBranchId(){
        return (String)branchId.get(lbBranch.getSelectedIndex());
    }
    
    public String getSelectedBranchName(){
        return (String)branchName.get(lbBranch.getSelectedIndex());
    }
    
    class BranchActionListener implements ActionListener{
        
        private Branch_LB myCb;
        
        public BranchActionListener(Branch_LB c){
            myCb = c;
        }
        
        public void actionPerformed(ActionEvent e){
            if(myCb.myActionListener != null){
                myCb.myActionListener.actionPerformed(e);
            }
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        SpacerPanel = new javax.swing.JPanel();
        lbBranch = new JComboBox(branchName);
        jPanel2 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 10)));
        jPanel3.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jPanel3.setMinimumSize(new java.awt.Dimension(10, 0));
        add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32814, 22));
        jPanel1.setMinimumSize(new java.awt.Dimension(70, 22));
        TitleLabel.setText("Branch:");
        TitleLabel.setMaximumSize(new java.awt.Dimension(60, 14));
        TitleLabel.setMinimumSize(new java.awt.Dimension(60, 14));
        TitleLabel.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(TitleLabel);

        SpacerPanel.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel1.add(SpacerPanel);

        jPanel1.add(lbBranch);

        add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jPanel2.setMinimumSize(new java.awt.Dimension(10, 0));
        add(jPanel2);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SpacerPanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox lbBranch;
    // End of variables declaration//GEN-END:variables
    
}
