/*
 * NewBranch_LB.java
 *
 * Created on February 23, 2005, 1:31 PM
 */

package rmischedule.components;
import rmischedule.main.Main_Window;
import rmischedule.components.*;

import java.awt.*;
import java.awt.event.*;
import java.io.DataInputStream;
import java.util.Vector;

import javax.swing.*;
import rmischedule.data_connection.*;
import rmischeduleserver.data_connection_types.*;
import rmischeduleserver.mysqlconnectivity.queries.util.*;
/**
 *
 * @author  ira
 */
public class Company_LB extends javax.swing.JPanel {
    private Vector companyId;
    private Vector companyName;
    
    private Main_Window parent;
    
    private ActionListener myActionListener = null;
    /** Creates new form NewBranch_LB */
    public Company_LB(Main_Window Parent) {
        parent = Parent;
        companyId = parent.getCompanyId();
        companyName = parent.getCompanyNames();
        initComponents();
        lbCompany.addActionListener(new Company_LB.CompanyActionListener(this));
    }
    
    /**
     * Self explainatory...should really be moved to Main_Window eventually...
     */
    public String getCompanyNameById(String id) {
        return parent.getCompanyNameById(id);
    }
    
    public String getCompanyName(int i) {
        return (String)companyName.get(i);
    }
    
    public String getCompanyId(int i) {
        return (String)companyId.get(i);
    }
    
    public int getLength(){
        return companyId.size();
    }
    
    public void addActionListener(ActionListener al){
        myActionListener = al;
    }
    
    public int getSelectedIndex(){
        return lbCompany.getSelectedIndex();
    }
    
    public String getSelectedItem(){
        return (String) lbCompany.getSelectedItem();
    }
    
    public String getSelectedCompanyId(){
        return (String)companyId.get(lbCompany.getSelectedIndex());
    }
    
    public String getSelectedCompanyName(){
        return (String)companyName.get(lbCompany.getSelectedIndex());
    }
    
    public void setSelectedCompanyId(String id){
        int i, c;
        c = companyId.size();
        for(i=0;i<c;i++){
            try {
            if(((String)companyId.get(i)).equals(id)){
                lbCompany.setSelectedItem((String)companyName.get(i));
                break;
            }
            } catch (Exception e) {}
        }
    }
    
    class CompanyActionListener implements ActionListener{
        
        private Company_LB myCb;
        
        public CompanyActionListener(Company_LB c){
            myCb = c;
        }
        
        public void actionPerformed(ActionEvent e){
            if(myCb.myActionListener != null){
                myCb.myActionListener.actionPerformed(e);
            }
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        SpacerPanel = new javax.swing.JPanel();
        lbCompany = new JComboBox(companyName);
        jPanel2 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 10)));
        jPanel3.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jPanel3.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(10, 5));
        add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32814, 22));
        jPanel1.setMinimumSize(new java.awt.Dimension(70, 22));
        TitleLabel.setText("Company: ");
        TitleLabel.setMaximumSize(new java.awt.Dimension(60, 14));
        TitleLabel.setMinimumSize(new java.awt.Dimension(60, 14));
        TitleLabel.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(TitleLabel);

        SpacerPanel.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel1.add(SpacerPanel);

        lbCompany.setMaximumSize(new java.awt.Dimension(1000000, 150000));
        jPanel1.add(lbCompany);

        add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jPanel2.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(10, 5));
        add(jPanel2);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SpacerPanel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox lbCompany;
    // End of variables declaration//GEN-END:variables
    
}
