/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DynamicFieldMoneyType.java
 *
 * Created on Aug 18, 2010, 1:50:43 PM
 */
package rmischedule.components;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import rmischedule.xadmin.model.DynamicFieldValue;

/**
 *
 * @author user
 */
public class DynamicFieldMoneyType extends javax.swing.JPanel implements DynamicFieldTypeInterface {

    private JTextField field;

    /** Creates new form DynamicFieldMoneyType */
    public DynamicFieldMoneyType(boolean enabled) {
        initComponents();

        field = this.getField();
        this.add(field);
    }

    public JTextField getField() {
        JFormattedTextField tmpVal = null;
        try {
            NumberFormatter defaultFormatter = new NumberFormatter(new DecimalFormat("#.##"));
            NumberFormatter displayFormatter =
                    new NumberFormatter(new DecimalFormat("$#,###.00"));
            NumberFormatter editFormatter = new NumberFormatter(new DecimalFormat("#.##"));
            defaultFormatter.setValueClass(Double.class);
            displayFormatter.setValueClass(Double.class);
            editFormatter.setValueClass(Double.class);
            DefaultFormatterFactory moneyFactory =
                    new DefaultFormatterFactory(defaultFormatter, displayFormatter, editFormatter);
            tmpVal = new JFormattedTextField();
            tmpVal.setFormatterFactory(moneyFactory);
        } catch (Exception e) {
            tmpVal = new JFormattedTextField(NumberFormat.getInstance());
        }
        return tmpVal;
    }

    public String getValue() {
        if (field instanceof JFormattedTextField) {
            try {
                ((JFormattedTextField)field).commitEdit();
                return ((JFormattedTextField)field).getValue().toString();
            } catch (Exception e) {}
        } else {
            return field.getText();
        }
        return "";
    }

    public void setValue(DynamicFieldValue value) {
        String tmpVal = "";
        try {
            NumberFormat myFormat = NumberFormat.getCurrencyInstance();
            tmpVal = myFormat.format(value.getDynamic_field_value());
        } catch (Exception e) {}
        if (field instanceof JFormattedTextField) {
            try {
                ((JFormattedTextField)field).setValue(Double.parseDouble(value.getDynamic_field_value()));
            } catch (Exception e) {
                ((JFormattedTextField)field).setValue(0);
            }
        } else {
            field.setText(tmpVal);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(100, 77));
        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents

    public JComponent getComponent() {
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
