/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RatingBoxPanel.java
 *
 * Created on Nov 28, 2011, 3:51:31 PM
 */
package rmischedule.components;

import java.awt.event.MouseListener;
import java.util.List;
import rmischedule.main.Main_Window;

/**
 *
 * @author user
 */
public class RatingBoxPanel extends javax.swing.JPanel {

    private List<RatingBoxPanel> ratingsBelow;
    private List<RatingBoxPanel> ratingsAbove;
    private int size;

    /** Creates new form RatingBoxPanel */
    public RatingBoxPanel(int size) {
        initComponents();

        if (size == 24) {
            setMaximumSize(new java.awt.Dimension(25, 25));
            setMinimumSize(new java.awt.Dimension(25, 25));
            setPreferredSize(new java.awt.Dimension(25, 25));
        }

        this.size = size;
        ratingLabel.setIcon(Main_Window.disabledStarIcon);
    }

    @Override
    public void addMouseListener(MouseListener listener) {
        super.addMouseListener(listener);
        this.ratingLabel.addMouseListener(listener);
    }

    public void setRatings(List<RatingBoxPanel> ratingsBelow, List<RatingBoxPanel> ratingsAbove) {
        this.ratingsBelow = ratingsBelow;
        this.ratingsAbove = ratingsAbove;
    }

    public void setSelected(boolean value, boolean setOthers) {
        if (value) {
            if (size == 24) {
                ratingLabel.setIcon(Main_Window.starIcon_24);
            } else {
                ratingLabel.setIcon(Main_Window.starIcon);
            }
        } else {
            if (size == 24) {
                ratingLabel.setIcon(Main_Window.disabledStarIcon_24);
            } else {
                ratingLabel.setIcon(Main_Window.disabledStarIcon);
            }
        }
        if (setOthers) {
            for (int r = 0; r < ratingsBelow.size(); r++) {
                ratingsBelow.get(r).setSelected(true && value, false);
            }
            for (int r = 0; r < ratingsAbove.size(); r++) {
                ratingsAbove.get(r).setSelected(false, false);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(33, 33));
        setMinimumSize(new java.awt.Dimension(33, 33));
        setPreferredSize(new java.awt.Dimension(33, 33));
        setLayout(new java.awt.GridLayout(1, 0));
        add(ratingLabel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ratingLabel;
    // End of variables declaration//GEN-END:variables
}
