/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RatingPanel.java
 *
 * Created on Nov 28, 2011, 3:47:50 PM
 */

package rmischedule.components;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author user
 */
public class RatingPanel extends javax.swing.JPanel {

    private ArrayList<RatingBoxPanel> ratings;
    private Integer selectedRating;
    private ArrayList<ChangeListener> changeListeners;

    private RatingPanel thisObject;

    /** Creates new form RatingPanel */
    public RatingPanel(int numberOfRatings, int size) {
        initComponents();

        thisObject = this;
        changeListeners = new ArrayList<ChangeListener>();
        ratings = new ArrayList<RatingBoxPanel>();

        for (int r = 0; r < numberOfRatings; r++) {
            ratings.add(new RatingBoxPanel(size));
        }

        for (int r = 0; r < numberOfRatings; r++) {
            this.add(ratings.get(r));
            final int num = r;
            ratings.get(r).addMouseListener(new MouseListener() {

                public void mouseClicked(MouseEvent e) {
                    
                }

                public void mousePressed(MouseEvent e) {
                    ratings.get(num).setSelected(true, true);
                    selectedRating = num;
                    ChangeEvent changeEvent = new ChangeEvent(thisObject);
                    for (int c = 0; c < changeListeners.size(); c++) {
                        changeListeners.get(c).stateChanged(changeEvent);
                    }
                }

                public void mouseReleased(MouseEvent e) {
                    
                }

                public void mouseEntered(MouseEvent e) {
                    if (selectedRating == null) {
                        ratings.get(num).setSelected(true, true);
                    }
                }

                public void mouseExited(MouseEvent e) {
                    if (selectedRating == null) {
                        ratings.get(num).setSelected(false, true);
                    }
                }

            });
        }

        for (int r = 0; r < numberOfRatings; r++) {
            int end = r;
            if (end < 0) {
                end = 0;
            }
            int start = r + 1;
            if (start >= numberOfRatings) {
                start = numberOfRatings;
            }
            ratings.get(r).setRatings(ratings.subList(0, end), ratings.subList(start, numberOfRatings));
        }
    }

    public void clearRating() {
        this.selectedRating = 0;
        for (int r = 0; r < ratings.size(); r++) {
            ratings.get(r).setSelected(false, false);
        }
    }

    public void setRating(int rating) {
        try {
            ratings.get(rating - 1).setSelected(true, true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Integer getRating() {
        try {
            return this.selectedRating + 1;
        } catch (Exception e) {
            return 0;
        }
    }

    public void setSelected(boolean selected) {
        selectedRating = null;
        for (int r = 0; r < ratings.size(); r++) {
            ratings.get(r).setSelected(selected, false);
        }
    }

    public void addChangeListener(ChangeListener changeLister) {
        changeListeners.add(changeLister);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
