/*
 * rate_code_edit.java
 *
 * Created on August 10, 2005, 8:56 AM
 */

package rmischedule.rate_codes;

import rmischedule.components.*;
import rmischedule.data_connection.*;

import rmischeduleserver.*;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.rate_codes.*;

import java.util.*;

import javax.swing.*;
import javax.swing.event.*;

import java.awt.event.*;
/**
 *
 * @author  jason.allen
 */
public class rate_code_edit extends javax.swing.JInternalFrame {
    private List_View lvRateList;
    private String companyId;
    private String companyName;
    private Connection myConnection;
    private String current_edit_id;
    private Vector<JTextField> myComponents;
    
    /** 
     * Creates new form rate_code_edit 
     */
    public rate_code_edit(String company_id, String company_name) {
        initComponents();
        
        setSize(500, 300);
        
        setVisible(true);
        setClosable(true);
        setResizable(true);
        setMaximizable(true);
        
        lvRateList = new List_View();

        lvRateList.addColumn("Id",        List_View.STRING, false, false);
        lvRateList.addColumn("Rate Code", List_View.STRING, 200);
        lvRateList.addColumn("Usked",     List_View.STRING, 200);

        lvRateList.addListSelectionListener(
            new ListSelectionListener(){
            	public void valueChanged(ListSelectionEvent e){
                    current_edit_id = (String)lvRateList.getSelectedCell(0);

                    efRateCode.setText((String)lvRateList.getSelectedCell(1));
                       efUsked.setText((String)lvRateList.getSelectedCell(2));
                       
                       pbCancel.setText("Cancel");
                    pbAddUpdate.setText("Update");
                }    
            }
        );
        
        lvRateList.buildTable();
        lvRateList.maximizeTable();

        pnRateList.add(lvRateList.myScrollPane);
        
        companyName = company_name;
        companyId   = company_id;
        
        this.setTitle("Rate Code Edit (" + companyName + ")");

        /* set up our connection*/
        myConnection = new Connection();
        myConnection.setCompany(companyId);
        
        getData();

        pbCancel.setText("Exit");
        
        myComponents = new Vector();
        
        myComponents.add(efRateCode);
        myComponents.add(efUsked);
        
        for (int i = 0; i < myComponents.size(); i++) {
            myComponents.get(i).addKeyListener(new myTextListener());
        }
        
    }
        
    
    /**
     *  This gets the Rate Code Information from the server and populates
     *  List View
     */
    private void getData(){
        rate_code_list_query rclq = new rate_code_list_query();
        Record_Set rs             = new Record_Set();
        
        lvRateList.clearRows();
        
        try{
            rs = myConnection.executeQuery(rclq);
        }catch(Exception e){
            e.printStackTrace();
        }
        
        rs.moveToFront();
    
        for (int i = 0; i < rs.length(); i++) {
            lvRateList.addRow(rs);
            rs.moveNext();
        }
        
        lvRateList.fireTableDataChanged();    
    }    

    /**
     * Clears the fields and sets the pbAddUpdate text to 'Add'
     */
    private void clearData(){
        current_edit_id = "";

        efRateCode.setText("");
           efUsked.setText("");

        pbAddUpdate.setText("Add");        
        pbCancel.setText("Exit");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnRateList = new javax.swing.JPanel();
        pnBottom = new javax.swing.JPanel();
        pnEdit = new javax.swing.JPanel();
        pnEdit2 = new javax.swing.JPanel();
        pnEditSpacer1 = new javax.swing.JPanel();
        pnEditFields = new javax.swing.JPanel();
        pnEditRateCode = new javax.swing.JPanel();
        lblRateCode = new javax.swing.JLabel();
        efRateCode = new javax.swing.JTextField();
        pnEditUsked = new javax.swing.JPanel();
        lblUsked = new javax.swing.JLabel();
        efUsked = new javax.swing.JTextField();
        pnEditButton = new javax.swing.JPanel();
        pbAddUpdate = new javax.swing.JButton();
        pbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pnRateList.setLayout(new java.awt.BorderLayout());

        getContentPane().add(pnRateList, java.awt.BorderLayout.CENTER);

        pnBottom.setLayout(new java.awt.BorderLayout());

        pnEdit.setLayout(new javax.swing.BoxLayout(pnEdit, javax.swing.BoxLayout.X_AXIS));

        pnEdit.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 5, 5, 1)));
        pnEdit2.setLayout(new javax.swing.BoxLayout(pnEdit2, javax.swing.BoxLayout.X_AXIS));

        pnEdit2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 1, 5, 1)));
        pnEdit2.add(pnEditSpacer1);

        pnEditFields.setLayout(new javax.swing.BoxLayout(pnEditFields, javax.swing.BoxLayout.Y_AXIS));

        pnEditRateCode.setLayout(new java.awt.BorderLayout());

        lblRateCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRateCode.setText("Rate Code: ");
        pnEditRateCode.add(lblRateCode, java.awt.BorderLayout.WEST);

        pnEditRateCode.add(efRateCode, java.awt.BorderLayout.CENTER);

        pnEditFields.add(pnEditRateCode);

        pnEditUsked.setLayout(new java.awt.BorderLayout());

        pnEditUsked.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 0, 0, 0)));
        lblUsked.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsked.setText("Usked: ");
        lblUsked.setMaximumSize(new java.awt.Dimension(57, 14));
        lblUsked.setMinimumSize(new java.awt.Dimension(57, 14));
        lblUsked.setPreferredSize(new java.awt.Dimension(57, 14));
        pnEditUsked.add(lblUsked, java.awt.BorderLayout.WEST);

        pnEditUsked.add(efUsked, java.awt.BorderLayout.CENTER);

        pnEditFields.add(pnEditUsked);

        pnEdit2.add(pnEditFields);

        pnEditButton.setLayout(new java.awt.BorderLayout());

        pnEditButton.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 5, 1, 5)));
        pnEditButton.setMaximumSize(new java.awt.Dimension(120, 20000));
        pbAddUpdate.setText("Add");
        pbAddUpdate.setPreferredSize(new java.awt.Dimension(120, 23));
        pbAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbAddUpdateActionPerformed(evt);
            }
        });

        pnEditButton.add(pbAddUpdate, java.awt.BorderLayout.NORTH);

        pbCancel.setText("Cancel");
        pbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbCancelActionPerformed(evt);
            }
        });

        pnEditButton.add(pbCancel, java.awt.BorderLayout.SOUTH);

        pnEdit2.add(pnEditButton);

        pnEdit.add(pnEdit2);

        pnBottom.add(pnEdit, java.awt.BorderLayout.NORTH);

        getContentPane().add(pnBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void pbAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbAddUpdateActionPerformed
        if(efRateCode.getText().length() > 0){
            rate_code_update rcu = new rate_code_update();
            rcu.update(current_edit_id, efRateCode.getText(), efUsked.getText());
            
            try{
                myConnection.executeUpdate(rcu);
            }catch(Exception e){
                e.printStackTrace();
            }
            
            clearData();
            getData();
        }
    }//GEN-LAST:event_pbAddUpdateActionPerformed

    private void pbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbCancelActionPerformed
        if(pbCancel.getText().equalsIgnoreCase("Exit")){
            dispose();
        }else{
            clearData();
        }
    }//GEN-LAST:event_pbCancelActionPerformed
    
    /**
     * Checks all of the fields to see if they are null or not, reason why it checks for 4 is
     * that the social security field when trimmed returns the string "-  -" because of mask so
     * that is actually a blank value...kinda lame yes
     */
    public void checkFieldsAndSetCancelButton() {
        int length = 0;
        for (int i = 0; i < myComponents.size(); i++) {
            length += myComponents.get(i).getText().trim().length();
        }
        if (length == 4) {
            pbCancel.setText("Exit");
        } else {
            pbCancel.setText("Cancel");
        }
    }
    
    /**
     * Listener to check all text boxes components, check if all fields are empty
     * then change Cancel button to Exit, else change to Cancel if one field is empty...
     */
    private class myTextListener extends KeyAdapter {
        public myTextListener() {
            
        }
        
        public void keyReleased(KeyEvent e) {
            checkFieldsAndSetCancelButton();
        }
    }
        
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rate_code_edit().setVisible(true);
            }
        });
    }
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField efRateCode;
    private javax.swing.JTextField efUsked;
    private javax.swing.JLabel lblRateCode;
    private javax.swing.JLabel lblUsked;
    private javax.swing.JButton pbAddUpdate;
    private javax.swing.JButton pbCancel;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnEdit;
    private javax.swing.JPanel pnEdit2;
    private javax.swing.JPanel pnEditButton;
    private javax.swing.JPanel pnEditFields;
    private javax.swing.JPanel pnEditRateCode;
    private javax.swing.JPanel pnEditSpacer1;
    private javax.swing.JPanel pnEditUsked;
    private javax.swing.JPanel pnRateList;
    // End of variables declaration//GEN-END:variables
    
}
