/*
 * CertReportDialog.java
 *
 * Created on October 12, 2006, 12:02 PM
 */

package rmischedule.xprint.components;

import java.util.Calendar;
import rmischeduleserver.util.StaticDateTimeFunctions;
import rmischedule.components.jcalendar.JCalendarComboBox;

/**
 *
 * @author  shawn
 */
public class CertReportDialog extends javax.swing.JDialog {
    
    private String[] returnVals;
    private JCalendarComboBox startCombo, endCombo;
    
    /** Creates new form CertReportDialog */
    public CertReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.MONTH, cal.get(Calendar.MONTH)+1);
        cal.set(Calendar.DAY_OF_MONTH, 1);
        
        startCombo = new JCalendarComboBox(cal);
        cal.roll(Calendar.DAY_OF_MONTH, -1);
        endCombo = new JCalendarComboBox(cal);
        this.mainPanel.add(startCombo);
        this.mainPanel.add(endCombo);
    }
    
    public String[] getDatesFromDialog() {
        this.setVisible(true);
        return this.returnVals;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        mainPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        spacerPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter a date range for the report");
        setResizable(false);
        mainPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 8));

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 32, 24, 32));
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.X_AXIS));

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 4, 4));
        spacerPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel.add(spacerPanel);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-296)/2, (screenSize.height-173)/2, 296, 173);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.returnVals = null;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.returnVals = new String[2];
        this.returnVals[0] = StaticDateTimeFunctions.convertCalendarToDatabaseFormat(this.startCombo.getCalendar());
        this.returnVals[1] = StaticDateTimeFunctions.convertCalendarToDatabaseFormat(this.endCombo.getCalendar());
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertReportDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel spacerPanel;
    // End of variables declaration//GEN-END:variables
    
}
