/*
 * OptionComboBox.java
 *
 * Created on October 6, 2005, 12:14 PM
 */

package rmischedule.options.optionsgraphical;
import rmischedule.options.optiontypeclasses.*;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author  Ira Juneau
 */
public class OptionComboBox extends javax.swing.JPanel {
    
    private JComboBox myComboBox;
    private int access;
    private ComboOptionClass options;
    
    /** Creates new form OptionComboBox */
    public OptionComboBox(ComboOptionClass myOption, int requestedAccess) {
        initComponents();
        options = myOption;
        access = requestedAccess;
        DisplayNameLabel.setText(myOption.getMyDisplay());
        Vector myVector = ((Vector)myOption.read());
        String selectedObj = (String)myVector.get(0);
        myVector.remove(0);
        myComboBox = new JComboBox(myVector);
        myComboBox.setSelectedItem(selectedObj);
        add(myComboBox);
        myComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save();
            }
        });
    }
    
    public void save() {
        options.writeOption(myComboBox, access);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        DisplayNameLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(2147483647, 20));
        setPreferredSize(new java.awt.Dimension(179, 20));
        DisplayNameLabel.setMaximumSize(new java.awt.Dimension(300, 20));
        DisplayNameLabel.setMinimumSize(new java.awt.Dimension(300, 20));
        DisplayNameLabel.setOpaque(true);
        DisplayNameLabel.setPreferredSize(new java.awt.Dimension(300, 20));
        add(DisplayNameLabel, java.awt.BorderLayout.WEST);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisplayNameLabel;
    // End of variables declaration//GEN-END:variables
    
}
