/*
 * TrainingListPanel.java
 *
 * Created on October 17, 2005, 1:26 PM
 */

package rmischedule.schedule.components.graphiccomponents;
import rmischedule.components.graphicalcomponents.*;
import rmischedule.schedule.components.*;
import rmischedule.schedule.*;

import java.util.*;
/**
 *
 * @author  Ira Juneau
 */
public class TrainingListPanel extends javax.swing.JDialog {
    
    private SShift editingShift;
    private boolean isTrainerShift;
    private Schedule_View_Panel myParent;
    private TrainerPanel myTrainerPanel;
    private NewDShiftEdit myEditParent;
    private int trainerId;
    private String trainerName;
        
    /** Creates new form TrainingListPanel */
    public TrainingListPanel(java.awt.Frame parent, boolean modal, SShift editShift, boolean isTrainer, Schedule_View_Panel myPar, NewDShiftEdit myEditPar) {
        super(parent, modal);
        initComponents();
        myTrainerPanel = new TrainerPanel();
        myEditParent = myEditPar;
        mainPanel.add(myTrainerPanel);
        myParent = myPar;
        isTrainerShift = isTrainer;
        editingShift = editShift;
        if (isTrainer) {
            HeaderLabel.setText("Please select a person to train.");
        } else {
            HeaderLabel.setText("Please select trainer.");
        }
        showTrainingPanel();
    }
    
    private void showTrainingPanel() {
        Vector Employees = myParent.getEmployeeList();
        for (int i = 1; i < Employees.size(); i++) {
            int size = ((SEmployee)Employees.get(i)).getPhone().length();
            if (size > 11) {
                size = 11;
            }
            if (!((SEmployee)Employees.get(i)).isDeleted()) {
                GraphicalListComponent mySubComp = new GraphicalListComponent(((SEmployee)Employees.get(i)), myTrainerPanel, ((SEmployee)Employees.get(i)).getName(), ((SEmployee)Employees.get(i)).getPhone().substring(0,size));
                myTrainerPanel.add(mySubComp);
            }
        }
    }
    
    public class TrainerPanel extends GraphicalListParent {
        
        private long lastClicked = 0;
    
        public TrainerPanel() {
            
        }
        
        public void functionToRunOnSelectedShift(Object objectContained, boolean selected) {
            trainerId = ((SEmployee)objectContained).getId();
            trainerName = ((SEmployee)objectContained).getName();
            String trainingOrTrainer = ((SEmployee)objectContained).getName() + " is training " + editingShift.getEmployee().getName();
            if (isTrainerShift) {
                trainingOrTrainer = ((SEmployee)objectContained).getName() + " is being trained by " + editingShift.getEmployee().getName();
            }
            if ((System.currentTimeMillis() - lastClicked) < 1000) {
                myEditParent.setTrainerInfo(trainerId, trainerName);
                dispose();
            } else {
                lastClicked = System.currentTimeMillis();
            }
            
        }
    }
    
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        HeaderLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        ControlPanel = new javax.swing.JPanel();
        CANCEL = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        HeaderLabel.setText("jLabel1");
        getContentPane().add(HeaderLabel, java.awt.BorderLayout.NORTH);

        mainPanel.setLayout(new java.awt.GridLayout());

        mainPanel.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        ControlPanel.setLayout(new javax.swing.BoxLayout(ControlPanel, javax.swing.BoxLayout.X_AXIS));

        CANCEL.setText("CANCEL");
        CANCEL.setMaximumSize(new java.awt.Dimension(80, 23));
        CANCEL.setMinimumSize(new java.awt.Dimension(80, 23));
        CANCEL.setPreferredSize(new java.awt.Dimension(80, 23));
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        ControlPanel.add(CANCEL);

        ControlPanel.add(jPanel1);

        jButton2.setText("SELECT");
        jButton2.setMaximumSize(new java.awt.Dimension(80, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(80, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ControlPanel.add(jButton2);

        getContentPane().add(ControlPanel, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        myEditParent.setTrainerInfo(trainerId, trainerName);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        dispose();
    }//GEN-LAST:event_CANCELActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCEL;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    
}
