/*
 * OptionsPanel.java
 *
 * Created on November 9, 2004, 9:12 AM
 */

package rmischedule.options;

import java.util.*;
import rmischedule.components.*;
import rmischedule.components.Options;
import rmischedule.options.optionsgraphical.OptionCheckBox;
import rmischedule.options.optionsgraphical.OptionColorPanel;
import rmischedule.options.optionsgraphical.OptionIntegerBox;
import rmischedule.options.optionsgraphical.OptionTimeDisplay;
import rmischedule.options.optionsgraphical.OptionsIntBox;


/**
 *
 * @author  ira
 */
public class OptionsPanel extends javax.swing.JPanel {
     
    private String Category;
    private Vector Data;
    public OptionsWindow parent;

    
    /** Creates new form OptionsPanel */
    public OptionsPanel(String category, Vector data, OptionsWindow p) {
        initComponents();
        Data = data;
        Category = category;
        parent = p;
        
        addComponents();
    }
    
    private void addComponents() {
        for (int i = 0; i < Data.size(); i++) {
            if (Category.compareTo(((Options.options)(Data.elementAt(i))).category) == 0) {
                addIndividualComponent(i);
            }
        }
    }
    
    private void addIndividualComponent(int pos) {
        int type = ((Options.options)(Data.elementAt(pos))).type;
        String name = ((Options.options)(Data.elementAt(pos))).name;
        String display = ((Options.options)(Data.elementAt(pos))).display;
//        if (type == Options.OPTIONS_BOOLEAN) {
//            OptionCheckBox myCheck = new OptionCheckBox(display, name, parent.getOptions());
//            OptionDisplayPanel.add(myCheck);
//        } else if ((type== Options.OPTIONS_STRING)) {
//            OptionsIntBox myInt = new OptionsIntBox(display, name, parent.getOptions());
//            OptionDisplayPanel.add(myInt);
//        } else if ((type == Options.OPTIONS_INT)) {
//            OptionIntegerBox myInt = new OptionIntegerBox(display, name, parent.getOptions());
//            OptionDisplayPanel.add(myInt);
//        } else if (type == Options.OPTIONS_COLOR) {
//            OptionColorPanel myPanel = new OptionColorPanel(display, name, parent.getOptions());
//            OptionDisplayPanel.add(myPanel);
//        } else if (type == Options.OPTIONS_TIME) {
//            OptionTimeDisplay myTime = new OptionTimeDisplay(display, name, parent.getOptions(), this);
//            OptionDisplayPanel.add(myTime);
//        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        OptionDisplayPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        OptionDisplayPanel.setLayout(new javax.swing.BoxLayout(OptionDisplayPanel, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(OptionDisplayPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OptionDisplayPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
