/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Email_Templates.java
 *
 * Created on Jul 30, 2010, 3:03:51 PM
 */
package rmischedule.messaging.components;

import java.beans.PropertyVetoException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rmischedule.main.Main_Window;
import rmischedule.messaging.datacomponents.EmailTemplate;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.messaging.email.AddEmailTemplateQuery;
import rmischeduleserver.mysqlconnectivity.queries.messaging.email.GetEmailTemplates;
import rmischeduleserver.mysqlconnectivity.queries.messaging.email.RemoveEmailTemplateDB;

/**
 *
 * @author vnguyen
 */
public class Email_Templates extends javax.swing.JInternalFrame {

    private Email_Messaging parent;
    static EmailTemplate defaultChoice = new EmailTemplate("", "", "", "");

    /** Creates new form Email_Templates */
    private Email_Templates() {
        initComponents();
    }

    public Email_Templates(Email_Messaging parent) {
        this.parent = parent;
        initComponents();
        this.setSize(600, 350);
        this.setEnabled(true);
        try {
            this.setSelected(true);
            this.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Email_Templates.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.loadTemplates();
    }

    private void loadTemplates() {
        Record_Set rs = this.parent.getMyConnection().executeQuery(new GetEmailTemplates());
        Vector<EmailTemplate> templates = new Vector<EmailTemplate>();
        do {
            String id = rs.getString("message_email_template_id");
            String name = rs.getString("message_email_name");
            String subject = rs.getString("message_email_subject");
            String message = rs.getString("message_email_text");
            templates.add(new EmailTemplate(id, name, subject, message));
        } while (rs.moveNext());

        for (EmailTemplate t : templates) {
            this.jComboBoxTemplates.addItem(t);
        }
        this.jComboBoxTemplates.addItem(defaultChoice);
        this.jComboBoxTemplates.setSelectedItem(defaultChoice);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxTemplates = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSubject = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButtonCancel = new javax.swing.JButton();
        jButtonDone = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setInheritsPopupMenu(true);
        setLayer(1);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(100);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jComboBoxTemplates.setMaximumSize(new java.awt.Dimension(32767, 30));
        jComboBoxTemplates.setMinimumSize(new java.awt.Dimension(33, 30));
        jComboBoxTemplates.setPreferredSize(new java.awt.Dimension(33, 30));
        jComboBoxTemplates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTemplatesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTemplates);

        jButton1.setText("Delete");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(100, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel1.setText("Subject:");

        jLabel2.setText("Message:");

        jScrollPane1.setViewportView(jTextPane1);

        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonDone.setText(" Done ");
        jButtonDone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jButtonSave.setText(" Save ");
        jButtonSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonDone)
                    .addComponent(jButtonCancel))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-350)/2, 600, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        this.savingTemplate();
        this.settingTemplate();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        // TODO add your handling code here:
        this.settingTemplate();
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object o = this.jComboBoxTemplates.getSelectedItem();
        if (o instanceof EmailTemplate) {
            EmailTemplate temp = (EmailTemplate) o;
            if (!temp.equals(defaultChoice)) {
                this.jComboBoxTemplates.removeItem(temp);
                this.deleteFromDb(temp);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxTemplatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTemplatesActionPerformed
        // TODO add your handling code here:
        Object o = this.jComboBoxTemplates.getSelectedItem();
        if (o instanceof EmailTemplate) {
            EmailTemplate temp = (EmailTemplate) o;
            this.jTextFieldSubject.setText(temp.getSubject());
            this.jTextPane1.setText(temp.getMessage());
        }
    }//GEN-LAST:event_jComboBoxTemplatesActionPerformed
    private void deleteFromDb(EmailTemplate template) {
        this.parent.getMyConnection().executeQuery(new RemoveEmailTemplateDB(template.getId()));
    }

    private void settingTemplate() {
        String subject = this.jTextFieldSubject.getText();
        String message = this.jTextPane1.getText();
        this.parent.replaceWithTemplate(subject, message);
        this.parent.setEnabled(true);
        this.parent.setVisible(true);
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxTemplates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldSubject;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void savingTemplate() {
        //Save To DB
        String name = null;
        while (name == null || name.compareTo("") == 0) {
            name = JOptionPane.showInputDialog(Main_Window.parentOfApplication, "Please enter the name of ");
        }
        this.parent.getMyConnection().executeQuery(new AddEmailTemplateQuery(name, this.jTextFieldSubject.getText(), this.jTextPane1.getText()));
    }
}
