/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEditWageTypesDialog.java
 *
 * Created on Apr 15, 2011, 1:56:02 PM
 */

package rmischedule.billing;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import rmischedule.main.Main_Window;
import rmischeduleserver.control.BillingController;
import schedfoxlib.model.EmployeeWageTypes;

/**
 *
 * @author user
 */
public class AddEditWageTypesDialog extends javax.swing.JDialog {

    private EmployeeWageTypeModel wageModel;
    private EmployeeWageTypes employeeWageType;
    private String companyId;

    /** Creates new form AddEditWageTypesDialog */
    public AddEditWageTypesDialog(java.awt.Frame parent, boolean modal, String companyId) {
        super(parent, modal);
        wageModel = new EmployeeWageTypeModel();
        this.companyId = companyId;
        initComponents();
        this.clearData();
    }

    private void clearData() {
        this.employeeWageType = new EmployeeWageTypes();
        this.displayData();
    }

    private void displayData() {
        this.descriptionTxt.setText(employeeWageType.getDescription());
        this.oneTimeChk.setSelected(employeeWageType.getOneTime());

        BillingController billingController = BillingController.getInstance(this.companyId);
        try {
            wageModel.clearData();
            ArrayList<EmployeeWageTypes> types = billingController.getEmployeeWageTypes();
            for (int t = 0; t < types.size(); t++) {
                wageModel.addWageType(types.get(t));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Error gettting wage types");
        }
    }

    private EmployeeWageTypeModel getTableModel() {
        return this.wageModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descriptionTxt = new javax.swing.JTextField();
        oneTimeChk = new javax.swing.JCheckBox();
        saveBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wageTypeModel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(388, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Description");
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(70, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 16));
        jPanel3.add(jLabel1);

        descriptionTxt.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        jPanel3.add(descriptionTxt);

        oneTimeChk.setText("One Time?");
        oneTimeChk.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        oneTimeChk.setMaximumSize(new java.awt.Dimension(95, 18));
        oneTimeChk.setMinimumSize(new java.awt.Dimension(95, 18));
        oneTimeChk.setPreferredSize(new java.awt.Dimension(95, 18));
        jPanel3.add(oneTimeChk);

        saveBtn.setText("Save");
        saveBtn.setMaximumSize(new java.awt.Dimension(60, 28));
        saveBtn.setMinimumSize(new java.awt.Dimension(60, 28));
        saveBtn.setPreferredSize(new java.awt.Dimension(60, 28));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel3.add(saveBtn);

        getContentPane().add(jPanel3);

        jPanel1.setLayout(new java.awt.GridLayout());

        wageTypeModel.setModel(getTableModel());
        wageTypeModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wageTypeModelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(wageTypeModel);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(closeBtn);

        getContentPane().add(jPanel2);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-396)/2, (screenSize.height-231)/2, 396, 231);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        employeeWageType.setDescription(this.descriptionTxt.getText());
        employeeWageType.setOneTime(this.oneTimeChk.isSelected());
        BillingController billingController = BillingController.getInstance(this.companyId);
        try {
            billingController.saveEmployeeWageType(employeeWageType);
            this.clearData();
            JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Data Saved!",
                    "Saved", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Could not save data!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void wageTypeModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wageTypeModelMouseClicked
        if (evt.getClickCount() > 1) {
            this.employeeWageType = wageModel.getTypeAt(wageTypeModel.getSelectedRow());
            this.displayData();
        }
    }//GEN-LAST:event_wageTypeModelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox oneTimeChk;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable wageTypeModel;
    // End of variables declaration//GEN-END:variables

}
