/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEditSalesTaxDialog.java
 *
 * Created on Mar 16, 2011, 2:26:36 PM
 */

package rmischedule.billing;

import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import rmischedule.data_connection.Connection;
import rmischedule.main.Main_Window;
import schedfoxlib.model.util.Record_Set;
import schedfoxlib.model.SalesTax;
import rmischeduleserver.mysqlconnectivity.queries.billing.get_all_sales_tax_query;
import rmischeduleserver.mysqlconnectivity.queries.billing.save_sales_tax_query;

/**
 *
 * @author user
 */
public class AddEditSalesTaxDialog extends javax.swing.JDialog {

    private SalesTaxModel salesModel = new SalesTaxModel();
    private int companyId;

    /** Creates new form AddEditSalesTaxDialog */
    public AddEditSalesTaxDialog(java.awt.Frame parent, boolean modal, int companyId) {
        super(parent, modal);
        initComponents();
        this.companyId = companyId;
        this.loadData();
    }

    private void clearData() {
        this.idField.setText("");
        this.exportTxt.setText("");
        this.descriptionTxt.setText("");
        this.salesRateTxt.setText("");
    }

    private SalesTaxModel getSalesTaxModel() {
        return this.salesModel;
    }

    public void loadData() {
        get_all_sales_tax_query salesTaxQuery = new get_all_sales_tax_query();
        salesTaxQuery.setPreparedStatement(new Object[]{});
        Connection myConn = new Connection();
        myConn.myCompany = companyId + "";
        myConn.prepQuery(salesTaxQuery);
        Record_Set rst = myConn.executeQuery(salesTaxQuery);
        salesModel.clearData();
        for (int r = 0; r < rst.length(); r++) {
            salesModel.addSalesTax(new SalesTax(rst));
            rst.moveNext();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descriptionTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salesRateTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        exportTxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTaxTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();

        idField.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMinimumSize(new java.awt.Dimension(0, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(386, 100));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Description");
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(70, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 16));
        jPanel6.add(jLabel1);

        descriptionTxt.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        jPanel6.add(descriptionTxt);

        jPanel3.add(jPanel6);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Sales Tax");
        jLabel2.setMaximumSize(new java.awt.Dimension(70, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(70, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 16));
        jPanel5.add(jLabel2);

        salesRateTxt.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        jPanel5.add(salesRateTxt);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Export ID");
        jLabel3.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel5.add(jLabel3);

        exportTxt.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        jPanel5.add(exportTxt);

        jPanel3.add(jPanel5);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 2));

        saveBtn.setText("Save Sales Tax");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel7.add(saveBtn);

        jPanel3.add(jPanel7);

        getContentPane().add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        salesTaxTable.setModel(getSalesTaxModel());
        salesTaxTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTaxTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salesTaxTable);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(386, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(closeBtn);

        getContentPane().add(jPanel1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-394)/2, (screenSize.height-326)/2, 394, 326);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            SalesTax newTax = new SalesTax();
            try {
                newTax.setSalesTaxId(Integer.parseInt(idField.getText()));
            } catch (Exception e) {}
            newTax.setExportId(exportTxt.getText().trim());
            newTax.setSalesTax(descriptionTxt.getText().trim());
            newTax.setSalesTaxRate(new BigDecimal(Double.parseDouble(salesRateTxt.getText())));
            save_sales_tax_query saveSalesQuery = new save_sales_tax_query();
            saveSalesQuery.update(newTax);
            Connection myConn = new Connection();
            myConn.myCompany = this.companyId + "";
            myConn.prepQuery(saveSalesQuery);
            myConn.executeUpdate(saveSalesQuery);
            this.loadData();
            this.clearData();
            JOptionPane.showMessageDialog(Main_Window.parentOfApplication,
                    "Saved Data!", "Saved!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Main_Window.parentOfApplication,
                    "Please enter a valid sales tax rate.", "Invalid Rate",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void salesTaxTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTaxTableMouseClicked
        if (evt.getClickCount() > 1) {
            SalesTax selectedSalesTax = salesModel.getSalesTax(salesTaxTable.getSelectedRow());
            this.idField.setText(selectedSalesTax.getSalesTaxId().toString());
            this.exportTxt.setText(selectedSalesTax.getExportId());
            this.descriptionTxt.setText(selectedSalesTax.getSalesTax());
            this.salesRateTxt.setText(selectedSalesTax.getSalesTaxRate().toString());
        }
    }//GEN-LAST:event_salesTaxTableMouseClicked

    private class SalesTaxModel extends AbstractTableModel {

        private ArrayList<SalesTax> salesTax;

        public SalesTaxModel() {
            salesTax = new ArrayList<SalesTax>();
        }

        public void clearData() {
            salesTax.clear();
            super.fireTableDataChanged();
        }

        public void addSalesTax(SalesTax tax) {
            this.salesTax.add(tax);
            super.fireTableDataChanged();
        }

        public SalesTax getSalesTax(int row) {
            return salesTax.get(row);
        }

        @Override
        public String getColumnName(int column) {
            if (column == 0) {
                return "Name";
            } else if (column == 1) {
                return "Rate";
            } else if (column == 2) {
                return "Export ID";
            }
            return "";
        }

        public int getRowCount() {
            return salesTax.size();
        }

        public int getColumnCount() {
            return 3;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            SalesTax myTax = salesTax.get(rowIndex);
            if (columnIndex == 0) {
                return myTax.getSalesTax();
            } else if (columnIndex == 1) {
                return myTax.getSalesTaxRate();
            } else if (columnIndex == 2) {
                return myTax.getExportId();
            }
            return "";
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JTextField exportTxt;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField salesRateTxt;
    private javax.swing.JTable salesTaxTable;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

}
