/*
 * HistoryDetailPanel.java
 *
 * Created on December 12, 2005, 1:40 PM
 */

package rmischedule.schedule.history;
import schedfoxlib.model.util.Record_Set;
import rmischedule.components.graphicalcomponents.*;
import rmischedule.schedule.components.*;
import java.awt.*;
import rmischeduleserver.mysqlconnectivity.queries.schedule_data.history.*;
import rmischeduleserver.data_connection_types.*;
import java.util.*;
import javax.swing.*;
import rmischeduleserver.mysqlconnectivity.queries.rate_codes.rate_code_list_query;
/**
 *
 * @author  Ira Juneau
 */
public class HistoryDetailPanel extends javax.swing.JPanel {
    
    public NewDShiftEdit myParent;
    private ArrayList<IndividualHistoryColumnPanel> myHistories;
    private PrettyTitleBar myDataPanel;
    private PrettyTitleBar myColumnListPanel;
    
    private HashMap<Integer, String> rateCodes = new HashMap<Integer, String>();
    
    /** Creates new form HistoryDetailPanel */
    public HistoryDetailPanel(NewDShiftEdit myparent) {
        initComponents();
        myParent = myparent;
        //TitlePanel.add(new PrettyTitleBar(new Color(4,43,130), new Color(198,213,247)));
        PrettyTitleBar TitleBar = new PrettyTitleBar(new Color(168,183,217), new Color(240,242,255), "", "");
        TitlePanel.add(TitleBar);
        TitleBar.add(new JLabel("Past"));
        JPanel myTransparentPanel = new JPanel();
        myTransparentPanel.setOpaque(false);
        TitleBar.add(myTransparentPanel);
        TitleBar.add(new JLabel("Current"));
        myDataPanel = new PrettyTitleBar(new Color(168,183,217), new Color(240,242,255), "", "");
        myColumnListPanel = new PrettyTitleBar(new Color(168,183,217), new Color(240,242,255), "", "");
        myColumnListPanel.add(DataList);
        mySplitPane.setLeftComponent(myColumnListPanel);
        
        loadRateCodes();
        
        DataPanel.add(myDataPanel);
        myHistories = new ArrayList();
        if (!myParent.svParent.shouldMarkUnconShifts()) {
            Confirmed.setVisible(false);
        }
    }
    
    private void loadRateCodes() {
        rate_code_list_query rclq = new rate_code_list_query();
        
        Record_Set myRs = new Record_Set();        

        try{
            myRs = myParent.svParent.getConnection().executeQuery(rclq);
            for (int r = 0; r < myRs.length(); r++) {
                rateCodes.put(myRs.getInt("id"), myRs.getString("name"));
                myRs.moveNext();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * Given the current shifts shiftId
     */
    public void populateDataWithGivenGroup(String shiftId) {
        retrieveHistoryForGivenGroup myRetrievalQuery = new retrieveHistoryForGivenGroup();
        myRetrievalQuery.setPreparedStatement(new Object[]{Integer.parseInt(shiftId)});
        Record_Set myHistory = new Record_Set();
        try {
            myHistory = myParent.svParent.getConnection().executeQuery(myRetrievalQuery);
        } catch (Exception e) {}
        myHistories.clear();
        myDataPanel.removeAll();
        for (int i = 0; i < myHistory.length(); i++) {
            IndividualHistoryColumnPanel myNewPanel = new IndividualHistoryColumnPanel(myHistory, this);
            myDataPanel.add(myNewPanel);
            myHistories.add(myNewPanel);
            myHistory.moveNext();
        }
        for (int i = 1; i < myHistories.size(); i++) {
            myHistories.get(i).compareThisAndOtherPanelAndHighlightChangedFields(myHistories.get(i - 1), Color.RED);
        }
        myScrollPane.getViewport().scrollRectToVisible(new Rectangle(myDataPanel.getBounds().width, 0, myScrollPane.getWidth(), myScrollPane.getHeight()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataList = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Confirmed = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        mySplitPane = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        myScrollPane = new javax.swing.JScrollPane();
        DataPanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();

        DataList.setBackground(new java.awt.Color(168, 183, 217));
        DataList.setOpaque(false);
        DataList.setLayout(new javax.swing.BoxLayout(DataList, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(168, 183, 217));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        DataList.add(jPanel1);

        jPanel4.setMaximumSize(new java.awt.Dimension(20000, 19));
        jPanel4.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel3.setText("Time Changed");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel4.add(jLabel3);

        DataList.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel5.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel4.setText("User Changed");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel5.add(jLabel4);

        DataList.add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel6.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel5.setText("Employee");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel6.add(jLabel5);

        DataList.add(jPanel6);

        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel7.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel6.setText("Client");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel7.add(jLabel6);

        DataList.add(jPanel7);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel8.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel7.setText("Start Time");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel8.add(jLabel7);

        DataList.add(jPanel8);

        jPanel9.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel9.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel8.setText("End Time");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel9.add(jLabel8);

        DataList.add(jPanel9);

        jPanel14.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel14.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel14.setOpaque(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel11.setText("Start Date");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel14.add(jLabel11);

        DataList.add(jPanel14);

        jPanel15.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel15.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel15.setOpaque(false);
        jPanel15.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel12.setText("End Date");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel15.add(jLabel12);

        DataList.add(jPanel15);

        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel10.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel9.setText("Shift Billable");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel10.add(jLabel9);

        DataList.add(jPanel10);

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel11.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel10.setText("Shift Payable");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel11.add(jLabel10);

        DataList.add(jPanel11);

        Confirmed.setMaximumSize(new java.awt.Dimension(32767, 17));
        Confirmed.setMinimumSize(new java.awt.Dimension(10, 17));
        Confirmed.setOpaque(false);
        Confirmed.setPreferredSize(new java.awt.Dimension(10, 17));
        Confirmed.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Shift Confirmed");
        Confirmed.add(jLabel1);

        DataList.add(Confirmed);

        jPanel16.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel16.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(10, 19));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel13.setText("Shift Recon");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel16.add(jLabel13);

        DataList.add(jPanel16);

        jPanel12.setBackground(new java.awt.Color(168, 183, 217));
        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel12.setMinimumSize(new java.awt.Dimension(58, 19));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(58, 19));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel14.setText("Bill Code");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(150, 150, 150)));
        jPanel12.add(jLabel14);

        DataList.add(jPanel12);

        jPanel17.setBackground(new java.awt.Color(168, 183, 217));
        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.GridLayout());
        DataList.add(jPanel17);

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                runOnFocusGained(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0));

        mySplitPane.setDividerLocation(100);
        mySplitPane.setDividerSize(1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        TitlePanel.setMaximumSize(new java.awt.Dimension(32767, 18));
        TitlePanel.setMinimumSize(new java.awt.Dimension(0, 18));
        TitlePanel.setPreferredSize(new java.awt.Dimension(0, 18));
        TitlePanel.setLayout(new java.awt.GridLayout(1, 0));
        jPanel2.add(TitlePanel);

        jPanel3.setLayout(new java.awt.CardLayout());

        myScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        myScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        DataPanel.setLayout(new java.awt.GridLayout(1, 0));
        myScrollPane.setViewportView(DataPanel);

        jPanel3.add(myScrollPane, "dataCard");
        jPanel3.add(jPanel13, "loadingCard");

        jPanel2.add(jPanel3);

        mySplitPane.setRightComponent(jPanel2);

        add(mySplitPane);
    }// </editor-fold>//GEN-END:initComponents

    private void runOnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_runOnFocusGained
        try {
            populateDataWithGivenGroup(myParent.getEditingShift().getShiftId());
        } catch (Exception e) {}
    }//GEN-LAST:event_runOnFocusGained
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Confirmed;
    private javax.swing.JPanel DataList;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane myScrollPane;
    private javax.swing.JSplitPane mySplitPane;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the rateCodes
     */
    public HashMap<Integer, String> getRateCodes() {
        return rateCodes;
    }

    /**
     * @param rateCodes the rateCodes to set
     */
    public void setRateCodes(HashMap<Integer, String> rateCodes) {
        this.rateCodes = rateCodes;
    }
    
}
