/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CatalogDisplayPanel.java
 *
 * Created on Nov 17, 2010, 3:14:59 PM
 */
package rmischedule.training;

import com.creamtec.ajaxswing.AjaxSwingConstants;
import com.creamtec.ajaxswing.AjaxSwingManager;
import com.creamtec.ajaxswing.core.AjaxSwingProperties;
import com.creamtec.ajaxswing.core.ClientAgent;
import com.creamtec.ajaxswing.rendering.html.positioned.AjaxPage;
import java.awt.Desktop;
import java.net.URL;
import rmischedule.main.Main_Window;
import rmischeduleserver.IPLocationFile;
import schedfoxlib.model.Client;
import schedfoxlib.model.EmployeeTest;

/**
 *
 * @author user
 */
public class CatalogDisplayPanel extends javax.swing.JPanel {

    private EmployeeTest catalog;
    private int client_id;

    /** Creates new form CatalogDisplayPanel */
    public CatalogDisplayPanel(EmployeeTest catalog, int client_id) {
        initComponents();

        this.catalog = catalog;
        this.client_id = client_id;

        catalogTitleLabel.setText(catalog.getEmployeeTestDisplay());
        if (Main_Window.isEmployeeLoggedIn()) {
            viewFileBtn.setText("Take");
            double score=catalog.getEmployeeTestScore();
            if(catalog.isDefault_to_na())
                scoreLabel.setText("Passed");
            if(!(score==0)){
                scoreLabel.setText(String.valueOf(score));
                viewFileBtn.setText("Re-Take");
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        catalogTitleLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        viewFileBtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(200000, 35));
        setMinimumSize(new java.awt.Dimension(204, 35));
        setPreferredSize(new java.awt.Dimension(204, 35));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(190, 39));
        jPanel1.setMinimumSize(new java.awt.Dimension(140, 38));
        jPanel1.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 9));
        jPanel2.setMinimumSize(new java.awt.Dimension(10, 8));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel1.add(jPanel2);

        catalogTitleLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        catalogTitleLabel.setMaximumSize(new java.awt.Dimension(190, 30));
        catalogTitleLabel.setMinimumSize(new java.awt.Dimension(140, 30));
        catalogTitleLabel.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(catalogTitleLabel);

        add(jPanel1);

        scoreLabel.setMaximumSize(new java.awt.Dimension(50, 20));
        scoreLabel.setPreferredSize(new java.awt.Dimension(50, 20));
        add(scoreLabel);

        viewFileBtn.setText("View");
        viewFileBtn.setMaximumSize(new java.awt.Dimension(80, 29));
        viewFileBtn.setMinimumSize(new java.awt.Dimension(80, 29));
        viewFileBtn.setPreferredSize(new java.awt.Dimension(80, 29));
        viewFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFileBtnActionPerformed(evt);
            }
        });
        add(viewFileBtn);
    }// </editor-fold>//GEN-END:initComponents

    private void viewFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFileBtnActionPerformed
        try {
            String url = "";
            if (Main_Window.isClientLoggedIn()) {
                url = IPLocationFile.getTRAINING_IP() + ":8080/TrainingLinkServer/ProcessClientView?client_id=" +
                    client_id + "&test_id=" + this.catalog.getEmployeeTestId();
            } else {
                url = IPLocationFile.getTRAINING_IP() + ":8080/TrainingLinkServer/ProcessEmployeeView?employee_id=" +
                    Main_Window.parentOfApplication.myUser.getUserId() + "&test_id=" + this.catalog.getEmployeeTestId();
            }
            if (AjaxSwingManager.isAjaxSwingRunning()) {
                AjaxPage ajaxPage = (AjaxPage) ClientAgent.getCurrentInstance().getHTMLPage();
                ajaxPage.getAjaxResponse().appendScript("window.open('" + url + "','_newtab')");
            } else {
                Desktop desktop = Desktop.getDesktop();
                desktop.browse(new URL(url).toURI());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewFileBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catalogTitleLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton viewFileBtn;
    // End of variables declaration//GEN-END:variables
}
