/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AvailIconContainer.java
 *
 * Created on Jun 27, 2011, 1:26:01 PM
 */

package rmischedule.employee.components.xavailability;

import java.awt.Color;
import javax.swing.ImageIcon;
import rmischedule.data_connection.Connection;
import rmischedule.main.Main_Window;

/**
 *
 * @author user
 */
public class AvailIconContainer extends javax.swing.JPanel {

    private xAvailDragDropIcon xDragDropIcon;

    private String myVal;
    private String myVal2;
    private xTempAvailabilityPanel employeeEdit;
    private Integer typeEmployee;

    private String title;

    /** Creates new form AvailIconContainer */
    public AvailIconContainer(xFormInterface myParent, String title, Object objToPass, Object objToPass2,
            ImageIcon myIcon, ImageIcon myIcon2, Color myBackground, xTempAvailabilityPanel employeeEdit,
            Integer timeOffType, Integer timeOffType2) {
        myVal = (String)objToPass;
        myVal2 = (String)objToPass2;
        this.title = title;

        initComponents();

        adjustBtn.setVisible(false);
        this.employeeEdit = employeeEdit;
        this.typeEmployee = timeOffType;

        xDragDropIcon = new xAvailDragDropIcon(myParent, timeOffType, myIcon, myBackground);

        try {
            iconLabel1.setText((String)objToPass);
        } catch (Exception e) {}
        iconPanel1.add(xDragDropIcon);

        if (objToPass2 != null) {
            iconLabel2.setText((String)objToPass2);
            xAvailDragDropIcon xDragDropIcon2 = new xAvailDragDropIcon(myParent, timeOffType2, myIcon2, myBackground);
            iconPanel2.add(xDragDropIcon2);
        }

        

        //adjustBtn.setVisible(false);

        subtotalLabel.setVisible(false);
        adjustmentLabel.setVisible(false);
    }

    public String getBorderTitle() {
        return this.title;
    }

    public void setCount(double count, int adjustment) {
        try {
            titleLabel.setText(this.title + " (" + (count + adjustment) + ")");
            if (Main_Window.parentOfApplication.isUserAMemberOfGroups(new Connection(), "ADMIN", "Corporate User")) {
                adjustBtn.setVisible(true);
            }
        } catch (Exception e) {}
    }

    /**
     * Returns the same val that will be passed via the drop method...
     */
    public Object getValue() {
        return xDragDropIcon.getValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtotalLabel = new javax.swing.JLabel();
        adjustmentLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        adjustBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        panelOne = new javax.swing.JPanel();
        firstRow = new javax.swing.JPanel();
        iconPanel1 = new javax.swing.JPanel();
        secondRow = new javax.swing.JPanel();
        iconLabel1 = new javax.swing.JLabel();
        panelTwo = new javax.swing.JPanel();
        firstRow2 = new javax.swing.JPanel();
        iconPanel2 = new javax.swing.JPanel();
        secondRow2 = new javax.swing.JPanel();
        iconLabel2 = new javax.swing.JLabel();

        subtotalLabel.setMaximumSize(new java.awt.Dimension(30, 40));
        subtotalLabel.setMinimumSize(new java.awt.Dimension(20, 40));
        subtotalLabel.setPreferredSize(new java.awt.Dimension(25, 40));

        adjustmentLabel.setMaximumSize(new java.awt.Dimension(30, 40));
        adjustmentLabel.setMinimumSize(new java.awt.Dimension(20, 40));
        adjustmentLabel.setPreferredSize(new java.awt.Dimension(25, 40));

        totalLabel.setMaximumSize(new java.awt.Dimension(30, 40));
        totalLabel.setMinimumSize(new java.awt.Dimension(20, 40));
        totalLabel.setPreferredSize(new java.awt.Dimension(25, 40));

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(32767, 100));
        setMinimumSize(new java.awt.Dimension(102, 75));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(102, 75));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        topPanel.setOpaque(false);
        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        titleLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        titleLabel.setText(getBorderTitle());
        titleLabel.setMaximumSize(new java.awt.Dimension(120, 16));
        titleLabel.setMinimumSize(new java.awt.Dimension(90, 16));
        titleLabel.setPreferredSize(new java.awt.Dimension(100, 16));
        topPanel.add(titleLabel);

        adjustBtn.setText("Adjust");
        adjustBtn.setMaximumSize(new java.awt.Dimension(62, 20));
        adjustBtn.setMinimumSize(new java.awt.Dimension(62, 20));
        adjustBtn.setPreferredSize(new java.awt.Dimension(62, 20));
        adjustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjustBtnActionPerformed(evt);
            }
        });
        topPanel.add(adjustBtn);

        add(topPanel);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.GridLayout(1, 2));

        panelOne.setOpaque(false);
        panelOne.setLayout(new javax.swing.BoxLayout(panelOne, javax.swing.BoxLayout.Y_AXIS));

        firstRow.setMaximumSize(new java.awt.Dimension(32767, 32));
        firstRow.setMinimumSize(new java.awt.Dimension(42, 32));
        firstRow.setOpaque(false);
        firstRow.setPreferredSize(new java.awt.Dimension(100, 32));

        iconPanel1.setMaximumSize(new java.awt.Dimension(40, 32));
        iconPanel1.setMinimumSize(new java.awt.Dimension(32, 32));
        iconPanel1.setOpaque(false);
        iconPanel1.setPreferredSize(new java.awt.Dimension(32, 32));
        iconPanel1.setLayout(new java.awt.GridLayout(1, 0));
        firstRow.add(iconPanel1);

        panelOne.add(firstRow);

        secondRow.setMaximumSize(new java.awt.Dimension(32767, 18));
        secondRow.setMinimumSize(new java.awt.Dimension(5, 18));
        secondRow.setOpaque(false);
        secondRow.setPreferredSize(new java.awt.Dimension(100, 18));
        secondRow.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        iconLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        iconLabel1.setMaximumSize(new java.awt.Dimension(41000, 30));
        secondRow.add(iconLabel1);

        panelOne.add(secondRow);

        mainPanel.add(panelOne);

        panelTwo.setOpaque(false);
        panelTwo.setLayout(new javax.swing.BoxLayout(panelTwo, javax.swing.BoxLayout.Y_AXIS));

        firstRow2.setMaximumSize(new java.awt.Dimension(32767, 32));
        firstRow2.setMinimumSize(new java.awt.Dimension(42, 32));
        firstRow2.setOpaque(false);
        firstRow2.setPreferredSize(new java.awt.Dimension(42, 32));

        iconPanel2.setMaximumSize(new java.awt.Dimension(40, 32));
        iconPanel2.setMinimumSize(new java.awt.Dimension(32, 32));
        iconPanel2.setOpaque(false);
        iconPanel2.setPreferredSize(new java.awt.Dimension(32, 32));
        iconPanel2.setLayout(new java.awt.GridLayout(1, 0));
        firstRow2.add(iconPanel2);

        panelTwo.add(firstRow2);

        secondRow2.setMaximumSize(new java.awt.Dimension(32767, 18));
        secondRow2.setMinimumSize(new java.awt.Dimension(5, 18));
        secondRow2.setOpaque(false);
        secondRow2.setPreferredSize(new java.awt.Dimension(5, 18));
        secondRow2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        iconLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        iconLabel2.setMaximumSize(new java.awt.Dimension(41000, 30));
        secondRow2.add(iconLabel2);

        panelTwo.add(secondRow2);

        mainPanel.add(panelTwo);

        add(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void adjustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjustBtnActionPerformed
        EditAvailabilityAdjustmentDialog editAvailDialog =
                new EditAvailabilityAdjustmentDialog(Main_Window.parentOfApplication, this.employeeEdit,
                typeEmployee, true);
        editAvailDialog.setVisible(true);
    }//GEN-LAST:event_adjustBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adjustBtn;
    private javax.swing.JLabel adjustmentLabel;
    private javax.swing.JPanel firstRow;
    private javax.swing.JPanel firstRow2;
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JLabel iconLabel2;
    private javax.swing.JPanel iconPanel1;
    private javax.swing.JPanel iconPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelOne;
    private javax.swing.JPanel panelTwo;
    private javax.swing.JPanel secondRow;
    private javax.swing.JPanel secondRow2;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

}
