/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AvailDayStats.java
 *
 * Created on Jul 12, 2011, 12:00:13 PM
 */
package rmischedule.employee.components.xavailability;

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.text.SimpleDateFormat;
import schedfoxlib.model.AvailabilityInterface;
import schedfoxlib.model.User;

/**
 *
 * @author user
 */
public class AvailDayStats extends javax.swing.JPanel {

    private SimpleDateFormat myFormat = new SimpleDateFormat("MM/dd/yyyy");
    
    /** Creates new form AvailDayStats */
    public AvailDayStats() {
        initComponents();
    }

    /**
     * Displaying statistics for the availability.
     * @param avail
     */
    public void displayStats(AvailabilityInterface avail) {
        try {
            User createdUser = avail.getUserCreatedBy("");

            if (createdUser == null) {
                requestedByLabel.setText("");
            } else {
                requestedByLabel.setText(createdUser.getUserFullName());
            }
            approvedByLabel.setText("");
            if (avail.getHoursCompensated() != null) {
                hoursCompensatedLabel.setText(avail.getHoursCompensated().doubleValue() + "");
            } else {
                hoursCompensatedLabel.setText("");
            }
            if (avail.getDateRequested() != null) {
                dateRequestedLabel.setText(myFormat.format(avail.getDateRequested()));
            } else {
                dateRequestedLabel.setText("");
            }
        } catch (Exception e) {
            requestedByLabel.setText("");
            approvedByLabel.setText("");
            dateRequestedLabel.setText("");
            hoursCompensatedLabel.setText("");
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setComposite(AlphaComposite.SrcOver.derive(0.75f));
        super.paintComponent(g2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        requestedByLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateRequestedLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        approvedByLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hoursCompensatedLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2)));
        setMaximumSize(new java.awt.Dimension(706, 130));
        setMinimumSize(new java.awt.Dimension(105, 125));
        setPreferredSize(new java.awt.Dimension(105, 130));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 10));
        jLabel1.setText("Requested By:");
        add(jLabel1);

        requestedByLabel.setFont(new java.awt.Font("sansserif", 3, 10));
        requestedByLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        requestedByLabel.setText("jLabel2");
        requestedByLabel.setMaximumSize(new java.awt.Dimension(700, 16));
        add(requestedByLabel);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 10));
        jLabel3.setText("Requested On:");
        add(jLabel3);

        dateRequestedLabel.setFont(new java.awt.Font("sansserif", 3, 10));
        dateRequestedLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateRequestedLabel.setText("jLabel4");
        dateRequestedLabel.setMaximumSize(new java.awt.Dimension(700, 16));
        add(dateRequestedLabel);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 10));
        jLabel5.setText("Approved By:");
        add(jLabel5);

        approvedByLabel.setFont(new java.awt.Font("sansserif", 3, 10));
        approvedByLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        approvedByLabel.setText("jLabel6");
        approvedByLabel.setMaximumSize(new java.awt.Dimension(700, 16));
        add(approvedByLabel);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 10));
        jLabel6.setText("Hours Compensated");
        add(jLabel6);

        hoursCompensatedLabel.setFont(new java.awt.Font("sansserif", 3, 10));
        hoursCompensatedLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hoursCompensatedLabel.setText("jLabel6");
        hoursCompensatedLabel.setMaximumSize(new java.awt.Dimension(700, 16));
        add(hoursCompensatedLabel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel approvedByLabel;
    private javax.swing.JLabel dateRequestedLabel;
    private javax.swing.JLabel hoursCompensatedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel requestedByLabel;
    // End of variables declaration//GEN-END:variables
}
