/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimeOffCalculationPanel.java
 *
 * Created on Jun 8, 2011, 4:13:04 PM
 */

package rmischedule.employee.components.xavailability;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import schedfoxlib.model.TimeOffCalc;

/**
 *
 * @author user
 */
public class TimeOffCalculationPanel extends javax.swing.JPanel {

    private SimpleDateFormat myFormat = new SimpleDateFormat("MM/dd/yyyy");
    private TimeOffCalc timeCalc;

    /** Creates new form TimeOffCalculationPanel */
    public TimeOffCalculationPanel(TimeOffCalc timeCalc, 
            String companyId) {
        this.timeCalc = timeCalc;
        initComponents();
        

//        rangeDataLabel.setText(timeCalc.getDays() + " days per " + timeCalc.getTimeOffInterval() + " ");
        timeEarnedLabel.setText(timeCalc.getDaysAccrued() + " days earned. (" + timeCalc.getHoursAccrued() + " hours)");


        String[] avail = timeCalc.getDatesTaken().split(",");
        try {
            int added = 0;
            for (int a = avail.length - 1; a >= 0; a--) {
                if (avail[a].trim().length() > 0) {
                    panelTimeOff.add(new TimeOffTakenPanel(avail[a]));
                    added++;
                }
            }
            lastPanel.setPreferredSize(new Dimension(this.getWidth(), added * 16));
            lastPanel.setMinimumSize(new Dimension(this.getWidth(), added * 16));
            this.setPreferredSize(new Dimension(this.getWidth(), (added * 16) + 120));

            int totalCount = timeCalc.getDaysAccrued() - added;
            if (totalCount < 0) {
                totalCount = 0;
            }
            
            totalLabel.setText(totalCount + " " + (timeCalc.isIsExpired() ? "(Expired)" : ""));
            revalidate();
        } catch (Exception e) {}
        
    }

    private String getBorderTitle() {
        return myFormat.format(timeCalc.getStartDate()) +
                " to " + myFormat.format(timeCalc.getEndDate());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTwo = new javax.swing.JPanel();
        timeEarnedLabel = new javax.swing.JLabel();
        lastPanel = new javax.swing.JPanel();
        panelTimeOff = new javax.swing.JPanel();
        panelThree = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), getBorderTitle()));
        setMaximumSize(new java.awt.Dimension(200000, 9000));
        setMinimumSize(new java.awt.Dimension(128, 90));
        setPreferredSize(new java.awt.Dimension(255, 90));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelTwo.setMaximumSize(new java.awt.Dimension(2000, 30));
        panelTwo.setMinimumSize(new java.awt.Dimension(85, 24));
        panelTwo.setPreferredSize(new java.awt.Dimension(85, 24));
        panelTwo.setLayout(new javax.swing.BoxLayout(panelTwo, javax.swing.BoxLayout.LINE_AXIS));

        timeEarnedLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        timeEarnedLabel.setForeground(new java.awt.Color(0, 102, 0));
        timeEarnedLabel.setMaximumSize(new java.awt.Dimension(400, 26));
        timeEarnedLabel.setMinimumSize(new java.awt.Dimension(150, 16));
        timeEarnedLabel.setPreferredSize(new java.awt.Dimension(150, 16));
        panelTwo.add(timeEarnedLabel);

        add(panelTwo);

        lastPanel.setLayout(new java.awt.GridLayout(1, 0));

        panelTimeOff.setMaximumSize(new java.awt.Dimension(10000, 10000));
        panelTimeOff.setMinimumSize(new java.awt.Dimension(100, 0));
        panelTimeOff.setPreferredSize(new java.awt.Dimension(227, 0));
        panelTimeOff.setLayout(new javax.swing.BoxLayout(panelTimeOff, javax.swing.BoxLayout.Y_AXIS));
        lastPanel.add(panelTimeOff);

        add(lastPanel);

        panelThree.setMaximumSize(new java.awt.Dimension(2000, 30));
        panelThree.setMinimumSize(new java.awt.Dimension(85, 24));
        panelThree.setPreferredSize(new java.awt.Dimension(85, 24));
        panelThree.setLayout(new javax.swing.BoxLayout(panelThree, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel1.setText("Totals:");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 16));
        panelThree.add(jLabel1);

        totalLabel.setFont(new java.awt.Font("sansserif", 1, 12));
        totalLabel.setMaximumSize(new java.awt.Dimension(150, 26));
        totalLabel.setMinimumSize(new java.awt.Dimension(150, 16));
        totalLabel.setPreferredSize(new java.awt.Dimension(150, 16));
        panelThree.add(totalLabel);

        add(panelThree);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel lastPanel;
    private javax.swing.JPanel panelThree;
    private javax.swing.JPanel panelTimeOff;
    private javax.swing.JPanel panelTwo;
    private javax.swing.JLabel timeEarnedLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

}
