/*
 * xDayAvailabilityPanel.java
 *
 * Created on August 17, 2005, 6:11 PM
 */

package rmischedule.employee.components.xavailability;

/**
 *
 * @author  Ira Juneau
 */
public class xDayAvailabilityPanel extends javax.swing.JPanel {
    
    private xIndividualDayPanel myDisplayedPanel;
    
    /** Creates new form xDayAvailabilityPanel */
    public xDayAvailabilityPanel() {
        initComponents();
        myDisplayedPanel = new xIndividualDayPanel();
        //InnerDisplayPanel.add(myDisplayedPanel);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        DateDisplayPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MainDayDisplayPanel = new javax.swing.JPanel();
        SpacerPanelOne = new javax.swing.JPanel();
        DisplayOuterPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SpacerPanelTwo = new javax.swing.JPanel();
        ControlsPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setOpaque(false);
        DateDisplayPanel.setLayout(new java.awt.GridLayout(1, 0));

        DateDisplayPanel.setMaximumSize(new java.awt.Dimension(5000, 24));
        DateDisplayPanel.setMinimumSize(new java.awt.Dimension(34, 24));
        DateDisplayPanel.setOpaque(false);
        DateDisplayPanel.setPreferredSize(new java.awt.Dimension(34, 24));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        DateDisplayPanel.add(jLabel1);

        add(DateDisplayPanel);

        MainDayDisplayPanel.setLayout(new javax.swing.BoxLayout(MainDayDisplayPanel, javax.swing.BoxLayout.X_AXIS));

        MainDayDisplayPanel.setOpaque(false);
        SpacerPanelOne.setMaximumSize(new java.awt.Dimension(10, 3000));
        SpacerPanelOne.setOpaque(false);
        MainDayDisplayPanel.add(SpacerPanelOne);

        DisplayOuterPanel.setLayout(new javax.swing.BoxLayout(DisplayOuterPanel, javax.swing.BoxLayout.Y_AXIS));

        DisplayOuterPanel.setMaximumSize(new java.awt.Dimension(200, 32767));
        DisplayOuterPanel.setMinimumSize(new java.awt.Dimension(100, 10));
        DisplayOuterPanel.setOpaque(false);
        DisplayOuterPanel.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel1.setOpaque(false);
        DisplayOuterPanel.add(jPanel1);

        jPanel2.setOpaque(false);
        DisplayOuterPanel.add(jPanel2);

        MainDayDisplayPanel.add(DisplayOuterPanel);

        SpacerPanelTwo.setOpaque(false);
        MainDayDisplayPanel.add(SpacerPanelTwo);

        add(MainDayDisplayPanel);

        ControlsPanel.setLayout(new javax.swing.BoxLayout(ControlsPanel, javax.swing.BoxLayout.X_AXIS));

        ControlsPanel.setMaximumSize(new java.awt.Dimension(32767, 24));
        ControlsPanel.setMinimumSize(new java.awt.Dimension(10, 24));
        ControlsPanel.setOpaque(false);
        ControlsPanel.setPreferredSize(new java.awt.Dimension(10, 24));
        jPanel3.setMaximumSize(new java.awt.Dimension(60, 32767));
        jPanel3.setOpaque(false);
        ControlsPanel.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(1000, 32767));
        jPanel4.setOpaque(false);
        ControlsPanel.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(1000, 32767));
        jPanel5.setOpaque(false);
        ControlsPanel.add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(60, 32767));
        jPanel6.setOpaque(false);
        ControlsPanel.add(jPanel6);

        add(ControlsPanel);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlsPanel;
    private javax.swing.JPanel DateDisplayPanel;
    private javax.swing.JPanel DisplayOuterPanel;
    private javax.swing.JPanel MainDayDisplayPanel;
    private javax.swing.JPanel SpacerPanelOne;
    private javax.swing.JPanel SpacerPanelTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
    
}
