/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MappingDialog.java
 *
 * Created on Apr 20, 2011, 2:43:02 PM
 */

package rmischedule.mapping;

import schedfoxlib.model.AddressInterface;

/**
 *
 * @author user
 */
public class MappingDialog extends javax.swing.JDialog {

    private MappingPanel myMapPanel;

    /** Creates new form MappingDialog */
    public MappingDialog(java.awt.Frame parent, boolean modal,
                AddressInterface addressToStart, AddressInterface addressToEnd) {
        super(parent, modal);
        initComponents();
        myMapPanel = new MappingPanel();
        mapPanel.add(myMapPanel);
        if (addressToEnd == null || !addressToEnd.isValid()) {
            myMapPanel.displayAddress(addressToStart);
        } else if (addressToStart == null || !addressToStart.isValid()) {
            myMapPanel.displayAddress(addressToEnd);
        } else {
            myMapPanel.mapDirections(addressToStart, addressToEnd);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        mapPanel.setMinimumSize(new java.awt.Dimension(525, 315));
        mapPanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(mapPanel);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(525, 35));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jButton1.setText("Close WIndow");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-533)/2, (screenSize.height-384)/2, 533, 384);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mapPanel;
    // End of variables declaration//GEN-END:variables

}
