/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetupCommissionsDialog.java
 *
 * Created on Nov 14, 2011, 11:05:47 AM
 */
package rmischedule.commissions;

import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import rmischedule.main.Main_Window;
import rmischeduleserver.control.CommissionController;
import schedfoxlib.model.Commission;

/**
 *
 * @author user
 */
public class SetupCommissionsDialog extends javax.swing.JDialog {

    private String companyId;
    private CommissionsModel commissionModel = new CommissionsModel();
    private Commission commission;

    /** Creates new form SetupCommissionsDialog */
    public SetupCommissionsDialog(java.awt.Frame parent, boolean modal, String companyId) {
        super(parent, modal);
        initComponents();
        this.companyId = companyId;
        this.loadForm();

    }

    private void loadForm() {
        CommissionController commissionsController = CommissionController.getInstance(this.companyId);
        try {
            ArrayList<Commission> commissions = commissionsController.getCommissions();
            commissionModel.clearData();
            for (int c = 0; c < commissions.size(); c++) {
                commissionModel.addCommission(commissions.get(c));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearForm() {
        commission = null;
        nameTxt.setText("");
        firstPaymentTxt.setText("");
        firstSalesYearTxt.setText("");
        firstManagerYearTxt.setText("");
        secondSalesYearTxt.setText("");
        secondManagerYearTxt.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        firstPaymentTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        firstSalesYearTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        firstManagerYearTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        secondSalesYearTxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        secondManagerYearTxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        saveCommissionBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commissionsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 110));
        jPanel2.setPreferredSize(new java.awt.Dimension(526, 110));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Commission Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel4.add(jLabel1);
        jPanel4.add(nameTxt);

        jLabel2.setText("% First Payment");
        jLabel2.setMaximumSize(new java.awt.Dimension(135, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(135, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(135, 16));
        jPanel4.add(jLabel2);

        firstPaymentTxt.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        firstPaymentTxt.setMinimumSize(new java.awt.Dimension(90, 28));
        firstPaymentTxt.setPreferredSize(new java.awt.Dimension(90, 28));
        jPanel4.add(firstPaymentTxt);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("First Year Sales %");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel5.add(jLabel3);

        firstSalesYearTxt.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        firstSalesYearTxt.setMinimumSize(new java.awt.Dimension(90, 28));
        firstSalesYearTxt.setPreferredSize(new java.awt.Dimension(90, 28));
        jPanel5.add(firstSalesYearTxt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel3);

        jLabel4.setText("First Year Manager %");
        jLabel4.setMaximumSize(new java.awt.Dimension(135, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(135, 16));
        jLabel4.setPreferredSize(new java.awt.Dimension(135, 16));
        jPanel5.add(jLabel4);

        firstManagerYearTxt.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        firstManagerYearTxt.setMinimumSize(new java.awt.Dimension(90, 28));
        firstManagerYearTxt.setPreferredSize(new java.awt.Dimension(90, 28));
        jPanel5.add(firstManagerYearTxt);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Second Year Sales %");
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel6.add(jLabel5);

        secondSalesYearTxt.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        secondSalesYearTxt.setMinimumSize(new java.awt.Dimension(90, 28));
        secondSalesYearTxt.setPreferredSize(new java.awt.Dimension(90, 28));
        jPanel6.add(secondSalesYearTxt);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8);

        jLabel6.setText("Second Year Manager %");
        jPanel6.add(jLabel6);

        secondManagerYearTxt.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        secondManagerYearTxt.setMinimumSize(new java.awt.Dimension(90, 28));
        secondManagerYearTxt.setPreferredSize(new java.awt.Dimension(90, 28));
        jPanel6.add(secondManagerYearTxt);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        saveCommissionBtn.setText("Save Commission");
        saveCommissionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCommissionBtnActionPerformed(evt);
            }
        });
        jPanel7.add(saveCommissionBtn);

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Commissions"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        commissionsTable.setModel(commissionModel);
        commissionsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commissionsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(commissionsTable);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-578)/2, (screenSize.height-326)/2, 578, 326);
    }// </editor-fold>//GEN-END:initComponents

    private void saveCommissionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCommissionBtnActionPerformed
        if (this.commission == null) {
            this.commission = new Commission();
            this.commission.setActive(true);
        }
        this.commission.setCommission_name(nameTxt.getText());
        CommissionController commissionsController = CommissionController.getInstance(this.companyId);
        try {
            try {
                this.commission.setFirst_pmt_sales_percentage(new BigDecimal(Double.parseDouble(firstPaymentTxt.getText()) / 100));
            } catch (Exception e) {
                throw new Exception("Invalid value for first payment sales percentage!");
            }
            try {
                this.commission.setFirst_year_sales_percentage(new BigDecimal(Double.parseDouble(firstSalesYearTxt.getText()) / 100));
            } catch (Exception e) {
                throw new Exception("Invalid value for first year sales percentage!");
            }
            try {
                this.commission.setFirst_year_manager_percentage(new BigDecimal(Double.parseDouble(firstManagerYearTxt.getText()) / 100));
            } catch (Exception e) {
                throw new Exception("Invalid value for first year manager percentage!");
            }
            try {
                this.commission.setSecond_year_sales_percentage(new BigDecimal(Double.parseDouble(secondSalesYearTxt.getText()) / 100));
            } catch (Exception e) {
                throw new Exception("Invalid value for second year sales percentage!");
            }
            try {
                this.commission.setSecond_year_manager_percentage(new BigDecimal(Double.parseDouble(secondManagerYearTxt.getText()) / 100));
            } catch (Exception e) {
                throw new Exception("Invalid value for second year manager percentage!");
            }
            commissionsController.saveCommission(commission);
            clearForm();
            loadForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Could not save commission!\r\nError: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_saveCommissionBtnActionPerformed

    private void commissionsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commissionsTableMouseClicked
        commission = commissionModel.getCommissionAt(commissionsTable.getSelectedRow());
        nameTxt.setText(commission.getCommission_name());
        firstPaymentTxt.setText((commission.getFirst_pmt_sales_percentage().doubleValue() * 100) + "");
        firstSalesYearTxt.setText((commission.getFirst_year_sales_percentage().floatValue() * 100) + "");
        firstManagerYearTxt.setText((commission.getFirst_year_manager_percentage().floatValue() * 100) + "");
        secondSalesYearTxt.setText((commission.getSecond_year_sales_percentage().floatValue() * 100) + "");
        secondManagerYearTxt.setText((commission.getSecond_year_manager_percentage().floatValue() * 100) + "");
    }//GEN-LAST:event_commissionsTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable commissionsTable;
    private javax.swing.JTextField firstManagerYearTxt;
    private javax.swing.JTextField firstPaymentTxt;
    private javax.swing.JTextField firstSalesYearTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton saveCommissionBtn;
    private javax.swing.JTextField secondManagerYearTxt;
    private javax.swing.JTextField secondSalesYearTxt;
    // End of variables declaration//GEN-END:variables
}
