/*  package declaration */
package rmischedule.reports.email.views;

/*  import declarations */
import java.awt.Cursor;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import rmischedule.main.Main_Window;
import rmischedule.reports.email.controllers.EmailReportController;

/**
 *
 * @author jdavis
 */
public class InactiveClientEmailReportDiag extends javax.swing.JDialog
{
    /*  object variable declarations    */
    private EmailReportController controller = EmailReportController.getInstance();
    
    /*  private method implementations  */
    private void updateSelectAllDisplay()
    {
        if ( this.jSelectAllToggleButton.isSelected() )
        {
            this.jSelectAllToggleButton.setIcon( Main_Window.Inactive_Schema_16x16_px);
            this.jSelectAllToggleButton.setText( "Deselect All" );
        }
        else
        {
            this.jSelectAllToggleButton.setIcon( Main_Window.Active_Schema_16x16_px );
            this.jSelectAllToggleButton.setText( "Select All" );
        }
    }

    /** Creates new form InactiveClientEmailReportDiag */
    public InactiveClientEmailReportDiag() 
    {
        super( Main_Window.parentOfApplication, true );
        initComponents();
        this.setTitle( "Inactive Client Email Reports");
        
        /*  set icons   */
        this.jExitButton.setIcon( Main_Window.Problemsolver_Email_Dialog_Exit_16x16_px);
        this.jSelectAllToggleButton.setSelected(false);
        this.jRunReportButton.setIcon(Main_Window.EmailReport_RunReport_16x16px);
        this.updateSelectAllDisplay();
    }
    
    /*  accessor methods    */
    public JComboBox getCompaniesComboBox() {  return this.jCompaniesComboBox;  }
    public JPanel getBranchPanel()  {  return this.jBranchesPanel; }
    public JToggleButton getSelectAllButton()   {  return this.jSelectAllToggleButton;  }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jBasePanel = new javax.swing.JPanel();
        jCompaniesPanel = new javax.swing.JPanel();
        jCompaniesComboBoxLabel = new javax.swing.JLabel();
        jCompaniesComboBox = new javax.swing.JComboBox();
        jBranchesBasePanel = new javax.swing.JPanel();
        jBranchesScrollPane = new javax.swing.JScrollPane();
        jBranchesPanel = new javax.swing.JPanel();
        jButtonPanel = new javax.swing.JPanel();
        jSelectAllToggleButton = new javax.swing.JToggleButton();
        jExitButton = new javax.swing.JButton();
        jRunReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jBasePanel.setLayout(new java.awt.BorderLayout());

        jCompaniesComboBoxLabel.setText("Companies:  ");

        jCompaniesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompaniesComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCompaniesPanelLayout = new javax.swing.GroupLayout(jCompaniesPanel);
        jCompaniesPanel.setLayout(jCompaniesPanelLayout);
        jCompaniesPanelLayout.setHorizontalGroup(
            jCompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCompaniesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCompaniesComboBoxLabel)
                .addGap(18, 18, 18)
                .addComponent(jCompaniesComboBox, 0, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        jCompaniesPanelLayout.setVerticalGroup(
            jCompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCompaniesPanelLayout.createSequentialGroup()
                .addGroup(jCompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCompaniesComboBoxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(jCompaniesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBasePanel.add(jCompaniesPanel, java.awt.BorderLayout.NORTH);

        jBranchesBasePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Branches"));
        jBranchesBasePanel.setLayout(new java.awt.GridBagLayout());

        jBranchesScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jBranchesPanel.setLayout(new java.awt.GridBagLayout());
        jBranchesScrollPane.setViewportView(jBranchesPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jBranchesBasePanel.add(jBranchesScrollPane, gridBagConstraints);

        jBasePanel.add(jBranchesBasePanel, java.awt.BorderLayout.CENTER);

        jButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        jSelectAllToggleButton.setText("Select All");
        jSelectAllToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectAllToggleButtonActionPerformed(evt);
            }
        });

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jRunReportButton.setText("Run Report");
        jRunReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRunReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jButtonPanelLayout = new javax.swing.GroupLayout(jButtonPanel);
        jButtonPanel.setLayout(jButtonPanelLayout);
        jButtonPanelLayout.setHorizontalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jExitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSelectAllToggleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jRunReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jButtonPanelLayout.setVerticalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSelectAllToggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExitButton)
                    .addComponent(jRunReportButton))
                .addContainerGap())
        );

        jBasePanel.add(jButtonPanel, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jBasePanel, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-575)/2, (screenSize.height-525)/2, 575, 525);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jSelectAllToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectAllToggleButtonActionPerformed
        this.updateSelectAllDisplay();
        controller.inactiveClientSelectAllAction();
    }//GEN-LAST:event_jSelectAllToggleButtonActionPerformed

    private void jCompaniesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompaniesComboBoxActionPerformed
        controller.inactiveClientCompanyComboBoxAction();
    }//GEN-LAST:event_jCompaniesComboBoxActionPerformed

    private void jRunReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRunReportButtonActionPerformed
        /*  check to ensure report is ready to run  */
        if ( controller.isInactiveClientReady() )
        {
            /*  set cursor  */
            Cursor hourglassCursor = new Cursor ( Cursor.WAIT_CURSOR );
            this.setCursor(hourglassCursor);
        
            controller.inactiveClientRunReportAction();
        
            Cursor normalCursor = new Cursor ( Cursor.DEFAULT_CURSOR );
            this.setCursor ( normalCursor );
        
            this.dispose();
        }       
    }//GEN-LAST:event_jRunReportButtonActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBasePanel;
    private javax.swing.JPanel jBranchesBasePanel;
    private javax.swing.JPanel jBranchesPanel;
    private javax.swing.JScrollPane jBranchesScrollPane;
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JComboBox jCompaniesComboBox;
    private javax.swing.JLabel jCompaniesComboBoxLabel;
    private javax.swing.JPanel jCompaniesPanel;
    private javax.swing.JButton jExitButton;
    private javax.swing.JButton jRunReportButton;
    private javax.swing.JToggleButton jSelectAllToggleButton;
    // End of variables declaration//GEN-END:variables
};
