/*  package declaration */
package rmischedule.reports.email.views;

/*  import declarations */
import java.awt.Cursor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import rmischedule.main.Main_Window;
import rmischedule.reports.email.controllers.EmailReportController;

/**
 *  This is the view object for Clients in the EmailReportSystem.
 *  @author Jeffrey N. Davis    
 *  @see rmischedule.reports.email.controllers.EmailReportController
 *  @since 04/21/2011 
 */
public class InvalidClientEmailReportDiag extends javax.swing.JDialog 
{
    /*  object variable declarations    */
    private EmailReportController controller = EmailReportController.getInstance();
    
    /*  private method implemenations   */
    private void updateSelectAllDisplay()
    {
        if ( this.jSelectAllButton.isSelected() )
        {
            this.jSelectAllButton.setIcon( Main_Window.Inactive_Schema_16x16_px);
            this.jSelectAllButton.setText( "Deselect All" );
        }
        else
        {
            this.jSelectAllButton.setIcon( Main_Window.Active_Schema_16x16_px );
            this.jSelectAllButton.setText( "Select All" );
        }
    }
    
    /** Creates new form InvalidClientEmailReportDiag */
    public InvalidClientEmailReportDiag() 
    {
        super( Main_Window.parentOfApplication, true );
        initComponents();
        this.setTitle( "Invalid Client Email Reports" );
        
        /*  set icons   */
        this.jExitButton.setIcon( Main_Window.Problemsolver_Email_Dialog_Exit_16x16_px );
        this.jSelectAllButton.setSelected( false );
        this.jRunReportsButton.setIcon ( Main_Window.EmailReport_RunReport_16x16px );
        this.updateSelectAllDisplay();
    }
    
    /*  accessor methods    */
    public JComboBox getCompaniesComboBox() {  return this.jCompaniesComboBox;  }
    public JPanel getBranchPanel()  {  return this.jBranchesPanel; }
    public JToggleButton getSelectAllButton()   {  return this.jSelectAllButton;  }
    public JCheckBox getInvalidCheckBox()   {  return this.jInvalidEmailsCheckBox;  }
    public JCheckBox getEmptyCheckBox() {  return this.jEmptyEmailsCheckBox;  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jBasePanel = new javax.swing.JPanel();
        jCompaniesPanel = new javax.swing.JPanel();
        jCompaniesComboBox = new javax.swing.JComboBox();
        jCompaniesComboBoxLabel = new javax.swing.JLabel();
        jBranchesBasePanel = new javax.swing.JPanel();
        jBranchesScrollPane = new javax.swing.JScrollPane();
        jBranchesPanel = new javax.swing.JPanel();
        jButtonPanel = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jRunReportsButton = new javax.swing.JButton();
        jInvalidEmailsCheckBox = new javax.swing.JCheckBox();
        jEmptyEmailsCheckBox = new javax.swing.JCheckBox();
        jSelectAllButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jBasePanel.setLayout(new java.awt.BorderLayout());

        jCompaniesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompaniesComboBoxActionPerformed(evt);
            }
        });

        jCompaniesComboBoxLabel.setText("Companies:");

        javax.swing.GroupLayout jCompaniesPanelLayout = new javax.swing.GroupLayout(jCompaniesPanel);
        jCompaniesPanel.setLayout(jCompaniesPanelLayout);
        jCompaniesPanelLayout.setHorizontalGroup(
            jCompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCompaniesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCompaniesComboBoxLabel)
                .addGap(18, 18, 18)
                .addComponent(jCompaniesComboBox, 0, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
        jCompaniesPanelLayout.setVerticalGroup(
            jCompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCompaniesPanelLayout.createSequentialGroup()
                .addGroup(jCompaniesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCompaniesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCompaniesComboBoxLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBasePanel.add(jCompaniesPanel, java.awt.BorderLayout.NORTH);

        jBranchesBasePanel.setBorder(null);
        jBranchesBasePanel.setLayout(new java.awt.GridBagLayout());

        jBranchesScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jBranchesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Branches"));
        jBranchesPanel.setLayout(new java.awt.GridBagLayout());
        jBranchesScrollPane.setViewportView(jBranchesPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jBranchesBasePanel.add(jBranchesScrollPane, gridBagConstraints);

        jBasePanel.add(jBranchesBasePanel, java.awt.BorderLayout.CENTER);

        jButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jRunReportsButton.setText("Run Report");
        jRunReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRunReportsButtonActionPerformed(evt);
            }
        });

        jInvalidEmailsCheckBox.setText("Invalid Emails");

        jEmptyEmailsCheckBox.setText("Empty Emails");

        jSelectAllButton.setText("Select All");
        jSelectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jButtonPanelLayout = new javax.swing.GroupLayout(jButtonPanel);
        jButtonPanel.setLayout(jButtonPanelLayout);
        jButtonPanelLayout.setHorizontalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jSelectAllButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(175, 175, 175)
                .addComponent(jEmptyEmailsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRunReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jInvalidEmailsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        jButtonPanelLayout.setVerticalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jInvalidEmailsCheckBox)
                        .addComponent(jEmptyEmailsCheckBox))
                    .addComponent(jSelectAllButton))
                .addGap(18, 18, 18)
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExitButton)
                    .addComponent(jRunReportsButton))
                .addContainerGap())
        );

        jBasePanel.add(jButtonPanel, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jBasePanel, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-575)/2, (screenSize.height-525)/2, 575, 525);
    }// </editor-fold>//GEN-END:initComponents

    private void jSelectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectAllButtonActionPerformed
        this.updateSelectAllDisplay();
        controller.invalidClientSelectAllAction();
    }//GEN-LAST:event_jSelectAllButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jCompaniesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompaniesComboBoxActionPerformed
        controller.invalidClientCompanyComboBoxAction();
    }//GEN-LAST:event_jCompaniesComboBoxActionPerformed

    private void jRunReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRunReportsButtonActionPerformed
        /*  set cursor  */
        Cursor hourglassCursor = new Cursor ( Cursor.WAIT_CURSOR );
        this.setCursor(hourglassCursor);
        
        controller.invalidClientRunReportAction();
        
        Cursor normalCursor = new Cursor ( Cursor.DEFAULT_CURSOR );
        this.setCursor ( normalCursor );
        
        this.dispose();
    }//GEN-LAST:event_jRunReportsButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBasePanel;
    private javax.swing.JPanel jBranchesBasePanel;
    private javax.swing.JPanel jBranchesPanel;
    private javax.swing.JScrollPane jBranchesScrollPane;
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JComboBox jCompaniesComboBox;
    private javax.swing.JLabel jCompaniesComboBoxLabel;
    private javax.swing.JPanel jCompaniesPanel;
    private javax.swing.JCheckBox jEmptyEmailsCheckBox;
    private javax.swing.JButton jExitButton;
    private javax.swing.JCheckBox jInvalidEmailsCheckBox;
    private javax.swing.JButton jRunReportsButton;
    private javax.swing.JToggleButton jSelectAllButton;
    // End of variables declaration//GEN-END:variables
};
