//  package declaration
package rmischedule.messaging.client_email.views;

//  import declarations
import java.awt.Color;
import rmischedule.messaging.client_email.models.ClientContactData;

/**
 *
 * @author jdavis
 */
public class Client_Contact_Panel extends javax.swing.JPanel
{
    /*  object variable declarations    */
    private final ClientContactData contactData;
    private final String clientName;

    /*  object instantiation code   */
    /**
     *  Default instantiation of this object is not allowed
     *  @throw UnsupportedOperationException
     */
    private Client_Contact_Panel()
    {
        throw new UnsupportedOperationException ( "Default instantiation of Client_Contact_Panel is not allowed." );
    }

    /**
     *  Create an instance of this object
     *  @param ClientContactData an instance of {@code ClientContactData} that this
     *      view represents
     *  @param clientName a string representing the client name
     */
    public Client_Contact_Panel( ClientContactData contactData, String clientName )
    {
        initComponents();

        this.contactData = contactData;
        this.clientName = clientName;

        this.jClientLabel.setText( this.clientName );
        this.jClientNameLabel.setText ( this.contactData.getContactFirstName() + " " + this.contactData.getContactLastName() );
        this.jEmailLabel.setText( this.contactData.getContactEmailAddress() );
        this.jPhoneLabel.setText( this.contactData.getContactPhone() );
        this.jTitleLabel.setText( this.contactData.getClientContactTitle() );
        String primaryAlternate = this.contactData.isIsContactPrimary() ? "PRIMARY" : "ALTERNATE";
        this.jPrimaryLabel.setText( primaryAlternate );
        this.jPrimaryLabel.setForeground( this.contactData.isIsContactPrimary()
                ? Color.green.darker()
                : Color.RED.darker()
                );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jClientLabel = new javax.swing.JLabel();
        jClientNameLabel = new javax.swing.JLabel();
        jEmailLabel = new javax.swing.JLabel();
        jPhoneLabel = new javax.swing.JLabel();
        jTitleLabel = new javax.swing.JLabel();
        jPrimaryLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("lol"));
        setLayout(new java.awt.GridLayout(1, 6));
        add(jClientLabel);
        add(jClientNameLabel);
        add(jEmailLabel);
        add(jPhoneLabel);
        add(jTitleLabel);
        add(jPrimaryLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jClientLabel;
    private javax.swing.JLabel jClientNameLabel;
    private javax.swing.JLabel jEmailLabel;
    private javax.swing.JLabel jPhoneLabel;
    private javax.swing.JLabel jPrimaryLabel;
    private javax.swing.JLabel jTitleLabel;
    // End of variables declaration//GEN-END:variables
};
