//  package declaration
package rmischedule.messaging.client_email.views;

//  import declarations
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import rmischedule.main.Main_Window;
import rmischedule.messaging.client_email.controllers.Client_Email_Controller;
import rmischedule.messaging.client_email.models.Client_Contact_Table_Model;

/**
 *  This class is a view component of the Client_Email_System.  It displays
 *      the address book of all clients in the system, and give the option
 *      to both view their information and select their email address.  The
 *      controller is {@code Client_Email_Controller}
 *  @author Jeffrey N. Davis
 *  @see rmischedule.messaging.client_email.controllers.Client_Email_Controller
 *  @since 03/29/2011
 */
public class Client_Email_AddressBook_Dialog extends javax.swing.JDialog
{
    /*  object variable declarations    */
    private Client_Email_Controller clientEmailController;

    /**
     *  Standard initialization of this object.  The rest of the setup occurs
     *      in the public {@code init} method.
     */
    public Client_Email_AddressBook_Dialog ( )
    {
        super(Main_Window.parentOfApplication, true);
        this.clientEmailController = Client_Email_Controller.getInstance();
        initComponents();

        this.jContactsTable.getColumnModel().getColumn( 5 ).setCellRenderer( Client_Contact_Table_Model.getCellRenderer() );

        //  set icons
        this.jFinishedButton.setIcon( Main_Window.Client_Email_AddressBook_Finished_16x16_px );
        this.jAddContactButton.setIcon( Main_Window.Client_Email_AddressBook_Add_16x16_px );
        this.jExitButton.setIcon ( Main_Window.Problemsolver_Email_Dialog_Exit_16x16_px );

        //  set tool tip text
        this.jFinishedButton.setToolTipText( "Return to Client Email with added addresses. " );
        this.jExitButton.setToolTipText ( "Return to Client Email with NO email addresses. ");
        this.jAddContactButton.setToolTipText( "Add's a contact's email address to the To field in Client Email. " );
    }

    /**
     *  Initializes this object.
     */
    public void init()
    {
        //this.clientEmailController = Client_Email_Controller.getInstance();
    }

    /*  accessor methods    */
    public JComboBox getBranchComboBox()    { return this.jBranchesComboBox;    }
    public JComboBox getClientsComboBox()   { return this.jClientsComboBox;     }
    public JTable getContactTable() {  return this.jContactsTable;  }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jBasePanel = new javax.swing.JPanel();
        jBranchClientComboBoxPanel = new javax.swing.JPanel();
        jBranchesComboBoxLabel = new javax.swing.JLabel();
        jBranchesComboBox = new javax.swing.JComboBox();
        jClientsComboBox = new javax.swing.JComboBox();
        jClientsLabel = new javax.swing.JLabel();
        jContactsBasePanel = new javax.swing.JPanel();
        jContactsScrollPane = new javax.swing.JScrollPane();
        jContactsTable = new javax.swing.JTable();
        jButtonPanel = new javax.swing.JPanel();
        jAddContactButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();
        jFinishedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Champion National Security Client Email Address Book\n");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jBasePanel.setLayout(new javax.swing.BoxLayout(jBasePanel, javax.swing.BoxLayout.PAGE_AXIS));

        jBranchesComboBoxLabel.setText("Branches:");

        jBranchesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBranchesComboBoxActionPerformed(evt);
            }
        });

        jClientsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientsComboBoxActionPerformed(evt);
            }
        });

        jClientsLabel.setText("Clients:");

        javax.swing.GroupLayout jBranchClientComboBoxPanelLayout = new javax.swing.GroupLayout(jBranchClientComboBoxPanel);
        jBranchClientComboBoxPanel.setLayout(jBranchClientComboBoxPanelLayout);
        jBranchClientComboBoxPanelLayout.setHorizontalGroup(
            jBranchClientComboBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBranchClientComboBoxPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jBranchesComboBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBranchesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jClientsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClientsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jBranchClientComboBoxPanelLayout.setVerticalGroup(
            jBranchClientComboBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBranchClientComboBoxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBranchClientComboBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBranchesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClientsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBranchesComboBoxLabel)
                    .addComponent(jClientsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBasePanel.add(jBranchClientComboBoxPanel);

        jContactsBasePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacts"));
        jContactsBasePanel.setLayout(new java.awt.GridBagLayout());

        jContactsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jContactsTable.setModel(clientEmailController.getTableModel());
        jContactsScrollPane.setViewportView(jContactsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jContactsBasePanel.add(jContactsScrollPane, gridBagConstraints);

        jBasePanel.add(jContactsBasePanel);

        jButtonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jAddContactButton.setText("Add Contact");
        jAddContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddContactButtonActionPerformed(evt);
            }
        });

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jFinishedButton.setText("Finished");
        jFinishedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinishedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jButtonPanelLayout = new javax.swing.GroupLayout(jButtonPanel);
        jButtonPanel.setLayout(jButtonPanelLayout);
        jButtonPanelLayout.setHorizontalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddContactButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(jFinishedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jButtonPanelLayout.setVerticalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddContactButton)
                    .addComponent(jExitButton)
                    .addComponent(jFinishedButton))
                .addContainerGap())
        );

        jBasePanel.add(jButtonPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jBasePanel, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-550)/2, 700, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void jBranchesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBranchesComboBoxActionPerformed
        clientEmailController.addressBookBranchComboBoxControl();
    }//GEN-LAST:event_jBranchesComboBoxActionPerformed

    private void jClientsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientsComboBoxActionPerformed
        clientEmailController.addressBookClientComboBoxControl();
    }//GEN-LAST:event_jClientsComboBoxActionPerformed

    private void jAddContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddContactButtonActionPerformed
        clientEmailController.addressBookAddContactControl();
    }//GEN-LAST:event_jAddContactButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        clientEmailController.addressBookExitButtonControl();
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jFinishedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinishedButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jFinishedButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddContactButton;
    private javax.swing.JPanel jBasePanel;
    private javax.swing.JPanel jBranchClientComboBoxPanel;
    private javax.swing.JComboBox jBranchesComboBox;
    private javax.swing.JLabel jBranchesComboBoxLabel;
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JComboBox jClientsComboBox;
    private javax.swing.JLabel jClientsLabel;
    private javax.swing.JPanel jContactsBasePanel;
    private javax.swing.JScrollPane jContactsScrollPane;
    private javax.swing.JTable jContactsTable;
    private javax.swing.JButton jExitButton;
    private javax.swing.JButton jFinishedButton;
    // End of variables declaration//GEN-END:variables
};
