//  package declaration
package rmischedule.messaging.client_email.views;

//  import declarations
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import rmischedule.main.Main_Window;
import rmischedule.messaging.client_email.controllers.Client_Email_Controller;
import rmischedule.messaging.client_email.models.Client_Email_Data;
import rmischedule.messaging.client_email.models.RecipientTableModel;

/**
 * A view form for confirming the recipients and body / message of
 * {@code Client_Email}
 *
 * @author Jeffrey N. Davis
 * @see rmischedule.messaging.client_email.controllers.Client_Email_Controller
 * @since 03/25/2011
 */
public class Confirm_Send_Client_Email_Dialog extends javax.swing.JDialog {
    /*  object variable declarations    */

    private Client_Email_Controller clientEmailController;
    private RecipientTableModel recipientsTableModel;

    /**
     * Creates new form Confirm_Send_Client_Email_Dialog
     */
    public Confirm_Send_Client_Email_Dialog(Map<Integer, Client_Email_Data> sendMap) {
        super(Main_Window.parentOfApplication, true);
        this.clientEmailController = Client_Email_Controller.getInstance();
        this.recipientsTableModel = new RecipientTableModel();
        recipientsTableModel.init(sendMap);
        initComponents();

        //  set icons
        this.jExitButton.setIcon(Main_Window.Problemsolver_Email_Dialog_Exit_16x16_px);
        this.jSendButton.setIcon(Main_Window.Problemsolver_Email_Dialog_Send_16x16_px);

        //  set tool tip text
        this.jExitButton.setToolTipText("Return to Client Email without sending.");
        this.jSendButton.setToolTipText("Send Email.");

        //  set text pane
        this.jMessageTextPane.setEditable(false);
    }

    /*  accessor methods    */
    public JLabel getSubjectDataLabel() {
        return this.jSubjectDataLabel;
    }

    public JTextPane getMessageTextPane() {
        return this.jMessageTextPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jBasePanel = new javax.swing.JPanel();
        jEmailMessagePanel = new javax.swing.JPanel();
        jSubjectLabel = new javax.swing.JLabel();
        jSubjectDataLabel = new javax.swing.JLabel();
        jMessageLabel = new javax.swing.JLabel();
        jMessageScrollPanel = new javax.swing.JScrollPane();
        jMessageTextPane = new javax.swing.JTextPane();
        jRecipientsPanel = new javax.swing.JPanel();
        jRecipientsScrollPane = new javax.swing.JScrollPane();
        jRecipientsTable = new javax.swing.JTable();
        jButtonPanel = new javax.swing.JPanel();
        jExitButton = new javax.swing.JButton();
        jSendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirm Client Email");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jBasePanel.setLayout(new javax.swing.BoxLayout(jBasePanel, javax.swing.BoxLayout.PAGE_AXIS));

        jEmailMessagePanel.setPreferredSize(new java.awt.Dimension(642, 120));

        jSubjectLabel.setText("Subject:");

        jMessageLabel.setText("Message:");

        jMessageScrollPanel.setViewportView(jMessageTextPane);

        javax.swing.GroupLayout jEmailMessagePanelLayout = new javax.swing.GroupLayout(jEmailMessagePanel);
        jEmailMessagePanel.setLayout(jEmailMessagePanelLayout);
        jEmailMessagePanelLayout.setHorizontalGroup(
            jEmailMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEmailMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEmailMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEmailMessagePanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jSubjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSubjectDataLabel))
                    .addGroup(jEmailMessagePanelLayout.createSequentialGroup()
                        .addComponent(jMessageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMessageScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jEmailMessagePanelLayout.setVerticalGroup(
            jEmailMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEmailMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEmailMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSubjectLabel)
                    .addComponent(jSubjectDataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jEmailMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessageLabel)
                    .addComponent(jMessageScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap())
        );

        jBasePanel.add(jEmailMessagePanel);

        jRecipientsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("To:\n"));
        jRecipientsPanel.setLayout(new java.awt.GridBagLayout());

        jRecipientsTable.setModel(recipientsTableModel);
        jRecipientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRecipientsTableMouseClicked(evt);
            }
        });
        jRecipientsScrollPane.setViewportView(jRecipientsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jRecipientsPanel.add(jRecipientsScrollPane, gridBagConstraints);

        jBasePanel.add(jRecipientsPanel);

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jSendButton.setText("Send");
        jSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jButtonPanelLayout = new javax.swing.GroupLayout(jButtonPanel);
        jButtonPanel.setLayout(jButtonPanelLayout);
        jButtonPanelLayout.setHorizontalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonPanelLayout.createSequentialGroup()
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(jSendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jButtonPanelLayout.setVerticalGroup(
            jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jExitButton)
                .addComponent(jSendButton))
        );

        jBasePanel.add(jButtonPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jBasePanel, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-650)/2, (screenSize.height-550)/2, 650, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        clientEmailController.confirmSendDialogCancelControl();
        this.dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSendButtonActionPerformed
        clientEmailController.confirmSendDialogSendControl();
        this.dispose();
    }//GEN-LAST:event_jSendButtonActionPerformed

    private void jRecipientsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRecipientsTableMouseClicked
        try {
            Client_Email_Data data = recipientsTableModel.getClientEmailAt(jRecipientsTable.getSelectedRow());
            jMessageTextPane.setText(data.getEmailBody());
        } catch (Exception exe) {
        }
    }//GEN-LAST:event_jRecipientsTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBasePanel;
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JPanel jEmailMessagePanel;
    private javax.swing.JButton jExitButton;
    private javax.swing.JLabel jMessageLabel;
    private javax.swing.JScrollPane jMessageScrollPanel;
    private javax.swing.JTextPane jMessageTextPane;
    private javax.swing.JPanel jRecipientsPanel;
    private javax.swing.JScrollPane jRecipientsScrollPane;
    private javax.swing.JTable jRecipientsTable;
    private javax.swing.JButton jSendButton;
    private javax.swing.JLabel jSubjectDataLabel;
    private javax.swing.JLabel jSubjectLabel;
    // End of variables declaration//GEN-END:variables
};
