/*
 * DateDisplayPanel.java
 *
 * Created on July 1, 2005, 8:59 AM
 */

package rmischedule.schedule.components;
import rmischedule.schedule.*;
import rmischeduleserver.util.StaticDateTimeFunctions;
import rmischedule.components.jcalendar.JCalendarComboBox;
import java.util.Calendar;
import java.text.*;
import rmischedule.main.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import javax.swing.event.*;

/**
 *
 * @author  ira
 */
public class DateDisplayPanel extends javax.swing.JPanel {

    private String Company;
    private String Branch;
    private Schedule_View_Panel Parent;
    private Calendar begDate, endDate;
    private JCalendarComboBox begCal;
    private JCalendarComboBox endCal;
    private boolean initial;

    /** Creates new form DateDisplayPanel */
    public DateDisplayPanel(Schedule_View_Panel parent) {
        initial = true;
        initComponents();
        Company = parent.getCompany();
        Branch = parent.getBranch();

        SimpleDateFormat myFormat = new SimpleDateFormat("MM/dd/yyyy");
        begDate = StaticDateTimeFunctions.getBegOfWeek(Integer.parseInt(Company));
        myFormat.format(begDate.getTime());
        endDate = StaticDateTimeFunctions.getEndOfWeek(Integer.parseInt(Company));
        myFormat.format(endDate.getTime());
        begDate.add(Calendar.WEEK_OF_YEAR, -Main_Window.parentOfApplication.getNumberOfWeeksToLoadInPast(Company));
        myFormat.format(begDate.getTime());
        endDate.add(Calendar.WEEK_OF_YEAR,  Main_Window.parentOfApplication.getNumberOfWeeksToLoadInFuture(Company));
        myFormat.format(endDate.getTime());

        begCal = new JCalendarComboBox(begDate);
        endCal = new JCalendarComboBox(endDate);

        container1.add(begCal);
        container2.add(endCal);
  
        revalidate();

        begCal.addChangeListener(new myChangeListener());
        endCal.addChangeListener(new myChangeListener());

        initial = false;
    }

    public void setEnabled(boolean b) {
        
        super.setEnabled(b);
        begCal.setEnabled(b);
        endCal.setEnabled(b);
    }

    public Calendar getBegDate() {
        return begDate;
    }

    public Calendar getEndDate() {
        return endDate;
    }

    public void setBegDate(java.util.Date d) {
        Calendar c = Calendar.getInstance();
        c.setTime(d);
        begCal.setCalendar(c);
    }

    public void setEndDate(java.util.Date d) {
        Calendar c = Calendar.getInstance();
        c.setTime(d);
        endCal.setCalendar(c);
    }

    public String getCompany() {
        return Company;
    }

    public String getBranch() {
        return Branch;
    }

    /**
     * Used to set the BegWeekCombo to Monday and the EndWeekCombo to Sunday...
     */
    public void setUpCalendars() {
        Calendar myEnd = endCal.getCalendar();
        Calendar myBeg = begCal.getCalendar();

        if (!StaticDateTimeFunctions.isEndOfWeek(myEnd, Integer.parseInt(Company))) {
            endDate = StaticDateTimeFunctions.getEndOfWeek(myEnd, Integer.parseInt(Company));
        } else {
            endDate = myEnd;
        }
        begDate = StaticDateTimeFunctions.getBegOfWeek(myBeg, Integer.parseInt(Company));

        endCal.setCalendar(endDate);
        begCal.setCalendar(begDate);
    }

    private class myChangeListener implements ChangeListener {
        private boolean hasAdjustedWeek;

        public myChangeListener() {
            hasAdjustedWeek = false;
        }

        public void stateChanged(ChangeEvent e) {
            if (!hasAdjustedWeek) {
                hasAdjustedWeek = true;
                setUpCalendars();
                hasAdjustedWeek = false;
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartPanel = new javax.swing.JPanel();
        EndLabelx = new javax.swing.JLabel();
        container1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        EndPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        container2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(150, 40));
        setMinimumSize(new java.awt.Dimension(150, 40));
        setPreferredSize(new java.awt.Dimension(150, 40));
        setLayout(new java.awt.GridLayout(0, 1));

        StartPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StartPanel.setMaximumSize(new java.awt.Dimension(130, 30));
        StartPanel.setMinimumSize(new java.awt.Dimension(130, 20));
        StartPanel.setPreferredSize(new java.awt.Dimension(130, 20));
        StartPanel.setLayout(new javax.swing.BoxLayout(StartPanel, javax.swing.BoxLayout.LINE_AXIS));

        EndLabelx.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        EndLabelx.setText("Start ");
        EndLabelx.setMaximumSize(new java.awt.Dimension(27, 14));
        EndLabelx.setMinimumSize(new java.awt.Dimension(27, 14));
        EndLabelx.setPreferredSize(new java.awt.Dimension(27, 14));
        StartPanel.add(EndLabelx);

        container1.setLayout(new java.awt.GridLayout());
        StartPanel.add(container1);

        jPanel1.setMaximumSize(new java.awt.Dimension(15, 5));
        jPanel1.setMinimumSize(new java.awt.Dimension(15, 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(15, 5));
        StartPanel.add(jPanel1);

        add(StartPanel);

        EndPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EndPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        EndPanel.setMaximumSize(new java.awt.Dimension(133, 30));
        EndPanel.setMinimumSize(new java.awt.Dimension(133, 20));
        EndPanel.setPreferredSize(new java.awt.Dimension(133, 20));
        EndPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EndPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EndPanelMousePressed(evt);
            }
        });
        EndPanel.setLayout(new javax.swing.BoxLayout(EndPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jLabel2.setText("End ");
        jLabel2.setMaximumSize(new java.awt.Dimension(27, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(27, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(27, 14));
        EndPanel.add(jLabel2);

        container2.setLayout(new java.awt.GridLayout());
        EndPanel.add(container2);

        jPanel2.setMaximumSize(new java.awt.Dimension(15, 5));
        jPanel2.setMinimumSize(new java.awt.Dimension(15, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(15, 5));
        EndPanel.add(jPanel2);

        add(EndPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void EndPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EndPanelMousePressed
// TODO add your handling code here:
    }//GEN-LAST:event_EndPanelMousePressed

    private void EndPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EndPanelMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_EndPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EndLabelx;
    private javax.swing.JPanel EndPanel;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JPanel container1;
    private javax.swing.JPanel container2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
