/*
 * EmployeeIconDisplay.java
 *
 * Created on February 18, 2005, 10:33 AM
 */

package rmischedule.schedule.components;

import rmischedule.schedule.*;
import rmischedule.components.*;
import javax.swing.ImageIcon;
import rmischedule.main.Main_Window;
/**
 *
 * @author  ira
 */
public class EmployeeIconDisplay extends javax.swing.JPanel {
    
    private Schedule_View_Panel parent;
    private ImageIcon trained;
    private ImageIcon overtime;
    private ImageIcon both;
    private boolean hasOvertime;
    private boolean hasTrained;
    
    /** Creates new form EmployeeIconDisplay */
    public EmployeeIconDisplay(Schedule_View_Panel p) {
        initComponents();
        parent = p;
        Jar_Images ji = Main_Window.parentOfApplication.getJarImage();
        try {
            overtime = new ImageIcon(ji.getImageFromJAR("images/Overtime.png"));
            trained = new ImageIcon(ji.getImageFromJAR("images/Trained.png"));   
        } catch (Exception e) {
            System.out.println("Error loading image in employee info, will not display correctly");
            e.printStackTrace();
        }
    }
    
    public void hasOvertime() {
        hasOvertime = true;
    }
    
    public void hasTrained() {
        hasTrained = true;
    }
    
    public void display() {
        if (hasOvertime && !hasTrained) {
            myIconLabel.setIcon(overtime);
        } else if (hasOvertime && hasTrained) {
            myIconLabel.setIcon(trained);
        } else {
            
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        myIconLabel = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        setMaximumSize(new java.awt.Dimension(18, 18));
        setMinimumSize(new java.awt.Dimension(18, 18));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(18, 18));
        myIconLabel.setToolTipText("");
        myIconLabel.setMaximumSize(new java.awt.Dimension(18, 18));
        myIconLabel.setMinimumSize(new java.awt.Dimension(18, 18));
        myIconLabel.setPreferredSize(new java.awt.Dimension(18, 18));
        add(myIconLabel);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myIconLabel;
    // End of variables declaration//GEN-END:variables
    
}
