/*
 * IndividualConflictingShift.java
 *
 * Created on February 16, 2005, 2:22 PM
 */

package rmischedule.schedule.components;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.util.StaticDateTimeFunctions;
import rmischedule.components.Options;
import rmischedule.main.*;
/**
 *
 * @author  ira
 */
public class IndividualConflictingShift extends javax.swing.JPanel {
    
    /** Creates new form IndividualConflictingShift */
    public IndividualConflictingShift(Record_Set rs, Main_Window mw, boolean MilTime, boolean isShiftOrAvail) {
        initComponents();
        int format;
        
        if (MilTime) {
            format = StaticDateTimeFunctions.STANDARD_FORMAT;
        } else {
            format = StaticDateTimeFunctions.MILITARY_FORMAT;
        }
        if (isShiftOrAvail) {
            displayShiftInfo(rs, format);
        } else {
            displayAvailInfo(rs, format);
        }
    }
    
    private void displayShiftInfo(Record_Set rs, int format) {
        jLabel1.setText(rs.getString("cname"));
        jLabel2.setText(StaticDateTimeFunctions.stringToFormattedTime(rs.getString("start_time"), format));
        jLabel3.setText(StaticDateTimeFunctions.stringToFormattedTime(rs.getString("end_time"), format));
    }
    
    private void displayAvailInfo(Record_Set rs, int format) {
        jLabel1.setText("Employee Is Not Available Between: ");
        jLabel2.setText(StaticDateTimeFunctions.stringToFormattedTime(rs.getString("stime"), format));
        jLabel3.setText(StaticDateTimeFunctions.stringToFormattedTime(rs.getString("etime"), format));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 14));
        add(jLabel1);

        jLabel2.setText("jLabel3");
        jLabel2.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));
        add(jLabel2);

        jLabel3.setText("jLabel4");
        jLabel3.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));
        add(jLabel3);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
}
