/*
 * LegendPanel.java
 *
 * Created on April 6, 2005, 1:16 PM
 */

package rmischedule.schedule.components;
import rmischedule.schedule.components.DShift;
import rmischedule.schedule.Schedule_View_Panel;
/**
 *
 * @author  ira
 */
public class LegendPanel extends javax.swing.JPanel {
    
    private int xoffset = 0;
    private int yoffset = 0;
    
    /** Creates new form LegendPanel */
    public LegendPanel() {
        initComponents();
        SelectedShift.setBackground(SShift.selectedColor);
        TempOpenShift.setBackground(SShift.TempOpenColor);
        PermOpenShift.setBackground(SShift.OpenColor);
        ConflictedShift.setBackground(SShift.ConflictedColor);
        UnconfirmedShift.setBackground(SShift.UnconfirmedColor);
       // TempShift.setBackground(Schedule_View_Panel.shift_color);
        TempShift.setBackground(SShift.TempShiftOpenColor);
        PermShift.setBackground(Schedule_View_Panel.master_color);
        TrainingShift.setBackground(Schedule_View_Panel.training_color);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        SelectShiftCont = new javax.swing.JPanel();
        SelectedShift = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        PermShiftCont = new javax.swing.JPanel();
        PermShift = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        TempShiftCont = new javax.swing.JPanel();
        TempShift = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        OpenShiftCont = new javax.swing.JPanel();
        OpenShift = new javax.swing.JPanel();
        TempOpenShift = new javax.swing.JPanel();
        PermOpenShift = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        ConflictedShiftCont = new javax.swing.JPanel();
        ConflictedShift = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        ConflictedShiftCont1 = new javax.swing.JPanel();
        UnconfirmedShift = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        ConflictedShiftCont2 = new javax.swing.JPanel();
        TrainingShift = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), null));
        setMaximumSize(new java.awt.Dimension(2147483647, 20));
        setMinimumSize(new java.awt.Dimension(176, 20));
        setPreferredSize(new java.awt.Dimension(64, 20));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(217, 213, 227));
        jPanel2.setMaximumSize(new java.awt.Dimension(140, 30));
        jPanel2.setMinimumSize(new java.awt.Dimension(90, 30));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptyHandler(evt);
            }
        });
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(140, 30));
        jPanel5.setMinimumSize(new java.awt.Dimension(90, 30));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel34.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel34.setOpaque(false);
        jPanel5.add(jPanel34);

        SelectShiftCont.setMaximumSize(new java.awt.Dimension(20, 20));
        SelectShiftCont.setMinimumSize(new java.awt.Dimension(20, 20));
        SelectShiftCont.setOpaque(false);
        SelectShiftCont.setPreferredSize(new java.awt.Dimension(20, 20));
        SelectShiftCont.setLayout(new java.awt.GridLayout(1, 0));

        SelectedShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SelectedShift.setMaximumSize(new java.awt.Dimension(10, 32767));
        SelectedShift.setLayout(new java.awt.GridLayout(1, 0));
        SelectShiftCont.add(SelectedShift);

        jPanel5.add(SelectShiftCont);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Selected");
        jPanel5.add(jLabel11);

        jPanel2.add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(140, 30));
        jPanel4.setMinimumSize(new java.awt.Dimension(90, 30));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel43.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel43.setOpaque(false);
        jPanel4.add(jPanel43);

        PermShiftCont.setMaximumSize(new java.awt.Dimension(20, 20));
        PermShiftCont.setMinimumSize(new java.awt.Dimension(20, 20));
        PermShiftCont.setOpaque(false);
        PermShiftCont.setPreferredSize(new java.awt.Dimension(20, 20));
        PermShiftCont.setLayout(new java.awt.GridLayout(1, 0));

        PermShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PermShift.setLayout(new java.awt.GridLayout(1, 0));
        PermShiftCont.add(PermShift);

        jPanel4.add(PermShiftCont);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Permanent");
        jPanel4.add(jLabel14);

        jPanel2.add(jPanel4);

        jPanel6.setMaximumSize(new java.awt.Dimension(140, 30));
        jPanel6.setMinimumSize(new java.awt.Dimension(90, 30));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel47.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel47.setOpaque(false);
        jPanel6.add(jPanel47);

        TempShiftCont.setMaximumSize(new java.awt.Dimension(20, 20));
        TempShiftCont.setMinimumSize(new java.awt.Dimension(20, 20));
        TempShiftCont.setOpaque(false);
        TempShiftCont.setPreferredSize(new java.awt.Dimension(20, 20));
        TempShiftCont.setLayout(new java.awt.GridLayout(1, 0));

        TempShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TempShift.setLayout(new java.awt.GridLayout(1, 0));
        TempShiftCont.add(TempShift);

        jPanel6.add(TempShiftCont);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Temporary");
        jPanel6.add(jLabel16);

        jPanel2.add(jPanel6);

        jPanel3.setMaximumSize(new java.awt.Dimension(140, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(90, 30));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel12.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel12.setOpaque(false);
        jPanel3.add(jPanel12);

        OpenShiftCont.setMaximumSize(new java.awt.Dimension(20, 20));
        OpenShiftCont.setMinimumSize(new java.awt.Dimension(20, 20));
        OpenShiftCont.setOpaque(false);
        OpenShiftCont.setPreferredSize(new java.awt.Dimension(20, 20));
        OpenShiftCont.setLayout(new java.awt.GridLayout(1, 0));

        OpenShift.setLayout(new java.awt.GridLayout(1, 2));

        TempOpenShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        OpenShift.add(TempOpenShift);

        OpenShiftCont.add(OpenShift);

        jPanel3.add(OpenShiftCont);

        PermOpenShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PermOpenShift.setMaximumSize(new java.awt.Dimension(20, 20));
        PermOpenShift.setMinimumSize(new java.awt.Dimension(20, 20));
        PermOpenShift.setPreferredSize(new java.awt.Dimension(20, 20));
        PermOpenShift.setLayout(new java.awt.GridLayout(1, 0));
        jPanel3.add(PermOpenShift);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Open");
        jPanel3.add(jLabel3);

        jPanel2.add(jPanel3);

        jPanel11.setMaximumSize(new java.awt.Dimension(140, 30));
        jPanel11.setMinimumSize(new java.awt.Dimension(90, 30));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jPanel29.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel29.setOpaque(false);
        jPanel11.add(jPanel29);

        ConflictedShiftCont.setMaximumSize(new java.awt.Dimension(20, 20));
        ConflictedShiftCont.setMinimumSize(new java.awt.Dimension(20, 20));
        ConflictedShiftCont.setOpaque(false);
        ConflictedShiftCont.setPreferredSize(new java.awt.Dimension(20, 20));
        ConflictedShiftCont.setLayout(new java.awt.GridLayout(1, 0));

        ConflictedShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ConflictedShift.setLayout(new java.awt.GridLayout(1, 0));
        ConflictedShiftCont.add(ConflictedShift);

        jPanel11.add(ConflictedShiftCont);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Conflicted");
        jPanel11.add(jLabel9);

        jPanel2.add(jPanel11);

        jPanel31.setMaximumSize(new java.awt.Dimension(140, 30));
        jPanel31.setMinimumSize(new java.awt.Dimension(90, 30));
        jPanel31.setOpaque(false);
        jPanel31.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31, javax.swing.BoxLayout.LINE_AXIS));

        jPanel32.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel32.setOpaque(false);
        jPanel31.add(jPanel32);

        ConflictedShiftCont1.setMaximumSize(new java.awt.Dimension(20, 20));
        ConflictedShiftCont1.setMinimumSize(new java.awt.Dimension(20, 20));
        ConflictedShiftCont1.setOpaque(false);
        ConflictedShiftCont1.setPreferredSize(new java.awt.Dimension(20, 20));
        ConflictedShiftCont1.setLayout(new java.awt.GridLayout(1, 0));

        UnconfirmedShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        UnconfirmedShift.setLayout(new java.awt.GridLayout(1, 0));
        ConflictedShiftCont1.add(UnconfirmedShift);

        jPanel31.add(ConflictedShiftCont1);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Unconfirmed");
        jPanel31.add(jLabel10);

        jPanel2.add(jPanel31);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel36.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel36.setOpaque(false);
        jPanel1.add(jPanel36);

        ConflictedShiftCont2.setMaximumSize(new java.awt.Dimension(20, 30));
        ConflictedShiftCont2.setMinimumSize(new java.awt.Dimension(20, 30));
        ConflictedShiftCont2.setOpaque(false);
        ConflictedShiftCont2.setPreferredSize(new java.awt.Dimension(20, 30));
        ConflictedShiftCont2.setLayout(new java.awt.GridLayout(1, 0));

        TrainingShift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TrainingShift.setLayout(new java.awt.GridLayout(1, 0));
        ConflictedShiftCont2.add(TrainingShift);

        jPanel1.add(ConflictedShiftCont2);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Training ");
        jPanel1.add(jLabel12);

        jPanel2.add(jPanel1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        jLabel1.setText("SHIFT LEGEND");
        jLabel1.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(85, 14));
        add(jLabel1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Empty method so that mouseEvent is caught and not trickled down to schedule....
     */
    private void emptyHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyHandler
        return;
    }//GEN-LAST:event_emptyHandler
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConflictedShift;
    private javax.swing.JPanel ConflictedShiftCont;
    private javax.swing.JPanel ConflictedShiftCont1;
    private javax.swing.JPanel ConflictedShiftCont2;
    private javax.swing.JPanel OpenShift;
    private javax.swing.JPanel OpenShiftCont;
    private javax.swing.JPanel PermOpenShift;
    private javax.swing.JPanel PermShift;
    private javax.swing.JPanel PermShiftCont;
    private javax.swing.JPanel SelectShiftCont;
    private javax.swing.JPanel SelectedShift;
    private javax.swing.JPanel TempOpenShift;
    private javax.swing.JPanel TempShift;
    private javax.swing.JPanel TempShiftCont;
    private javax.swing.JPanel TrainingShift;
    private javax.swing.JPanel UnconfirmedShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
    
}
