/*
 * SearchPanel.java
 *
 * Created on July 8, 2005, 10:56 AM
 */

package rmischedule.schedule.components;
import rmischedule.schedule.Schedule_View_Panel;
import java.awt.KeyboardFocusManager;
import java.util.*;
import javax.swing.event.*;
import java.awt.event.*;
import rmischedule.main.Main_Window;
/**
 *
 * @author  ira
 */
public class SearchPanel extends javax.swing.JPanel {
    
    private Schedule_View_Panel Parent;

    /** Creates new form SearchPanel */
    public SearchPanel(Schedule_View_Panel parent) {
        initComponents();
        this.setBackground(Schedule_View_Panel.hcol_color);
        Parent = parent;
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
        ClientSearchField.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                Parent.searchClientAndEmployees(ClientSearchField.getText(), true);
            }

            public void removeUpdate(DocumentEvent e) {
                Parent.searchClientAndEmployees(ClientSearchField.getText(), true);
            }

            public void changedUpdate(DocumentEvent e) {
                Parent.searchClientAndEmployees(ClientSearchField.getText(), true);
            }

        });

        ClientSearchField.addKeyListener(new KeyListener() {

            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    Parent.searchClientAndEmployees(ClientSearchField.getText(), false);
                }
            }

            public void keyTyped(KeyEvent e) {

            }

            public void keyReleased(KeyEvent e) {
                
            }
        });

        if (Main_Window.isClientLoggedIn() || Main_Window.isEmployeeLoggedIn()) {
            this.jPanel1.setVisible(false);
            this.jPanel3.setVisible(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ClientSearchField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(46, 40));
        setPreferredSize(new java.awt.Dimension(46, 40));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        panel2.setText("Search ");
        panel2.setToolTipText("Enter the name of the employee");
        panel2.setMaximumSize(new java.awt.Dimension(80, 15));
        panel2.setMinimumSize(new java.awt.Dimension(80, 15));
        jPanel3.add(panel2);

        add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        ClientSearchField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClientSearchField.setMaximumSize(new java.awt.Dimension(2147483647, 18));
        jPanel1.add(ClientSearchField);
        jPanel1.add(jPanel2);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClientSearchField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel panel2;
    // End of variables declaration//GEN-END:variables
    
}
