/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rmischedule.event_log;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import rmischedule.main.Main_Window;
import rmischeduleserver.control.EventController;
import rmischeduleserver.control.UserController;
import schedfoxlib.model.EventType;
import schedfoxlib.model.Group;

/**
 *
 * @author ira
 */
public class EventTypeContactDialog extends javax.swing.JDialog {

    private EventTypeComboModel eventTypeModel = new EventTypeComboModel();
    private HashMap<Integer, JCheckBox> checks;
    private String companyId;
    
    /**
     * Creates new form EventTypeContactDialog
     */
    public EventTypeContactDialog(java.awt.Frame parent, boolean modal, String companyId) {
        super(parent, modal);
        initComponents();
        
        this.companyId = companyId;
        
        try {
            EventController eventController = new EventController(companyId);
            ArrayList<EventType> types = eventController.getEventTypes(1);
            for (int t = 0; t < types.size(); t++) {
                eventTypeModel.addEventType(types.get(t));
            }
        } catch (Exception exe) {}
        
        try {
            checks = new HashMap<Integer, JCheckBox>();
            UserController userController = new UserController(companyId);
            ArrayList<Group> groups = userController.getGroups();
            for (int g = 0; g < groups.size(); g++) {
                JCheckBox groupCheck = new JCheckBox(groups.get(g).getGroupName());
                groupPanel.add(groupCheck);
                checks.put(groups.get(g).getGroupId(), groupCheck);
            }
        } catch (Exception exe) {}
        
        loadData();
    }

    private void loadData() {
        Iterator<Integer> keys = checks.keySet().iterator();
        while (keys.hasNext()) {
            Integer key = keys.next();
            checks.get(key).setSelected(false);
        }
        
        try {
            EventType selType = (EventType)eventTypeModel.getElementAt(eventCombo.getSelectedIndex());
            
            EventController eventController = new EventController(this.companyId);
            ArrayList<Group> groups = eventController.getGroupsForEventType(selType.getEventTypeId());
            keys = checks.keySet().iterator();
            while (keys.hasNext()) {
                Integer key = keys.next();
                for (int g = 0; g < groups.size(); g++) {
                    if (groups.get(g).getGroupId() == key) {
                        checks.get(key).setSelected(true);
                    }
                }
            }
        } catch (Exception exe) {}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eventCombo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        groupPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Event Type Dialog");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 32));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 32));
        jPanel1.setPreferredSize(new java.awt.Dimension(449, 32));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Event Type");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 16));
        jPanel1.add(jLabel1);

        eventCombo.setModel(eventTypeModel);
        eventCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventComboActionPerformed(evt);
            }
        });
        jPanel1.add(eventCombo);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(75, 160));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel2.setText("Groups");
        jLabel2.setMaximumSize(new java.awt.Dimension(75, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(75, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 16));
        jPanel5.add(jLabel2);

        jPanel2.add(jPanel5);

        groupPanel.setPreferredSize(new java.awt.Dimension(10, 195));
        groupPanel.setLayout(new java.awt.GridLayout(0, 3));
        jPanel2.add(groupPanel);

        getContentPane().add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 36));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 36));
        jPanel3.setPreferredSize(new java.awt.Dimension(449, 36));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(closeBtn))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        setSize(new java.awt.Dimension(467, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Iterator<Integer> keys = checks.keySet().iterator();
        ArrayList<Integer> groupIds = new ArrayList<Integer>();
        while (keys.hasNext()) {
            Integer key = keys.next();
            if (checks.get(key).isSelected()) {
                groupIds.add(key);
            }
        }
        try {
            EventType selType = (EventType)eventTypeModel.getElementAt(eventCombo.getSelectedIndex());
            
            EventController eventController = new EventController(this.companyId);
            eventController.saveGroupsToEventType(selType.getEventTypeId(), groupIds);
        } catch (Exception exe) {}
        
        JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Events saved to groups!", "Events saved to group!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void eventComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventComboActionPerformed
        loadData();
    }//GEN-LAST:event_eventComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JComboBox eventCombo;
    private javax.swing.JPanel groupPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
