/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rmischedule.event_log;

import java.awt.CardLayout;
import java.util.ArrayList;
import rmischeduleserver.control.UserController;
import schedfoxlib.model.Group;
import schedfoxlib.model.User;

/**
 *
 * @author ira
 */
public class RequestEventFollowupDialog extends javax.swing.JDialog {

    private UserComboModel userModel = new UserComboModel();
    private GroupComboModel groupModel = new GroupComboModel();
    
    private Group selectedGroup;
    private User selectedUser;
    private Boolean wasSaved;
    
    /**
     * Creates new form RequestEventFollowupDialog
     */
    public RequestEventFollowupDialog(java.awt.Frame parent, boolean modal, String companyId, Integer eventId) {
        super(parent, modal);
        initComponents();
        
        try {
            UserController userController = new UserController(companyId); 
            ArrayList<User> users = userController.getUsersByCompany(Integer.parseInt(companyId));
            for (int u = 0; u < users.size(); u++) {
                userModel.addUser(users.get(u));
            }
            
            ArrayList<Group> groups = userController.getGroups();
            for (int g = 0; g < groups.size(); g++) {
                groupModel.addGroup(groups.get(g));
            }
            
            ((CardLayout)mainPanel.getLayout()).show(mainPanel, "anyone");
        } catch (Exception exe) {}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        mainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        groupPanel = new javax.swing.JPanel();
        groupCombo = new javax.swing.JComboBox();
        userPanel = new javax.swing.JPanel();
        userCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(408, 35));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Request followup from");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel1.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anyone", "A particular user", "A group of users" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(32767, 28));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);

        getContentPane().add(jPanel1);

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel4, "anyone");

        groupCombo.setModel(groupModel);
        groupCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groupPanelLayout = new javax.swing.GroupLayout(groupPanel);
        groupPanel.setLayout(groupPanelLayout);
        groupPanelLayout.setHorizontalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        groupPanelLayout.setVerticalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(groupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainPanel.add(groupPanel, "group");

        userCombo.setModel(userModel);
        userCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainPanel.add(userPanel, "user");

        getContentPane().add(mainPanel);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Save Followup Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3);

        setSize(new java.awt.Dimension(379, 192));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().equals("Anyone")) {
            ((CardLayout)mainPanel.getLayout()).show(mainPanel, "anyone");
        } else if (jComboBox1.getSelectedItem().equals("A group of users")) {
            ((CardLayout)mainPanel.getLayout()).show(mainPanel, "group");
        } else {
            ((CardLayout)mainPanel.getLayout()).show(mainPanel, "user");
        }
        selectedGroup = null;
        selectedUser = null;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void groupComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupComboActionPerformed
        try {
            selectedGroup = (Group)groupModel.getElementAt(groupCombo.getSelectedIndex());
            selectedUser = null;
        } catch (Exception exe) {}
    }//GEN-LAST:event_groupComboActionPerformed

    private void userComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboActionPerformed
        try {
            selectedUser = (User)userModel.getElementAt(userCombo.getSelectedIndex());
            selectedGroup = null;
        } catch (Exception exe) {}
    }//GEN-LAST:event_userComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.wasSaved = true;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox groupCombo;
    private javax.swing.JPanel groupPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox userCombo;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the selectedGroup
     */
    public Group getSelectedGroup() {
        return selectedGroup;
    }

    /**
     * @param selectedGroup the selectedGroup to set
     */
    public void setSelectedGroup(Group selectedGroup) {
        this.selectedGroup = selectedGroup;
    }

    /**
     * @return the selectedUser
     */
    public User getSelectedUser() {
        return selectedUser;
    }

    /**
     * @param selectedUser the selectedUser to set
     */
    public void setSelectedUser(User selectedUser) {
        this.selectedUser = selectedUser;
    }

    /**
     * @return the wasSaved
     */
    public Boolean getWasSaved() {
        return wasSaved;
    }

    /**
     * @param wasSaved the wasSaved to set
     */
    public void setWasSaved(Boolean wasSaved) {
        this.wasSaved = wasSaved;
    }
}
