/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicCompanyInformationSubScreen.java
 *
 * Created on Jun 24, 2010, 2:20:48 PM
 */

package rmischedule.new_user;

import java.awt.Color;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.event.ListDataListener;
import javax.swing.text.MaskFormatter;
import rmischedule.data_connection.Connection;
import rmischedule.main.Main_Window;
import rmischedule.utility.TextField;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.new_user.get_industry_types_query;
//import rmischeduleserver.mysqlconnectivity.queries.new_user.get_industry_types_query;

/**
 *
 * @author user
 */
public class BasicCompanyInformationSubScreen extends javax.swing.JPanel implements NewUserSubScreen {

    private MaskFormatter phoneFormatter = null;
    private Vector<IndustryType> industryTypesColl;

    /** Creates new form BasicCompanyInformationSubScreen */
    public BasicCompanyInformationSubScreen() {
        try {
            phoneFormatter = new MaskFormatter("(###)###-####");
            phoneFormatter.setPlaceholder(" ");
        } catch (Exception e) {
            e.printStackTrace();
            phoneFormatter = new MaskFormatter();
        }
        initComponents();

        industryTypesColl = new Vector<IndustryType>();
        get_industry_types_query industryTypes = new get_industry_types_query();
        Connection myConn = new Connection();
        Record_Set rst = myConn.executeQuery(industryTypes);
        for (int r = 0; r < rst.length(); r++) {
            IndustryType industryType = new IndustryType(rst.getInt("industry_type_id"), rst.getString("industry"));
            industryTypesColl.add(industryType);
            rst.moveNext();
        }
    }

    private void resetErrors() {
        nameError.setIcon(null);
        phoneError.setIcon(null);
        addressError.setIcon(null);
        cityError.setIcon(null);
        phoneError.setIcon(null);
        websiteError.setIcon(null);
        companyError.setIcon(null);

        companyNameTxt.setBackground(Color.WHITE);
        phoneTxt.setBackground(Color.WHITE);
        addressTxt.setBackground(Color.WHITE);
        cityTxt.setBackground(Color.WHITE);
        stateTxt.setBackground(Color.WHITE);
        zipTxt.setBackground(Color.WHITE);
        phoneTxt.setBackground(Color.WHITE);
        websiteTxt.setBackground(Color.WHITE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        companyNameTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stateTxt = TextField.getStateTextField();
        jLabel5 = new javax.swing.JLabel();
        zipTxt = TextField.getZipTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        websiteTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        industryType = new javax.swing.JComboBox();
        rightPanel = new javax.swing.JPanel();
        nameError = new javax.swing.JLabel();
        addressError = new javax.swing.JLabel();
        cityError = new javax.swing.JLabel();
        phoneError = new javax.swing.JLabel();
        websiteError = new javax.swing.JLabel();
        companyError = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tell us about your company"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        leftPanel.setMaximumSize(new java.awt.Dimension(2147483647, 20000));
        leftPanel.setLayout(new javax.swing.BoxLayout(leftPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(10000, 36));
        jPanel1.setMinimumSize(new java.awt.Dimension(130, 32));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Company Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel1.add(jLabel1);

        companyNameTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel1.add(companyNameTxt);

        leftPanel.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel2.setMaximumSize(new java.awt.Dimension(10000, 36));
        jPanel2.setMinimumSize(new java.awt.Dimension(130, 32));
        jPanel2.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Address");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel2.add(jLabel2);

        addressTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel2.add(addressTxt);

        leftPanel.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel3.setMaximumSize(new java.awt.Dimension(10000, 36));
        jPanel3.setMinimumSize(new java.awt.Dimension(130, 32));
        jPanel3.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("City");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel3.add(jLabel3);

        cityTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel3.add(cityTxt);

        jLabel4.setText("State");
        jPanel3.add(jLabel4);

        stateTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel3.add(stateTxt);

        jLabel5.setText("Zip");
        jPanel3.add(jLabel5);

        zipTxt.setMaximumSize(new java.awt.Dimension(55, 26));
        zipTxt.setMinimumSize(new java.awt.Dimension(55, 20));
        zipTxt.setPreferredSize(new java.awt.Dimension(55, 20));
        jPanel3.add(zipTxt);

        leftPanel.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel4.setMaximumSize(new java.awt.Dimension(10000, 36));
        jPanel4.setMinimumSize(new java.awt.Dimension(130, 32));
        jPanel4.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Phone");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel4.add(jLabel6);

        phoneTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel4.add(phoneTxt);

        leftPanel.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel5.setMaximumSize(new java.awt.Dimension(10000, 36));
        jPanel5.setMinimumSize(new java.awt.Dimension(130, 32));
        jPanel5.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText("Website");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel5.add(jLabel7);

        websiteTxt.setText("http://www.");
        websiteTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel5.add(websiteTxt);

        leftPanel.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel6.setMaximumSize(new java.awt.Dimension(10000, 36));
        jPanel6.setMinimumSize(new java.awt.Dimension(130, 32));
        jPanel6.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("Company Size");
        jLabel8.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel6.add(jLabel8);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Under 10 Employees", "10 to 50 Employees", "50 to 100 Employees", "100 to 500 Employees", "500 to 1000 Employees", "1000+ Employees" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(32767, 26));
        jPanel6.add(jComboBox1);

        leftPanel.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel7.setMaximumSize(new java.awt.Dimension(10000, 36));
        jPanel7.setMinimumSize(new java.awt.Dimension(130, 32));
        jPanel7.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setText("Company Type");
        jLabel9.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel7.add(jLabel9);

        industryType.setModel(new IndustryTypeModel());
        industryType.setMaximumSize(new java.awt.Dimension(32767, 26));
        jPanel7.add(industryType);

        leftPanel.add(jPanel7);

        add(leftPanel);

        rightPanel.setMaximumSize(new java.awt.Dimension(25, 32767));
        rightPanel.setMinimumSize(new java.awt.Dimension(25, 0));
        rightPanel.setPreferredSize(new java.awt.Dimension(25, 270));
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.Y_AXIS));

        nameError.setMaximumSize(new java.awt.Dimension(24, 24));
        nameError.setMinimumSize(new java.awt.Dimension(24, 24));
        nameError.setPreferredSize(new java.awt.Dimension(24, 24));
        rightPanel.add(nameError);

        addressError.setMaximumSize(new java.awt.Dimension(24, 24));
        addressError.setMinimumSize(new java.awt.Dimension(24, 24));
        addressError.setPreferredSize(new java.awt.Dimension(24, 24));
        rightPanel.add(addressError);

        cityError.setMaximumSize(new java.awt.Dimension(24, 24));
        cityError.setMinimumSize(new java.awt.Dimension(24, 24));
        cityError.setPreferredSize(new java.awt.Dimension(24, 24));
        rightPanel.add(cityError);

        phoneError.setMaximumSize(new java.awt.Dimension(24, 24));
        phoneError.setMinimumSize(new java.awt.Dimension(24, 24));
        phoneError.setPreferredSize(new java.awt.Dimension(24, 24));
        rightPanel.add(phoneError);

        websiteError.setMaximumSize(new java.awt.Dimension(24, 24));
        websiteError.setMinimumSize(new java.awt.Dimension(24, 24));
        websiteError.setPreferredSize(new java.awt.Dimension(24, 24));
        rightPanel.add(websiteError);

        companyError.setMaximumSize(new java.awt.Dimension(24, 24));
        companyError.setMinimumSize(new java.awt.Dimension(24, 24));
        companyError.setPreferredSize(new java.awt.Dimension(24, 24));
        rightPanel.add(companyError);

        add(rightPanel);
    }// </editor-fold>//GEN-END:initComponents

    public Hashtable<String, Object> getValues() {
        String companyName = companyNameTxt.getText().trim().replaceAll("'", "''");
        String phoneNumber = phoneTxt.getText().trim().replaceAll("'", "''");
        String address = addressTxt.getText().trim().replaceAll("'", "''");
        String city = cityTxt.getText().trim().replaceAll("'", "''");
        String state = stateTxt.getText().trim().replaceAll("'", "''");
        String zip = zipTxt.getText().trim().replaceAll("'", "''");
        String website = websiteTxt.getText().trim().replaceAll("'", "''");

        NewCompany company = new NewCompany();
        company.setCompanyAddress(address);
        company.setCompanyCity(city);
        company.setCompanyName(companyName);
        company.setCompanyPhone(phoneNumber);
        company.setCompanyState(state);
        company.setCompanyWebsite(website);
        company.setCompanyZip(zip);

        Hashtable<String, Object> retVal = new Hashtable<String, Object>();
        retVal.put("company", company);
        return retVal;
    }

    public ArrayList<String> getValidationString() {
        resetErrors();
        ArrayList<String> retVal = new ArrayList<String>();

        String companyName = companyNameTxt.getText().trim();
        String address = addressTxt.getText().trim();
        String phoneNumber = phoneTxt.getText().trim();
        String city = cityTxt.getText().trim();
        String state = stateTxt.getText().trim();
        String zip = zipTxt.getText().trim();
        String website = websiteTxt.getText().trim();
        
        if (companyName.length() <= 0) {
            retVal.add("A company name is required!");
            nameError.setIcon(Main_Window.Medium_Error_Icon);
            companyNameTxt.setBackground(Main_Window.redInputColor);
        }
        if (address.length() <= 0) {
            retVal.add("A company address is required!");
            addressError.setIcon(Main_Window.Medium_Error_Icon);
            addressTxt.setBackground(Main_Window.redInputColor);
        }
        if (phoneNumber.length() <= 0) {
            retVal.add("A phone number is required!");
            phoneError.setIcon(Main_Window.Medium_Error_Icon);
            phoneTxt.setBackground(Main_Window.redInputColor);
        }
        if (state.length() <= 0) {
            retVal.add("A state is required!");
            cityError.setIcon(Main_Window.Medium_Error_Icon);
            stateTxt.setBackground(Main_Window.redInputColor);
        }
        if (city.length() <= 0) {
            retVal.add("A city is required!");
            cityError.setIcon(Main_Window.Medium_Error_Icon);
            cityTxt.setBackground(Main_Window.redInputColor);
        }
        if (zip.length() <= 0) {
            retVal.add("A zip is required!");
            cityError.setIcon(Main_Window.Medium_Error_Icon);
            zipTxt.setBackground(Main_Window.redInputColor);
        }
        
        return retVal;
    }

    public Container getContainer() {
        return this;
    }

    private class IndustryType {

        private int id;
        private String industry;

        public IndustryType(int id, String industry) {
            this.id = id;
            this.industry = industry;
        }

        public int getId() {
            return id;
        }

        public String getIndustry() {
            return industry;
        }

        @Override
        public String toString() {
            return industry;
        }
    }

    private class IndustryTypeModel implements ComboBoxModel {

        private int selectedIndex = -1;

        public void setSelectedItem(Object anItem) {
            if (anItem instanceof IndustryType) {
                IndustryType selected = (IndustryType)anItem;
                for (int i = 0; i < industryTypesColl.size(); i++) {
                    if (industryTypesColl.get(i).getId() == selected.getId()) {
                        selectedIndex = i;
                    }
                }
            }
        }

        public Object getSelectedItem() {
            if (selectedIndex >= 0 && selectedIndex < industryTypesColl.size()) {
                return industryTypesColl.get(selectedIndex);
            } else {
                return new IndustryType(0, "Please select an industry!");
            }
        }

        public int getSize() {
           return industryTypesColl.size();
        }

        public Object getElementAt(int index) {
            return industryTypesColl.get(index);
        }

        public void addListDataListener(ListDataListener l) {

        }

        public void removeListDataListener(ListDataListener l) {
            
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressError;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel cityError;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel companyError;
    private javax.swing.JTextField companyNameTxt;
    private javax.swing.JComboBox industryType;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel nameError;
    private javax.swing.JLabel phoneError;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JLabel websiteError;
    private javax.swing.JTextField websiteTxt;
    private javax.swing.JFormattedTextField zipTxt;
    // End of variables declaration//GEN-END:variables

}
