/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseTemplateSubScreen.java
 *
 * Created on Jul 21, 2010, 12:51:27 PM
 */

package rmischedule.new_user;

import java.awt.Container;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.event.ListDataListener;
import rmischedule.data_connection.Connection;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.new_user.get_templates_query;
//import rmischeduleserver.mysqlconnectivity.queries.new_user.get_templates_query;

/**
 *
 * @author user
 */
public class ChooseTemplateSubScreen extends javax.swing.JPanel implements NewUserSubScreen {

    private Vector<TemplateDatabase> tempDatabases;

    /** Creates new form ChooseTemplateSubScreen */
    public ChooseTemplateSubScreen() {
        tempDatabases = new Vector<TemplateDatabase>();
        initComponents();
        
        get_templates_query tempQuery = new get_templates_query();
        Connection myConn = new Connection();
        Record_Set rst = myConn.executeQuery(tempQuery);
        for (int r = 0; r < rst.length(); r++) {
            TemplateDatabase tempDatabase = new TemplateDatabase(rst.getInt("template_database_id"), rst.getString("template_database_name"),
                    rst.getString("template_database_description"), rst.getString("template_database"));
            tempDatabases.add(tempDatabase); 
            rst.moveNext();
        }
        this.setSelectedItem();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        templateInfoTxt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        templateCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Template Information")));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jTextPane1.setBorder(null);
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextPane1.setText("Schedfox can be configured with a number of templates if so desired. These templates are used to insert in existing data so that you can hit the ground running with existing data before entering in your own information. Or if you prefer you can choose not to use a template and get a clean slate to insert your own information. Simply make your selection below. ");
        jTextPane1.setOpaque(false);
        jPanel2.add(jTextPane1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        templateInfoTxt.setColumns(20);
        templateInfoTxt.setEditable(false);
        templateInfoTxt.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        templateInfoTxt.setForeground(new java.awt.Color(51, 0, 204));
        templateInfoTxt.setLineWrap(true);
        templateInfoTxt.setRows(5);
        templateInfoTxt.setWrapStyleWord(true);
        templateInfoTxt.setOpaque(false);
        jPanel2.add(templateInfoTxt);

        add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Selected Template");
        jPanel4.add(jLabel1);

        jPanel5.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel5.setMinimumSize(new java.awt.Dimension(10, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(10, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        templateCombo.setModel(new TemplateDatabaseModel());
        templateCombo.setMaximumSize(new java.awt.Dimension(32767, 20));
        templateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templateComboActionPerformed(evt);
            }
        });
        jPanel4.add(templateCombo);

        jPanel1.add(jPanel4);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(jPanel3);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void setSelectedItem() {
        TemplateDatabase selDB = (TemplateDatabase)templateCombo.getSelectedItem();
        templateInfoTxt.setText(selDB.getDescription());
    }

    private void templateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templateComboActionPerformed
        this.setSelectedItem();
    }//GEN-LAST:event_templateComboActionPerformed

    public Hashtable<String, Object> getValues() {
         Hashtable<String, Object> values = new Hashtable<String, Object>();
         TemplateDatabase selDB = (TemplateDatabase)templateCombo.getSelectedItem();
         values.put("database", selDB.getDatabase());
         return values;
    }

    public ArrayList<String> getValidationString() {
        return new ArrayList<String>();
    }

    public Container getContainer() {
        return this;
    }

    private class TemplateDatabase {
        private int id;
        private String name;
        private String description;
        private String database;

        public TemplateDatabase(int id, String name, String description, String database) {
            this.id = id;
            this.name = name;
            this.description = description;
            this.database = database;
        }

        /**
         * @return the id
         */
        public int getId() {
            return id;
        }

        /**
         * @return the name
         */
        public String getName() {
            return name;
        }

        /**
         * @return the description
         */
        public String getDescription() {
            return description;
        }

        /**
         * @return the database
         */
        public String getDatabase() {
            return database;
        }

        @Override
        public String toString() {
            return this.name;
        }

    }


    private class TemplateDatabaseModel implements ComboBoxModel {

        private int selectedIndex = 0;

        public void setSelectedItem(Object anItem) {
            if (anItem instanceof TemplateDatabase) {
                TemplateDatabase selected = (TemplateDatabase)anItem;
                for (int i = 0; i < tempDatabases.size(); i++) {
                    if (tempDatabases.get(i).getId() == selected.getId()) {
                        selectedIndex = i;
                    }
                }
            }
        }

        public Object getSelectedItem() {
            if (selectedIndex >= 0 && selectedIndex < tempDatabases.size()) {
                return tempDatabases.get(selectedIndex);
            } else {
                return new TemplateDatabase(0, "", "", "");
            }
        }

        public int getSize() {
           return tempDatabases.size();
        }

        public Object getElementAt(int index) {
            return tempDatabases.get(index);
        }

        public void addListDataListener(ListDataListener l) {

        }

        public void removeListDataListener(ListDataListener l) {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox templateCombo;
    private javax.swing.JTextArea templateInfoTxt;
    // End of variables declaration//GEN-END:variables

}
