/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapExportFieldsDialog.java
 *
 * Created on Sep 13, 2010, 3:59:48 PM
 */

package rmischedule.importexportData;

import rmischeduleserver.control.model.BoundMappings;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MapExportFieldsDialog extends javax.swing.JDialog {

    private Vector<String> unusedMappings;
    private Vector<String> unrecognizedMappings;
    private Vector<BoundMappings> boundMappings;
    private java.awt.Frame myParent;
    private boolean nextWasPressed = false;

    /** Creates new form MapExportFieldsDialog */
    public MapExportFieldsDialog(java.awt.Frame parent, boolean modal, Vector<String> unusedMappings, Vector<String> unrecognizedMappings) {
        super(parent, modal);
        initComponents();
        this.myParent = parent;
        this.unrecognizedMappings = unrecognizedMappings;
        this.unusedMappings = unusedMappings;
        this.boundMappings = new Vector<BoundMappings>();

        unmappedList.setListData(this.unusedMappings);
        unreclist.setListData(this.unrecognizedMappings);
        mappedList.setListData(this.boundMappings);
    }

    public boolean isNextWasPressed() {
        return this.nextWasPressed;
    }

    public void addMapping() {
        int selIndex1 = unmappedList.getSelectedIndex();
        int selIndex2 = unreclist.getSelectedIndex();
        if (selIndex1 == -1) {
            JOptionPane.showMessageDialog(myParent, "You must select a value from the Unused Column section " +
                    "to proceed with mapping!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (selIndex2 == -1) {
            JOptionPane.showMessageDialog(myParent, "You must select a value from the Unmapped Column section " +
                    "to proceed with mapping!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            BoundMappings myBoundMapping = new BoundMappings(unusedMappings.get(selIndex1), unrecognizedMappings.get(selIndex2));
            unusedMappings.remove(selIndex1);
            unrecognizedMappings.remove(selIndex2);
            boundMappings.add(myBoundMapping);
            mappedList.setListData(this.boundMappings);
            unmappedList.setListData(this.unusedMappings);
            unreclist.setListData(this.unrecognizedMappings);
        }
    }

    public void removeMapping() {
        int selIndex1 = mappedList.getSelectedIndex();
        if (selIndex1 == -1) {
            JOptionPane.showMessageDialog(myParent, "You must select a mapped value from the Mapped Values section " +
                    "to remove the mapping!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            BoundMappings mapping = boundMappings.get(selIndex1);
            unusedMappings.add(mapping.getUnusedMapping());
            unrecognizedMappings.add(mapping.getUnrecognizedMapping());
            unmappedList.setListData(this.unusedMappings);
            unreclist.setListData(this.unrecognizedMappings);
            boundMappings.remove(selIndex1);
            mappedList.setListData(this.boundMappings);
        }
    }

    public Vector<BoundMappings> getBoundMappings() {
        return this.boundMappings;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        unreclist = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        unmappedList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        addMappingBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mappedList = new javax.swing.JList();
        jPanel8 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 5));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(536, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("There were some columns supplied in the file you imported that could not be detected by Schedfox. These columns in your file that are unrecognized are listed below in the \"Unrecoginzed Columns\" field. Please match these to the, \"Unused Columns\" values and click add mapping to establish what fields these values should be placed in and click, \"Next\" when you are ready to continue.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jPanel1.add(jTextArea1);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Unused Columns"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        unreclist.setMaximumSize(new java.awt.Dimension(145, 8000));
        unreclist.setMinimumSize(new java.awt.Dimension(145, 80));
        unreclist.setPreferredSize(new java.awt.Dimension(145, 80));
        jScrollPane2.setViewportView(unreclist);

        jPanel5.add(jScrollPane2);

        jPanel3.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Unrecoginized Columns"));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        unmappedList.setMaximumSize(new java.awt.Dimension(145, 8000));
        unmappedList.setMinimumSize(new java.awt.Dimension(145, 80));
        unmappedList.setPreferredSize(new java.awt.Dimension(145, 80));
        jScrollPane1.setViewportView(unmappedList);

        jPanel6.add(jScrollPane1);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        addMappingBtn.setText("Add Mapping");
        addMappingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMappingBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove Mapping");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMappingBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(addMappingBtn)
                .addGap(41, 41, 41)
                .addComponent(removeBtn)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Mapped Values"));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        mappedList.setMaximumSize(new java.awt.Dimension(145, 8000));
        mappedList.setMinimumSize(new java.awt.Dimension(145, 80));
        mappedList.setPreferredSize(new java.awt.Dimension(145, 80));
        jScrollPane3.setViewportView(mappedList);

        jPanel10.add(jScrollPane3);

        jPanel2.add(jPanel10);

        getContentPane().add(jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel8.setMaximumSize(new java.awt.Dimension(32887, 35));
        jPanel8.setMinimumSize(new java.awt.Dimension(220, 35));
        jPanel8.setPreferredSize(new java.awt.Dimension(613, 35));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        cancelBtn.setText("Cancel");
        cancelBtn.setMaximumSize(new java.awt.Dimension(80, 24));
        cancelBtn.setMinimumSize(new java.awt.Dimension(80, 24));
        cancelBtn.setPreferredSize(new java.awt.Dimension(80, 24));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel8.add(cancelBtn);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9);

        nextBtn.setText("Next");
        nextBtn.setMaximumSize(new java.awt.Dimension(80, 24));
        nextBtn.setMinimumSize(new java.awt.Dimension(80, 24));
        nextBtn.setPreferredSize(new java.awt.Dimension(80, 24));
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel8.add(nextBtn);

        getContentPane().add(jPanel8);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-642)/2, (screenSize.height-427)/2, 642, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void addMappingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMappingBtnActionPerformed
        this.addMapping();
    }//GEN-LAST:event_addMappingBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        this.nextWasPressed = true;
        this.dispose();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        this.removeMapping();
    }//GEN-LAST:event_removeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMappingBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList mappedList;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JList unmappedList;
    private javax.swing.JList unreclist;
    // End of variables declaration//GEN-END:variables

}
