/*
 * SingleNoteDisplay.java
 *
 * Created on February 13, 2006, 8:38 AM
 */

package rmischedule.schedule.components.notes;
import java.text.SimpleDateFormat;
import java.util.*;
import rmischedule.components.*;
/**
 *
 * @author  Ira Juneau
 */
public class SingleNoteDisplay extends javax.swing.JPanel {
    
    /** Creates new form SingleNoteDisplay */
    public SingleNoteDisplay() {
        initComponents();
    }
    
    public SingleNoteDisplay(NoteData note) {
        initComponents();
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        SimpleDateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        NoteLabel.setText(note.getNote());
        UserNameLabel.setText(note.getUserLogin());
        DateLabel.setText(dateFormat.format(note.getDate()));
        try {
            TimeLabel.setText(hourFormat.format(note.getDate()));
        } catch (Exception e) {}
        NoteTypeLabel.setText(note.getNoteType());
    }
    
    public String getNote() {
        return NoteLabel.getText();
    }
    
    public String getUser() {
        return UserNameLabel.getText();
    }
    
    public String getDate() {
        return DateLabel.getText();
    }
    
    public String getTime() {
        return TimeLabel.getText();
    }
    
    public String getNoteType() {
        return NoteTypeLabel.getText();
    }
    
    /**
     * Useful for creating a copy of a note...
     */
    public SingleNoteDisplay(SingleNoteDisplay noteToCopy) {
        initComponents();
        NoteLabel.setText(noteToCopy.getNote());
        UserNameLabel.setText(noteToCopy.getUser());
        DateLabel.setText(noteToCopy.getDate());
        TimeLabel.setText(noteToCopy.getTime());
        NoteTypeLabel.setText(noteToCopy.getNoteType());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        UserNameLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NoteTypeLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NoteLabel = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 5, 5));
        setMaximumSize(new java.awt.Dimension(240, 180));
        setMinimumSize(new java.awt.Dimension(240, 180));
        setPreferredSize(new java.awt.Dimension(240, 180));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 40));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setOpaque(false);
        UserNameLabel.setMaximumSize(new java.awt.Dimension(3400, 14));
        jPanel3.add(UserNameLabel);

        DateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DateLabel.setText("02-01-2005");
        DateLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        DateLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        DateLabel.setPreferredSize(new java.awt.Dimension(90, 14));
        jPanel3.add(DateLabel);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel4.setOpaque(false);
        jLabel5.setText("Note Type   ");
        jPanel4.add(jLabel5);

        NoteTypeLabel.setMaximumSize(new java.awt.Dimension(3004, 14));
        jPanel4.add(NoteTypeLabel);

        TimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TimeLabel.setMaximumSize(new java.awt.Dimension(90, 14));
        TimeLabel.setMinimumSize(new java.awt.Dimension(90, 14));
        TimeLabel.setPreferredSize(new java.awt.Dimension(90, 14));
        jPanel4.add(TimeLabel);

        jPanel1.add(jPanel4);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));
        jPanel2.setOpaque(false);
        NoteLabel.setBackground(new java.awt.Color(244, 245, 179));
        NoteLabel.setColumns(20);
        NoteLabel.setEditable(false);
        NoteLabel.setFont(new java.awt.Font("Courier", 1, 12));
        NoteLabel.setLineWrap(true);
        NoteLabel.setRows(5);
        NoteLabel.setWrapStyleWord(true);
        jScrollPane1.setViewportView(NoteLabel);

        jPanel2.add(jScrollPane1);

        add(jPanel2);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextArea NoteLabel;
    private javax.swing.JLabel NoteTypeLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
