/*
 * TabbedNoteDisplay.java
 *
 * Created on February 20, 2006, 9:10 AM
 */

package rmischedule.schedule.components.notes;

import java.util.*;
import javax.swing.*;
/**
 *
 * @author  Ira Juneau
 */
public class TabbedNoteDisplay extends javax.swing.JPanel {
    
    private static String ALL_NOTES = "All Notes";
    
    /** Creates new form TabbedNoteDisplay */
    public TabbedNoteDisplay() {
        initComponents();
    }
    
    public void clearData() {
        noteTabbedArea.removeAll();
        addTab(ALL_NOTES);
    }
    
    /**
     * Adds a note tab...
     */
    private void addTab(String tabName) {
        JPanel newPanel = new JPanel();
        BoxLayout myLayout = new BoxLayout(newPanel, BoxLayout.X_AXIS);
        newPanel.setLayout(myLayout);
        noteTabbedArea.addTab(tabName, newPanel);
    }
    
    /**
     * Adds a note to all tab, and note type tab....fun fun
     */
    public void addNote(SingleNoteDisplay newNote) {
        getTab(ALL_NOTES).add(newNote);
        if (getTab(newNote.getNoteType()) == null) {
            addTab(newNote.getNoteType());
        }
        getTab(newNote.getNoteType()).add(new SingleNoteDisplay(newNote));
    }
    
    /**
     * Sees if this tab already exists...
     */
    private JPanel getTab(String tabName) {
        for (int i = 0; i < noteTabbedArea.getTabCount(); i++) {
            if (tabName.trim().equals(noteTabbedArea.getTitleAt(i).trim())) {
                return (JPanel)noteTabbedArea.getComponentAt(i);
            }
        }
        return null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        noteTabbedArea = new javax.swing.JTabbedPane();

        setLayout(new java.awt.GridLayout());

        add(noteTabbedArea);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane noteTabbedArea;
    // End of variables declaration//GEN-END:variables
    
}
