/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientContactInfo.java
 *
 * Created on Mar 6, 2011, 8:50:13 PM
 */

package rmischedule.client.constant_contact;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import rmischedule.components.RatingPanel;
import rmischedule.components.graphicalcomponents.GenericEditSubForm;
import rmischedule.main.Main_Window;
import rmischeduleserver.control.ClientController;
import rmischeduleserver.control.ClientRatingController;
import rmischeduleserver.control.CompanyController;
import schedfoxlib.model.util.Record_Set;
import schedfoxlib.model.Client;
import schedfoxlib.model.ClientContact;
import schedfoxlib.model.ClientRating;
import rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat;
import rmischeduleserver.mysqlconnectivity.queries.client.get_client_by_id_query;
import schedfoxlib.model.Branch;
import schedfoxlib.model.ClientDisplayContact;
import schedfoxlib.model.User;

/**
 *
 * @author user
 */
public class ClientContactInfo extends GenericEditSubForm {

    private RatingPanel ratingPanel;

    /** Creates new form ClientContactInfo */
    public ClientContactInfo() {
        initComponents();

        ratingPanel = new RatingPanel(10, 32);
        clientRatingPanel.add(ratingPanel);
    }

    public Integer getRating() {
        return ratingPanel.getRating();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        branchLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clientNameLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clientPhoneLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        clientPhone2Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lastWeekLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        thisWeekLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        showClientChk = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        dmNameLbl = new javax.swing.JLabel();
        clientRatingPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(40095, 70));
        setMinimumSize(new java.awt.Dimension(95, 70));
        setPreferredSize(new java.awt.Dimension(196, 70));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        topPanel.setMaximumSize(new java.awt.Dimension(40095, 100));
        topPanel.setMinimumSize(new java.awt.Dimension(95, 100));
        topPanel.setPreferredSize(new java.awt.Dimension(196, 100));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(40069, 22));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Branch");
        jLabel2.setMaximumSize(new java.awt.Dimension(95, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(95, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(95, 16));
        jPanel9.add(jLabel2);

        branchLabel.setMaximumSize(new java.awt.Dimension(40000, 16));
        jPanel9.add(branchLabel);

        jPanel2.add(jPanel9);

        jPanel8.setMaximumSize(new java.awt.Dimension(40069, 22));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Client Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(95, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(95, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(95, 16));
        jPanel8.add(jLabel1);

        clientNameLabel.setMaximumSize(new java.awt.Dimension(40000, 16));
        jPanel8.add(clientNameLabel);

        jPanel2.add(jPanel8);

        jPanel7.setMaximumSize(new java.awt.Dimension(40069, 22));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Client Phone");
        jLabel3.setMaximumSize(new java.awt.Dimension(95, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(95, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(95, 16));
        jPanel7.add(jLabel3);

        clientPhoneLabel.setMaximumSize(new java.awt.Dimension(40000, 16));
        jPanel7.add(clientPhoneLabel);

        jPanel2.add(jPanel7);

        jPanel6.setMaximumSize(new java.awt.Dimension(40069, 22));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Client Phone 2");
        jLabel5.setMaximumSize(new java.awt.Dimension(95, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(95, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(95, 16));
        jPanel6.add(jLabel5);

        clientPhone2Label.setMaximumSize(new java.awt.Dimension(40000, 16));
        jPanel6.add(clientPhone2Label);

        jPanel2.add(jPanel6);

        topPanel.add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(240, 32811));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 100));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setMaximumSize(new java.awt.Dimension(40069, 22));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Contacts Last Week");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(120, 16));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel10.add(jLabel4);

        lastWeekLabel.setMaximumSize(new java.awt.Dimension(40000, 16));
        jPanel10.add(lastWeekLabel);

        jPanel1.add(jPanel10);

        jPanel11.setMaximumSize(new java.awt.Dimension(40069, 22));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText("Contacts This Week");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 16));
        jLabel7.setMinimumSize(new java.awt.Dimension(120, 16));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel11.add(jLabel7);

        thisWeekLabel.setMaximumSize(new java.awt.Dimension(40000, 16));
        jPanel11.add(thisWeekLabel);

        jPanel1.add(jPanel11);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        showClientChk.setText("Show client in call queue");
        showClientChk.setMaximumSize(new java.awt.Dimension(300, 25));
        showClientChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showClientChkActionPerformed(evt);
            }
        });
        jPanel3.add(showClientChk);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 22));
        jPanel4.setMinimumSize(new java.awt.Dimension(10, 16));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("DM");
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(25, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(25, 16));
        jPanel4.add(jLabel8);

        dmNameLbl.setMaximumSize(new java.awt.Dimension(4000, 16));
        jPanel4.add(dmNameLbl);

        jPanel1.add(jPanel4);

        topPanel.add(jPanel1);

        add(topPanel);

        clientRatingPanel.setMaximumSize(new java.awt.Dimension(40069, 37));
        clientRatingPanel.setMinimumSize(new java.awt.Dimension(95, 36));
        clientRatingPanel.setPreferredSize(new java.awt.Dimension(95, 36));
        clientRatingPanel.setLayout(new javax.swing.BoxLayout(clientRatingPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Customer Rating");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 16));
        clientRatingPanel.add(jLabel6);

        add(clientRatingPanel);

        contentPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        contentPanel.setPreferredSize(new java.awt.Dimension(200, 400));
        contentPanel.setLayout(new java.awt.GridLayout(0, 2));
        jScrollPane1.setViewportView(contentPanel);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void showClientChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showClientChkActionPerformed
        try {
            int confirm = JOptionPane.showConfirmDialog(Main_Window.parentOfApplication, "This will remove the client PERMANENTLY from the call queue. Do you want to do this?", "Remove Client?", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                Integer clientId = Integer.parseInt(myparent.getMyIdForSave());
                ClientController.getInstance(myparent.getConnection().myCompany).toggleClientViewableInContact(clientId);
                super.getMyParent().getData();
            }
        } catch (Exception exe) {}
        
    }//GEN-LAST:event_showClientChkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel branchLabel;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JLabel clientPhone2Label;
    private javax.swing.JLabel clientPhoneLabel;
    private javax.swing.JPanel clientRatingPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel dmNameLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastWeekLabel;
    private javax.swing.JCheckBox showClientChk;
    private javax.swing.JLabel thisWeekLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public GeneralQueryFormat getQuery(boolean isSelected) {
        get_client_by_id_query clientByIdQuery = new get_client_by_id_query();
        Client currClient = (Client)super.myparent.getSelectedObject();
        clientByIdQuery.setPreparedStatement(new Object[]{currClient.getClientId()});
        return clientByIdQuery;
    }

    @Override
    public GeneralQueryFormat getSaveQuery(boolean isNewData) {
        return null;
    }

    @Override
    public void loadData(Record_Set rs) {
        Client myClient = new Client(new Date(), rs);
        showClientChk.setSelected(true);
        clientNameLabel.setText(myClient.getClientName());
        clientPhoneLabel.setText(myClient.getClientPhone());
        clientPhone2Label.setText(myClient.getClientPhone2());
        
        try {
            CompanyController compController = new CompanyController(myparent.getConnection().myCompany);
            Branch myBranch = compController.getBranchById(myClient.getBranchId());
            branchLabel.setText(myBranch.getBranchName());
        } catch (Exception exe) {}
        
        try {
            ClientController cliController = ClientController.getInstance(myparent.getConnection().myCompany);
            User assignedDM = cliController.getDMAssignedToClient(myClient.getClientId());
            if (assignedDM == null || assignedDM.getUserId() == null) {
                dmNameLbl.setText("No DM Assigned");
            } else {
                dmNameLbl.setText(assignedDM.getFullName());
            }
        } catch (Exception exe) {}
        
        contentPanel.removeAll();
        ArrayList<ClientContact> contacts = myClient.getContacts(myparent.getConnection().myCompany);
        for (int c = 0; c < contacts.size(); c++) {
            contentPanel.add(new ClientContactPanel(contacts.get(c), myparent));
        }

        try {
            ClientRatingController ratingController = ClientRatingController.getInstance(myparent.getConnection().myCompany);
            ClientRating clientRating = ratingController.getLastClientRating(Integer.parseInt(myparent.getMyIdForSave()));
            if (clientRating.getCustomer_rating() > 0) {
                ratingPanel.setRating(clientRating.getCustomer_rating());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            ClientDisplayContact displayContact = (ClientDisplayContact)myparent.getSelectedObject();
            lastWeekLabel.setText(displayContact.getLastWeekTotal().toString());
            thisWeekLabel.setText(displayContact.getCurrentWeekTotal().toString());
        } catch (Exception exe) {}
    }


    @Override
    public boolean needsMoreRecordSets() {
        return false;
    }

    @Override
    public String getMyTabTitle() {
        return "Contact Info";
    }

    @Override
    public JPanel getMyForm() {
        return this;
    }

    @Override
    public void doOnClear() {
        ratingPanel.setSelected(false);
    }

    @Override
    public boolean userHasAccess() {
        return true;
    }

}
