/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientContactPanel.java
 *
 * Created on Mar 7, 2011, 8:59:39 AM
 */
package rmischedule.client.constant_contact;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import rmischedule.components.graphicalcomponents.GenericEditForm;
import rmischedule.main.Main_Window;
import schedfoxlib.model.ClientContact;
import schedfoxlib.model.ClientContactType;

/**
 *
 * @author user
 */
public class ClientContactPanel extends javax.swing.JPanel {

    private ClientContactType clientType;

    /**
     * Creates new form ClientContactPanel
     */
    public ClientContactPanel(final ClientContact clientContact, final GenericEditForm form) {
        clientType = clientContact.getClientContactTypeObj(form.getConnection().myCompany);
        initComponents();

        titleLabel.setText(clientContact.getClientContactTitle());
        firstLabel.setText(clientContact.getClientContactFirstName());
        lastLabel.setText(clientContact.getClientContactLastName());
        phoneLabel.setText(clientContact.getClientContactPhone());
        cellLabel.setText(clientContact.getClientContactCell());
        if (clientContact.getEmailAddress() == null || clientContact.getEmailAddress().length() == 0) {
            sendEmailBtn.setVisible(false);
        } else {
            sendEmailBtn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int response = JOptionPane.showConfirmDialog(Main_Window.parentOfApplication, 
                            "Do you want to send an email and mark this account as contacted?", 
                            "Send Email", JOptionPane.YES_NO_OPTION);
                    try {
                        if (response == JOptionPane.YES_OPTION) {
                            Desktop.getDesktop().mail(new URI("mailto:" + clientContact.getEmailAddress() + ""));
                            ConstantContact myParent = (ConstantContact)form;
                            myParent.markAsContacted(true);
                        }
                    } catch (URISyntaxException ex) {

                    } catch (IOException ioe) {

                    }

                }
            });
        }
    }

    private String getTitleText() {
        try {
            return clientType.getContactType();
        } catch (Exception e) {
            return "Contact Info";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        cellLabel = new javax.swing.JLabel();
        sendEmailBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(getTitleText()));
        setMinimumSize(new java.awt.Dimension(222, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(120, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(120, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 259));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Title");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel2.add(jLabel1);

        jLabel2.setText("First Name");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel2.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel2.add(jLabel2);

        jLabel3.setText("Last Name");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel2.add(jLabel3);

        jLabel4.setText("Phone");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel4.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel2.add(jLabel4);

        jLabel5.setText("Cell");
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel5.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel2.add(jLabel5);

        jLabel7.setText("Email");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel7.setMinimumSize(new java.awt.Dimension(90, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel2.add(jLabel7);

        add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(150, 32767));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        titleLabel.setText("Title");
        titleLabel.setMaximumSize(new java.awt.Dimension(160, 24));
        titleLabel.setMinimumSize(new java.awt.Dimension(90, 20));
        titleLabel.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel1.add(titleLabel);

        firstLabel.setText("First Name");
        firstLabel.setMaximumSize(new java.awt.Dimension(160, 24));
        firstLabel.setMinimumSize(new java.awt.Dimension(90, 20));
        firstLabel.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel1.add(firstLabel);

        lastLabel.setText("Last Name");
        lastLabel.setMaximumSize(new java.awt.Dimension(160, 24));
        lastLabel.setMinimumSize(new java.awt.Dimension(90, 20));
        lastLabel.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel1.add(lastLabel);

        phoneLabel.setText("Phone");
        phoneLabel.setMaximumSize(new java.awt.Dimension(160, 24));
        phoneLabel.setMinimumSize(new java.awt.Dimension(90, 20));
        phoneLabel.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel1.add(phoneLabel);

        cellLabel.setText("Cell");
        cellLabel.setMaximumSize(new java.awt.Dimension(160, 24));
        cellLabel.setMinimumSize(new java.awt.Dimension(90, 20));
        cellLabel.setPreferredSize(new java.awt.Dimension(120, 24));
        jPanel1.add(cellLabel);

        sendEmailBtn.setText("Send Email");
        sendEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sendEmailBtn);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void sendEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendEmailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cellLabel;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton sendEmailBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
