/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rmischedule.misc;

import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;
import rmischeduleserver.control.HealthCareController;
import schedfoxlib.model.HealthCareOption;

/**
 *
 * @author ira
 */
public class HealthCareDialog extends javax.swing.JDialog {

    private HealthCareModel healthModel = new HealthCareModel();
    private HealthCareOption option;
    private String companyId;
    
    /**
     * Creates new form HealthCareDialog
     */
    public HealthCareDialog(java.awt.Frame parent, boolean modal, String companyId) {
        super(parent, modal);
        initComponents();
        
        this.companyId = companyId;
        
        this.reloadData();
    }

    private void reloadData() {
        try {
            healthModel.clear();
            ArrayList<HealthCareOption> options = HealthCareController.getInstance(companyId).getHealthCareOptions();
            for (int o = 0; o < options.size(); o++) {
                healthModel.add(options.get(o));
            }
            showInformation();
        } catch (Exception exe) {
            exe.printStackTrace();
        }
    }
    
    private void showInformation() {
        try {
            healthCareTxt.setText(option.getName());
        } catch (Exception exe) {
            healthCareTxt.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        healthCareTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        healthcareTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(445, 60));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Health Care Option Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(155, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(155, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(155, 16));
        jPanel1.add(jLabel1);

        healthCareTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        healthCareTxt.setMinimumSize(new java.awt.Dimension(6, 26));
        healthCareTxt.setPreferredSize(new java.awt.Dimension(6, 26));
        jPanel1.add(healthCareTxt);

        jPanel4.setMaximumSize(new java.awt.Dimension(5, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(5, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(5, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        saveBtn.setText("Save");
        saveBtn.setMaximumSize(new java.awt.Dimension(70, 25));
        saveBtn.setMinimumSize(new java.awt.Dimension(70, 25));
        saveBtn.setPreferredSize(new java.awt.Dimension(70, 25));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jPanel2.setLayout(new java.awt.GridLayout());

        healthcareTable.setModel(healthModel);
        healthcareTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healthcareTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(healthcareTable);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 35));
        jPanel3.setPreferredSize(new java.awt.Dimension(445, 35));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));

        closeBtn.setText("Close");
        closeBtn.setMaximumSize(new java.awt.Dimension(80, 25));
        closeBtn.setMinimumSize(new java.awt.Dimension(80, 25));
        closeBtn.setPreferredSize(new java.awt.Dimension(80, 25));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(closeBtn);

        getContentPane().add(jPanel3);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-463)/2, (screenSize.height-345)/2, 463, 345);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            if (option == null) {
                option = new HealthCareOption();
            }
            option.setActive(true);
            option.setName(healthCareTxt.getText());
            HealthCareController.getInstance(companyId).saveHealthCareOption(option);
            option = null;
            reloadData();
        } catch (Exception exe) {
            exe.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void healthcareTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthcareTableMouseClicked
        option = healthModel.get(healthcareTable.getSelectedRow());
        showInformation();
    }//GEN-LAST:event_healthcareTableMouseClicked

    private class HealthCareModel extends AbstractTableModel {

        private ArrayList<HealthCareOption> healthOptions;
        
        public HealthCareModel() {
            healthOptions = new ArrayList<HealthCareOption>();
        }
        
        public int getRowCount() {
            return healthOptions.size();
        }

        public int getColumnCount() {
            return 1;
        }
        
        public HealthCareOption get(int i) {
            return this.healthOptions.get(i);
        }

        public void add(HealthCareOption option) {
            this.healthOptions.add(option);
            this.fireTableDataChanged();
        }
        
        public void clear() {
            this.healthOptions.clear();
            this.fireTableDataChanged();
        }
        
        public Object getValueAt(int rowIndex, int columnIndex) {
            return healthOptions.get(rowIndex).getName();
        }
        
        @Override
        public String getColumnName(int columnIndex) {
            return "Health Care Name";
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField healthCareTxt;
    private javax.swing.JTable healthcareTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
