/*
 * ForgotPasswordDialog.java
 *
 * Created on November 25, 2005, 9:04 AM
 */

package rmischedule.login;
import schedfoxlib.model.util.Record_Set;
import rmischedule.main.*;
import rmischeduleserver.data_connection_types.*;
import rmischeduleserver.mysqlconnectivity.queries.util.*;
import rmischedule.data_connection.*;
import rmischedule.components.*;

import javax.swing.*;
import java.util.*;
import java.net.*;
import java.io.*;
//import rmischeduleserver.util.MailMessage;
/**
 *
 * @author  Ira Juneau
 */
public class ForgotPasswordDialog extends javax.swing.JDialog {
    
    /** Creates new form ForgotPasswordDialog */
    public ForgotPasswordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void resetPasswordForUser() {
        ArrayList<UserInfo> emails = getEmailsThatMatch();
//        if (emails.size() > 0) {
//            MailMessage message = new MailMessage();
//            StringBuffer buffer = new StringBuffer();
//            ArrayList<String> mailTo = new ArrayList();
//            buffer.append("You recently requested your lost password information for Schedfox. ");
//            buffer.append("Please click on the link(s) below to log into Schedfox.\r\n\r\n");
//            for (int i = 0; i < emails.size(); i++) {
//                if (!mailTo.contains(emails.get(i).UserEmail)) {
//                    mailTo.add(emails.get(i).UserEmail);
//                }
//                buffer.append("http://www.schedfox.com/sched/schedule.php?md5=" + emails.get(i).UserMD5 + "&user=" + emails.get(i).UserID + "/r/n");
//            }
//            message.setMailServer("mail.champ.net");
//            message.setMailSubject("SchedFox Password Request");
//            message.setMailTo(mailTo);
//            message.setFromAddress("schedfox@schedfox.com");
//            message.setMessageContents(buffer.toString());
//
//            try {
//                boolean retVal = Main_Window.parentOfApplication.getServer().sendMail(message);
//                if (!retVal) {
//                    throw new Exception();
//                } else {
//                    JOptionPane.showMessageDialog(this, "A Email has been sent to the Email address provided in your account.\n Please click on the link provided in the message to reset your password.", "Confirm message sent", JOptionPane.OK_OPTION);
//                    dispose();
//                }
//            } catch (Exception e) {
//                 JOptionPane.showMessageDialog(this, "Error Encountered: Could not send mail message.", "Error Sending Mail", JOptionPane.ERROR_MESSAGE);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Could not find a account with provided information, please retry.", "Error Finding Account", JOptionPane.ERROR_MESSAGE);
//        }
    }
    
    /**
     * Returns a list of all users who match provided info either their email or
     * login name...
     */
    public ArrayList<UserInfo> getEmailsThatMatch() {
        getUserInfoForEmailOrLoginQuery forgotPasswordQuery = new getUserInfoForEmailOrLoginQuery();
        ArrayList<UserInfo> sendTo = new ArrayList();
        forgotPasswordQuery.update(InfoBox.getText());
        Record_Set rs = new Record_Set();
        try {
            rs = new Connection().executeQuery(forgotPasswordQuery);
        } catch (Exception e) {}
        rs.moveToFront();
        for (int i = 0; i < rs.length(); i++) {
            sendTo.add(new UserInfo(rs.getString("email"), rs.getString("md5"), rs.getString("uid")));
            rs.moveNext();
        }
        return sendTo;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel4 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        InfoBox = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        OkButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setText("Type in the login name or the Email of your account and we will send you a link to reset your password. ");
        jTextArea1.setOpaque(false);
        jPanel4.add(jTextArea1);

        getContentPane().add(jPanel4);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel7.setMinimumSize(new java.awt.Dimension(60, 10));
        jPanel7.setPreferredSize(new java.awt.Dimension(60, 10));
        jPanel2.add(jPanel7);

        jPanel2.add(InfoBox);

        jPanel6.setMinimumSize(new java.awt.Dimension(60, 10));
        jPanel6.setPreferredSize(new java.awt.Dimension(60, 10));
        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        OkButton.setText("OK");
        OkButton.setMaximumSize(new java.awt.Dimension(80, 23));
        OkButton.setMinimumSize(new java.awt.Dimension(80, 23));
        OkButton.setPreferredSize(new java.awt.Dimension(80, 23));
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        jPanel3.add(OkButton);

        jPanel3.add(jPanel5);

        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(80, 23));
        CancelButton.setMinimumSize(new java.awt.Dimension(80, 23));
        CancelButton.setPreferredSize(new java.awt.Dimension(80, 23));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jPanel3.add(CancelButton);

        getContentPane().add(jPanel3);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-351)/2, (screenSize.height-163)/2, 351, 163);
    }
    // </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        resetPasswordForUser();
    }//GEN-LAST:event_OkButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    private class UserInfo {
        public String UserEmail;
        public String UserMD5;
        public String UserID;
        public UserInfo(String email, String md5, String id) {
            UserEmail = email;
            UserMD5 = md5;
            UserID = id;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField InfoBox;
    private javax.swing.JButton OkButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
