/*
 * SplashScreen.java
 *
 * Created on February 10, 2005, 1:43 PM
 */
package rmischedule.login;

import com.creamtec.ajaxswing.AjaxSwingManager;
import com.creamtec.ajaxswing.core.AjaxSwingProperties;
import com.creamtec.ajaxswing.core.ClientAgent;
import rmischedule.main.*;
import rmischedule.components.Jar_Images;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author ira
 */
public class SplashScreen extends javax.swing.JFrame {

    public boolean isDone;
    private Main_Window parent;
    private Jar_Images ji;
    private BlankAjaxForm myBackground = null;

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen(Main_Window mw) {
        this.getRootPane().putClientProperty(AjaxSwingProperties.COMPONENT_CSS_CLASS, "dialogCenter");
        if (AjaxSwingManager.isAjaxSwingRunning()) {
            //myBackground = new BlankAjaxForm();
            //myBackground.setVisible(true);
        }
        mw.mySplash = this;
        parent = mw;
        initComponents();
        ji = new Jar_Images(mw);
        Image myImage = ji.getImageFromJAR("images/splash.jpg");
        PictureLabel.setIcon(new ImageIcon(myImage));
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width - this.getWidth()) / 2, (screenSize.height - this.getHeight()) / 2);
    }

    public void startMe() {
        myStartThread myThread = new myStartThread();
        myThread.start();
    }

    private class myStartThread extends Thread {

        public void run() {

            try {

                while (parent.getLoadProgress() < 100) {
                    sleep(100);
                    SwingUtilities.invokeAndWait(new Runnable() {

                        public void run() {
                            myProgressBar.setString(parent.getTextForLoadingProgress());
                            myProgressBar.setValue(parent.getLoadProgress());
                        }
                    });

                }

                isDone = true;
                SwingUtilities.invokeAndWait(new Runnable() {

                    public void run() {
                        dispose();
                        parent.continueLoad();
                        
                        if (AjaxSwingManager.isAjaxSwingRunning()) {
                            try {
                                myBackground.setVisible(false);
                                parent.toFront();
                                ClientAgent.getCurrentInstance().setUpdateBrowser(true);
                            } catch (Exception e) {
                            }
                        }
                        
                    }
                });
            } catch (Exception e) {
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroundPanel = new javax.swing.JPanel();
        PictureLabel = new javax.swing.JLabel();
        myProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(150, 56, 22));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setResizable(false);
        setUndecorated(true);

        GroundPanel.setBackground(new java.awt.Color(204, 204, 204));
        GroundPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GroundPanel.setPreferredSize(new java.awt.Dimension(556, 401));
        GroundPanel.setLayout(new java.awt.BorderLayout());

        PictureLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        PictureLabel.setForeground(new java.awt.Color(255, 255, 255));
        PictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PictureLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GroundPanel.add(PictureLabel, java.awt.BorderLayout.CENTER);

        myProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        myProgressBar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        myProgressBar.setForeground(new java.awt.Color(178, 57, 0));
        myProgressBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        myProgressBar.setString("Loading");
        myProgressBar.setStringPainted(true);
        GroundPanel.add(myProgressBar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(GroundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GroundPanel;
    private javax.swing.JLabel PictureLabel;
    private javax.swing.JProgressBar myProgressBar;
    // End of variables declaration//GEN-END:variables
}
