/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommissionCapDialog.java
 *
 * Created on Feb 21, 2012, 10:24:08 AM
 */

package rmischedule.xadmin;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import rmischedule.main.Main_Window;
import rmischeduleserver.control.UserCommissionCapsController;
import rmischeduleserver.control.UserController;
import schedfoxlib.model.Contact;
import schedfoxlib.model.User;
import schedfoxlib.model.UserCommissionCaps;

/**
 *
 * @author user
 */
public class CommissionCapDialog extends javax.swing.JDialog {

    private ArrayList<UserCommissionCaps> userCaps;
    private UserCommissionCaps userCap;
    private CommissionCapModel commissionCapModel = new CommissionCapModel();
    
    /** Creates new form CommissionCapDialog */
    public CommissionCapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            userCaps = new ArrayList<UserCommissionCaps>();
            UserController userController = new UserController("2");
            ArrayList<Contact> sales = userController.getUsersByType("Sales", "-1");
            ArrayList<Contact> salesManager = userController.getUsersByType("Sales Manager", "-1");

            HashMap<Integer, Contact> removeDuplicateHash = new HashMap<Integer, Contact>();
            for (int d = 0; d < sales.size(); d++) {
                removeDuplicateHash.put(sales.get(d).getPrimaryId(), sales.get(d));
            }
            for (int d = 0; d < salesManager.size(); d++) {
                removeDuplicateHash.put(salesManager.get(d).getPrimaryId(), salesManager.get(d));
            }

            ArrayList<Contact> fullList = new ArrayList<Contact>();
            Iterator<Contact> iterator = removeDuplicateHash.values().iterator();
            while (iterator.hasNext()) {
                fullList.add(iterator.next());
            }
            Collections.sort(fullList);

            for (int s = 0; s < fullList.size(); s++) {
                salesCmbo.addItem(fullList.get(s));
            }

        } catch (Exception exe) {
            exe.printStackTrace();
        }
    }

    private void loadCommissionData() {
        yearNumberTxt.setText("");
        amountTxt.setText("");
        try {
            User user = (User)salesCmbo.getSelectedItem();
            UserCommissionCapsController controller = UserCommissionCapsController.getInstance("2");
            userCaps = controller.getCommissionCapsForUser(user.getPrimaryId());
            commissionCapModel.clear();
            for (int c = 0; c < userCaps.size(); c++) {
                commissionCapModel.addCap(userCaps.get(c));
            }
            try {
                //amountTxt.setText(userCaps.getYearlyCaps().toString());
            } catch (Exception e) {
                //amountTxt.setText("0");
            }
            
        } catch (Exception exe) {
            exe.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salesCmbo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        yearNumberTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commissionTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(10000, 35));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 28));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Sales Person");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel1);

        salesCmbo.setMaximumSize(new java.awt.Dimension(32767, 26));
        salesCmbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesCmboActionPerformed(evt);
            }
        });
        jPanel4.add(salesCmbo);

        jPanel1.add(jPanel4);

        jPanel3.setMaximumSize(new java.awt.Dimension(10000, 35));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 28));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Year Number");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel3.add(jLabel2);

        yearNumberTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel3.add(yearNumberTxt);

        jLabel8.setText("Year Cap");
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel3.add(jLabel8);

        amountTxt.setMaximumSize(new java.awt.Dimension(2147483647, 26));
        jPanel3.add(amountTxt);

        jPanel1.add(jPanel3);

        jPanel5.setMaximumSize(new java.awt.Dimension(10000, 1000));
        jPanel5.setLayout(new java.awt.GridLayout());

        commissionTable.setModel(commissionCapModel);
        commissionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commissionTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(commissionTable);

        jPanel5.add(jScrollPane1);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 35));
        jPanel2.setPreferredSize(new java.awt.Dimension(326, 35));

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(closeBtn)))
        );

        getContentPane().add(jPanel2);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-454)/2, (screenSize.height-340)/2, 454, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void salesCmboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesCmboActionPerformed
        loadCommissionData();
    }//GEN-LAST:event_salesCmboActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            User user = (User)salesCmbo.getSelectedItem();
            UserCommissionCapsController controller = UserCommissionCapsController.getInstance("2");
            
            if (userCap == null) {
                userCap = new UserCommissionCaps();
                //userCap = controller.getCommissionCapByUserAndYear(user.getId(), Integer.parseInt(yearNumberTxt.getText()));
            } 
            if (Integer.parseInt(yearNumberTxt.getText()) > 0) {
                userCap.setYearNumber(Integer.parseInt(yearNumberTxt.getText()));
                userCap.setUserId(user.getId());
                userCap.setYearlyCaps(new BigDecimal(new Double(amountTxt.getText())));
                controller.saveCommissionCaps(userCap);
                userCaps = new ArrayList<UserCommissionCaps>();
                loadCommissionData();
                JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Commission Cap Saved!", "Saved", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Please enter in a year > 0", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception exe) {
            JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Invalid Data", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void commissionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commissionTableMouseClicked
        try {
            userCap = commissionCapModel.getCapAt(commissionTable.getSelectedRow());
            yearNumberTxt.setText(userCap.getYearNumber() + "");
            amountTxt.setText(userCap.getYearlyCaps() + "");
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_commissionTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTable commissionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox salesCmbo;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField yearNumberTxt;
    // End of variables declaration//GEN-END:variables

}
