/*
 * ListGroupAccessPanel.java
 *
 * Created on September 6, 2005, 11:03 AM
 */

package rmischedule.xadmin;
import rmischedule.components.*;
import rmischeduleserver.data_connection_types.*;
import rmischeduleserver.mysqlconnectivity.queries.*;
import rmischeduleserver.mysqlconnectivity.queries.util.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author  Ira Juneau
 */
public class ListGroupAccessPanel extends javax.swing.JPanel implements UserPanelInterface {
    
    private List_View myGroupListView;
    private String uid;
    
    /** Creates new form ListGroupAccessPanel */
    public ListGroupAccessPanel(xUserDetail myPar) {
        initComponents();
        uid = "0";
        myGroupListView = new List_View();
        myGroupListView.addColumn("id", List_View.STRING, false, false);
        myGroupListView.addColumn("id2", List_View.STRING, false, false);
        myGroupListView.addColumn("Group Name", List_View.STRING, false, true);
        myGroupListView.addColumn("Member Of?", List_View.BOOLEAN, true, true);
        myGroupListView.buildTable();
        myGroupListView.maximizeTable();
        add(myGroupListView.myScrollPane);
        myPar.registerListView(myGroupListView);
    }
    
    public javax.swing.JPanel getComponent() {
        return this;
    }
    
    public void clearListView() { this.myGroupListView.clearRows(); this.myGroupListView.fireTableDataChanged(); }
    public String getUserId() { return this.uid; }
    public void setUserId(String id) { this.uid = id; }
    
    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getQuery(String manageId, String userId) {
        uid = userId;
        get_user_group_security_query myQuery = new get_user_group_security_query();
        myQuery.update(userId, manageId);
        return myQuery;
    }
    
    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getSaveDataQuery(Object OptionalData) {
        save_branch_comp_group_access_query myCompQuery = new save_branch_comp_group_access_query();
        ArrayList Group = new ArrayList();
        for (int i = 0; i < myGroupListView.getRowCount(); i++) {
            if ((Boolean) myGroupListView.getValueAt(i, 1)) {
                Group.add(myGroupListView.getTrueValueAt(i, 0).toString());
            }
        }
        myCompQuery.update(uid, null, null, Group, null);
        return myCompQuery;
    }
    
    public String getTitleOfTab() {
        return "Groups";
    }
    
    public void setData(schedfoxlib.model.util.Record_Set rs) {
        myGroupListView.clearRows();
        for (int i = 0; i < rs.length(); i++) {
            myGroupListView.addRow(rs);
            rs.moveNext();
        }
        myGroupListView.fireTableDataChanged();
    }

    public List_View getListView() {
        return myGroupListView;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 0));

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
