/*
 * ListBranchAccessPanel.java
 *
 * Created on September 5, 2005, 4:25 PM
 */

package rmischedule.xadmin;
import schedfoxlib.model.util.Record_Set;
import rmischedule.components.*;
import rmischeduleserver.data_connection_types.*;
import rmischeduleserver.mysqlconnectivity.queries.*;
import rmischeduleserver.mysqlconnectivity.queries.util.*;

import javax.swing.*;
import java.util.*;
/**
 *
 * @author  Owner
 */
public class ListBranchAccessPanel extends javax.swing.JPanel implements UserPanelInterface {
    
    private List_View myBranchListView;
    private String uid;
    
    /** Creates new form ListBranchAccessPanel */
    public ListBranchAccessPanel() {
        initComponents();
        uid = "0";
        myBranchListView = new List_View();
        myBranchListView.addColumn("id", List_View.STRING, false, false);
        myBranchListView.addColumn("branchid", List_View.STRING, false, false);
        myBranchListView.addColumn("Branch Name", List_View.STRING, false, true);
        myBranchListView.addColumn("Has Access?", List_View.BOOLEAN, true, true);
        myBranchListView.buildTable();
        myBranchListView.maximizeTable();
        add(myBranchListView.myScrollPane);
    }
    
    /**
     * Returns Query, as defined in the interface UserPanelInterface...
     */
    public GeneralQueryFormat getQuery(String manageId, String userId) {
        uid = userId;
        get_user_branch_security_query myQuery = new get_user_branch_security_query();
        myQuery.update(userId, manageId);
        return myQuery;
    }
    
    public void setData(Record_Set rs) {
        myBranchListView.clearRows();
        for (int i = 0; i < rs.length(); i++) {
            myBranchListView.addRow(rs);
            rs.moveNext();
        }
        myBranchListView.fireTableDataChanged();
    }
    
    public String getTitleOfTab() {
        return "Branch Access";
    }
    
    public JPanel getComponent() {
        return this;
    }
    
    public GeneralQueryFormat getSaveDataQuery(Object OptionalData) {
        save_branch_comp_group_access_query myCompQuery = new save_branch_comp_group_access_query();
        ArrayList Branch = new ArrayList();
        for (int i = 0; i < myBranchListView.getRowCount(); i++) {
            if ((Boolean) myBranchListView.getValueAt(i, 1)) {
                Branch.add(myBranchListView.getTrueValueAt(i, 0).toString());
            }
        }
        myCompQuery.update(uid, Branch, null, null, null);
        return myCompQuery;
    }

    public List_View getListView() {
        return myBranchListView;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 0));

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
