/*
 * xDisplayAccountInfoPanel.java
 *
 * Created on November 25, 2005, 10:27 AM
 */

package rmischedule.xadmin;
import schedfoxlib.model.util.Record_Set;
import rmischeduleserver.mysqlconnectivity.queries.util.*;
import rmischeduleserver.data_connection_types.*;
import rmischedule.data_connection.*;
import rmischedule.main.*;
import rmischedule.misc.*;
import javax.swing.*;
/**
 *
 * @author  Ira Juneau
 */
public class xDisplayAccountInfoPanel extends javax.swing.JDialog {
    
    /** Creates new form xDisplayAccountInfoPanel */
    public xDisplayAccountInfoPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ChngPsswd.setIcon(Main_Window.Lock_Icon);
        populateData();
    }
    
    public void populateData() {
        list_users_query myQuery = new list_users_query();
        Record_Set myInfo = new Record_Set();
        myQuery.update(true, Main_Window.parentOfApplication.getManagementId(), Main_Window.parentOfApplication.getUser().getUserId());
        try {
            myInfo = new Connection().executeQuery(myQuery);
        } catch (Exception e) {}
        fname.setText(myInfo.getString("user_first_name"));
        mi.setText(myInfo.getString("user_middle_initial"));
        lname.setText(myInfo.getString("user_last_name"));
        setTitle("Information for " + myInfo.getString("user_login"));
        email.setText(myInfo.getString("email"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mi = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        ChngPsswd = new javax.swing.JButton();
        ChngTimeZone = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(2, 2, 2, 2)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 25));
        jLabel1.setText("First Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(85, 14));
        jPanel1.add(jLabel1);

        fname.setMaximumSize(new java.awt.Dimension(2147483647, 19));
        fname.setMinimumSize(new java.awt.Dimension(6, 19));
        fname.setPreferredSize(new java.awt.Dimension(57, 19));
        jPanel1.add(fname);

        jLabel3.setText(" MI");
        jLabel3.setMaximumSize(new java.awt.Dimension(20, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(20, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel1.add(jLabel3);

        mi.setMaximumSize(new java.awt.Dimension(45, 19));
        mi.setMinimumSize(new java.awt.Dimension(45, 19));
        mi.setPreferredSize(new java.awt.Dimension(45, 19));
        jPanel1.add(mi);

        jPanel8.add(jPanel1);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 19));
        jPanel7.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel7.setPreferredSize(new java.awt.Dimension(10, 19));
        jLabel4.setText("Last Name");
        jLabel4.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(85, 14));
        jPanel7.add(jLabel4);

        lname.setMaximumSize(new java.awt.Dimension(2147483647, 19));
        lname.setMinimumSize(new java.awt.Dimension(6, 19));
        lname.setPreferredSize(new java.awt.Dimension(57, 19));
        jPanel7.add(lname);

        jPanel8.add(jPanel7);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 25));
        jLabel5.setText("Email Address");
        jLabel5.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(85, 14));
        jPanel2.add(jLabel5);

        email.setMaximumSize(new java.awt.Dimension(2147483647, 19));
        email.setMinimumSize(new java.awt.Dimension(6, 19));
        email.setPreferredSize(new java.awt.Dimension(57, 19));
        jPanel2.add(email);

        jPanel8.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        ChngPsswd.setText("Change Password");
        ChngPsswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChngPsswdActionPerformed(evt);
            }
        });

        jPanel3.add(ChngPsswd);

        ChngTimeZone.setText("Set TimeZone");
        ChngTimeZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChngTimeZoneActionPerformed(evt);
            }
        });

        jPanel3.add(ChngTimeZone);

        jPanel8.add(jPanel3);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jButton1.setText("Save");
        jButton1.setMaximumSize(new java.awt.Dimension(80, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(80, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.add(jButton1);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel5.add(jPanel6);

        jButton2.setText("Cancel");
        jButton2.setMaximumSize(new java.awt.Dimension(80, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(80, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.add(jButton2);

        jPanel8.add(jPanel5);

        getContentPane().add(jPanel8);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-290)/2, (screenSize.height-151)/2, 290, 151);
    }
    // </editor-fold>//GEN-END:initComponents

    private void ChngTimeZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChngTimeZoneActionPerformed
        new SpecifyTimeZoneDialog(Main_Window.parentOfApplication, true).setVisible(true);
    }//GEN-LAST:event_ChngTimeZoneActionPerformed

    private void ChngPsswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChngPsswdActionPerformed
        ChangePasswordDialog myChangeDialog = new ChangePasswordDialog(Main_Window.parentOfApplication, true);
    }//GEN-LAST:event_ChngPsswdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        save_basic_user_info mySaveQuery = new save_basic_user_info();
        mySaveQuery.update(Main_Window.parentOfApplication.getUser().getUserId(), fname.getText(), mi.getText(), lname.getText(), email.getText());
        try {
            new Connection().executeQuery(mySaveQuery);
        } catch (Exception e) {}
        JOptionPane.showMessageDialog(Main_Window.parentOfApplication, "Information Updated!", "Confirm Save", JOptionPane.OK_OPTION);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xDisplayAccountInfoPanel(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChngPsswd;
    private javax.swing.JButton ChngTimeZone;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    // End of variables declaration//GEN-END:variables
    
}
