/*
 * xListCompanyBranchAccessPanel.java
 *
 * Created on November 22, 2005, 8:53 AM
 */

package rmischedule.xadmin;
import rmischeduleserver.mysqlconnectivity.queries.util.*;
import rmischedule.components.graphicalcomponents.graphicalTree.*;
import rmischedule.misc.*;
import rmischedule.main.Main_Window;
import java.util.*;

/**
 *
 * @author  Ira Juneau
 */
public class xListCompanyBranchAccessPanel extends javax.swing.JPanel implements UserPanelInterface {
    
    private xUserDetail Parent;
    private Vector<CompanyTreeObj> myCompanies;
    private String currMangement;
    private String currUser;
    
    /** Creates new form xListCompanyBranchAccessPanel */
    public xListCompanyBranchAccessPanel(xUserDetail myPar) {
        initComponents();
        Parent = myPar;
        noLabel.setIcon(Main_Window.BulletRed16x16Icon);
        partLabel.setIcon(Main_Window.BulletYellow16x16Icon);
        fullLabel.setIcon(Main_Window.BulletGreen16x16Icon);
        this.jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        
    }
    
    public void setUserId(String id) { this.currUser = id; }
    public String getUserId() { return this.currUser; }
    public void clearCompanyList() { myCompanies = new Vector(); this.containerPane.removeAll(); }

    public javax.swing.JPanel getComponent() {
        return this;
    }

    public rmischedule.components.List_View getListView() {
        return null;
    }

    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getQuery(String manageId, String userId) {
        xGet_User_Branch_Company_List_Query myQuery = new xGet_User_Branch_Company_List_Query();
        currMangement = manageId;
        currUser = userId;
        myQuery.update(userId, manageId);
        return myQuery;
    }

    public rmischeduleserver.mysqlconnectivity.queries.GeneralQueryFormat getSaveDataQuery(Object OptionalData) {
        return null;
    }

    public String getTitleOfTab() {
        return "Company/Branch Access";
    }

    public void setData(schedfoxlib.model.util.Record_Set rs) {
        myCompanies = new Vector();
        containerPane.removeAll();
        String lastCid = "";
        CompanyTreeObj lastCompany = null;
        for (int i = 0; i < rs.length(); i++) {
            if (!rs.getString("cid").equals(lastCid)) {
                lastCid = rs.getString("cid");
                rmischedule.misc.CompanyTreeObj myComp = new rmischedule.misc.CompanyTreeObj(rs.getString("cid"), rs.getString("cname"), currMangement, currUser);
                myCompanies.add(myComp);
                lastCompany = myComp;
            }
            rmischedule.misc.BranchTreeObj myBranch = new rmischedule.misc.BranchTreeObj(rs.getString("bid"), rs.getString("bname"), currMangement, !rs.getBoolean("hasaccess"), lastCompany);
            lastCompany.addBranch(myBranch);
            rs.moveNext();
        }
        for (int i = 0; i < myCompanies.size(); i++) {
            IndividualTreePanel myPanel = new IndividualTreePanel(myCompanies.get(i));
            containerPane.add(myPanel);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        noLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        partLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fullLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        containerPane = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 22));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 22));
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 22));
        jPanel5.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel1.add(jPanel5);

        jLabel1.setText("Access Levels ");
        jPanel1.add(jLabel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel1.add(jPanel2);

        noLabel.setText("No Access");
        jPanel1.add(noLabel);

        jPanel3.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel1.add(jPanel3);

        partLabel.setText("Partial Access");
        jPanel1.add(partLabel);

        jPanel4.setMaximumSize(new java.awt.Dimension(10, 32767));
        jPanel1.add(jPanel4);

        fullLabel.setText("Full Access");
        jPanel1.add(fullLabel);

        add(jPanel1);

        containerPane.setLayout(new javax.swing.BoxLayout(containerPane, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(containerPane);

        add(jScrollPane1);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPane;
    private javax.swing.JLabel fullLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noLabel;
    private javax.swing.JLabel partLabel;
    // End of variables declaration//GEN-END:variables
    
}
