/*
 * LateCheckInOptions.java
 *
 * Created on June 29, 2005, 6:11 PM
 */

package rmischedule.schedule.checkincheckout;
import rmischedule.main.Main_Window;
import rmischedule.components.graphicalcomponents.GraphicalOption;
import rmischeduleserver.util.StaticDateTimeFunctions;
import rmischeduleserver.mysqlconnectivity.queries.schedule_data.check_in.update_check_in_out_time_query;
import rmischeduleserver.mysqlconnectivity.queries.*;
import javax.swing.JLabel;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.*;
import schedfoxlib.model.AssembleCheckinScheduleType;
/**
 *
 * @author  ira
 */
public class LateCheckInOptions extends javax.swing.JDialog {
    
    private static boolean showIconsInOptions = false;
    
    private GraphicalOption CheckInRadio;
    private GraphicalOption ModifyRadio;
    private GraphicalOption FlagRadio;
    private IndividualCheckInCheckOutPanel myparent;
    private boolean isCheckInData;
    
    /** Creates new form LateCheckInOptions */
    public LateCheckInOptions(java.awt.Frame parent, String time, String id, String eName, boolean modal, boolean isCheckIn, IndividualCheckInCheckOutPanel myParent) {
        super(parent, modal);
        myparent = myParent;
        String myTimeText = "Entry ";
        isCheckInData = isCheckIn;
        if (!isCheckIn) {
            myTimeText = "Exit ";
        }
        String myPrompt = myTimeText + " time was at least 15 minutes ago what do you want to do?";
        initComponents();
        
        JLabel myCheckLabel = new JLabel();
        JLabel myHelpLabel = new JLabel();
        JLabel myClockLabel = new JLabel();
        
        myCheckLabel.setIcon(Main_Window.Time_Sheet_Check_Icon);
        myHelpLabel.setIcon(Main_Window.HelpIcon);
        myClockLabel.setIcon(Main_Window.ClockIcon);
        
        CheckInRadio = new GraphicalOption(showIconsInOptions);
        ModifyRadio = new GraphicalOption(showIconsInOptions);
        FlagRadio = new GraphicalOption(showIconsInOptions);
        
        CheckInRadio.setText("Check " + eName + " In On Time");
        ModifyRadio.setText("Modify "+ myTimeText + " Time On Schedule");
        FlagRadio.setText("Flag Shift As Uncertain "+ myTimeText + " Time");
        PromptText.setText(myPrompt);
        
        ButtonGroup.add(CheckInRadio);
        ButtonGroup.add(ModifyRadio);
        ButtonGroup.add(FlagRadio);
        EntryTimeText.setText(time);
        
        jPanel5.add(myClockLabel);
        jPanel4.add(myCheckLabel);
        jPanel6.add(myHelpLabel);
        
        jPanel5.add(ModifyRadio);
        jPanel5.add(ModifySpacer);
        jPanel5.add(EntryTimeText);
        jPanel4.add(CheckInRadio);
        jPanel6.add(FlagRadio);
        //EntryTimeText.setVisible(false);
        
        ModifyRadio.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent evt) {
                    if (ModifyRadio.isSelected()) {
                        EntryTimeText.setVisible(true);
                    } else {
                        EntryTimeText.setVisible(false);
                    }
                }
            });
        
        //EntryTimeText.setVisible(false);
            
        CheckInRadio.setSelected(true);
        getContentPane().repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ButtonGroup = new javax.swing.ButtonGroup();
        EntryTimeText = new javax.swing.JTextField();
        ModifySpacer = new javax.swing.JPanel();
        PromptText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        OkButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        SpacerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        EntryTimeText.setMaximumSize(new java.awt.Dimension(50, 18));
        EntryTimeText.setMinimumSize(new java.awt.Dimension(50, 18));
        EntryTimeText.setPreferredSize(new java.awt.Dimension(50, 18));
        ModifySpacer.setMaximumSize(new java.awt.Dimension(20, 32767));
        ModifySpacer.setMinimumSize(new java.awt.Dimension(20, 10));
        ModifySpacer.setPreferredSize(new java.awt.Dimension(20, 10));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check In Options");
        PromptText.setText("Entry time was at least 15 minutes ago what do you want to do?");
        getContentPane().add(PromptText, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        OkButton.setText("OK");
        OkButton.setMaximumSize(new java.awt.Dimension(80, 23));
        OkButton.setMinimumSize(new java.awt.Dimension(80, 23));
        OkButton.setPreferredSize(new java.awt.Dimension(80, 23));
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        jPanel2.add(OkButton);

        jPanel7.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel2.add(jPanel7);

        CancelButton.setText("Cancel");
        CancelButton.setMaximumSize(new java.awt.Dimension(80, 23));
        CancelButton.setMinimumSize(new java.awt.Dimension(80, 23));
        CancelButton.setPreferredSize(new java.awt.Dimension(80, 23));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jPanel2.add(CancelButton);

        jPanel2.add(SpacerPanel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.add(jPanel6);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.add(jPanel5);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-450)/2, (screenSize.height-200)/2, 450, 200);
    }
    // </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        if (CheckInRadio.isSelected()) {
            if (isCheckInData) {
                myparent.saveCheckIn();
            } else {
                myparent.saveCheckOut();
            }
            
        } else if (ModifyRadio.isSelected()) {
            update_check_in_out_time_query myQuery = new update_check_in_out_time_query();
            AssembleCheckinScheduleType scheduleType = myparent.getCheckinType();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            myQuery.update(StaticDateTimeFunctions.fromTextToTime(EntryTimeText.getText()), myparent.getShiftId(), isCheckInData, format.format(scheduleType.getDate()), Integer.parseInt(Main_Window.parentOfApplication.getUser().getUserId()));
            RunQueriesEx myQueryEx = new RunQueriesEx();
            try {
                myparent.getMyConn(myQuery).prepQuery(myQuery);
                myQueryEx.add(myQuery);
                ArrayList rs = myparent.getMyConn(myQuery).executeQueryEx(myQueryEx);
                //myparent.shiftId = rs.getString("sid");
                myparent.saveCheckIn();
            } catch (Exception e) {}
        } else {
            myparent.saveCheckIn();
        }
        dispose();
    }//GEN-LAST:event_OkButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField EntryTimeText;
    private javax.swing.JPanel ModifySpacer;
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel PromptText;
    private javax.swing.JPanel SpacerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
    
}
